/*
 * Copyright 2026 PANTHEON.tech s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package rpc_test

import (
	"context"
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"

	sqlc "github.com/entguard/entguard/db"
	"github.com/entguard/entguard/pkg/test"
	pbapi "github.com/entguard/entguard/proto/v1"
	"github.com/entguard/entguard/service/api/v1"
	"github.com/entguard/entguard/service/rpc"
	"github.com/entguard/entguard/service/vcm"
)

const (
	HCClientRPCPort = "8084"
)

func TestIntegrationVpncGetConfiguration(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	conn := q.GetDbConnection(ctx)

	ss := make(map[int]api.Server)
	server1 := test.InsertSampleServer(t, ctx, conn, "server1").ToAPI()
	server2 := test.InsertSampleServer(t, ctx, conn, "server2", test.WithHealthCheckAddress(nil)).ToAPI()
	ss[server1.ID] = server1
	ss[server2.ID] = server2

	scs := make(map[int]*api.ServerWireGuardInterface)
	sc, err := vcm.GetWireGuardServerConfig(ctx, uManager.SQLcQ, test.TestEncryptionKey, server1.ID)
	require.NoError(t, err)
	scs[server1.ID] = sc.ToAPI()
	sc, err = vcm.GetWireGuardServerConfig(ctx, uManager.SQLcQ, test.TestEncryptionKey, server2.ID)
	require.NoError(t, err)
	scs[server2.ID] = sc.ToAPI()

	user := test.InsertSampleUser(t, ctx, q, "testUser").ToAPI()
	meta := &rpc.UserMetadata{
		UserID:       user.ID,
		MFAType:      user.MFAType,
		Notification: user.Notification,
	}

	addressPool := test.InsertSampleAddressPool(t, ctx, uManager.SQLcQ, test.NewSampleInsertAddressPoolParams("test-pool"))

	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, uManager.SQLcQ, user.ID, []int{addressPool.ID})
	deviceTemplateDNSs, err := uManager.SQLcQ.GetDeviceTemplateWireGuardIfaceDNSs(ctx, deviceTemplate.ID)
	require.NoError(t, err)

	device := test.InsertSampleDeviceAutoGenerated(t, ctx, uManager, deviceTemplate.ID)

	adjs := make(map[int]*sqlc.Adjacency)
	adjs[server1.ID] = test.InsertSampleAdjacency(t, ctx, uManager.SQLcQ, server1.ID, device.ID)
	adjs[server2.ID] = test.InsertSampleAdjacency(t, ctx, uManager.SQLcQ, server2.ID, device.ID)

	var expectedPeers []*pbapi.WireGuardPeer

	for sID := range adjs {
		var aips []string
		for _, aip := range adjs[sID].ClientSideAllowedIps {
			aips = append(aips, aip.String())
		}

		ep := &pbapi.WireGuardPeer{
			PublicKey:           scs[sID].PublicKey,
			PersistentKeepalive: scs[sID].PersistentKeepalive,
			PresharedKey:        test.OpenString(adjs[sID].PresharedKeyEncrypted),
			AllowedIps:          aips,
			Endpoint:            fmt.Sprintf("%s:%s", ss[sID].Endpoint, scs[sID].ListenPort),
			HealthcheckEndpoint: "",
		}

		if ss[sID].HealthCheckAddress != "" {
			ep.HealthcheckEndpoint = fmt.Sprintf("%s:%s", ss[sID].HealthCheckAddress, HCClientRPCPort)
		}

		expectedPeers = append(expectedPeers, ep)
	}

	newCtx := rpc.SetUserMetadata(ctx, meta)

	vpnCfg, err := vpnCServer.GetConfiguration(newCtx, &pbapi.ClientConfigurationRequest{
		ExternalDeviceId: device.ExternalDeviceID,
	})
	require.NoError(t, err)

	// need to test:
	// 1. correctness of returned configuration
	//    a. wireguard configuration
	//    b. session ID
	// 2. whether session is updated in DB

	// 1.a.
	require.NotNil(t, vpnCfg.GetConfiguration())
	wg := vpnCfg.GetConfiguration().GetWg()
	require.Equal(t, deviceTemplate.InterfaceName, wg.Name)

	iface := wg.GetIface()
	require.NotNil(t, iface)
	require.Equal(t, device.Addresses, iface.Addresses)
	require.Equal(t, deviceTemplateDNSs, iface.Dns)
	require.Equal(t, device.PrivateKey, iface.PrivateKey)
	require.Equal(t, fmt.Sprint(*deviceTemplate.ListenPort), iface.ListenPort)
	require.Equal(t, fmt.Sprint(*deviceTemplate.Mtu), iface.Mtu)

	peers := wg.GetPeers()
	require.ElementsMatch(t, expectedPeers, peers)

	// 2.
	updatedDevice, err := uManager.SQLcQ.GetDeviceByExternalID(ctx, device.ExternalDeviceID)
	require.NoError(t, err)
	require.NotEmpty(t, updatedDevice.SessionID)
	require.Len(t, updatedDevice.SessionID, 32)
	require.True(t, updatedDevice.LastTimeConnected.Valid)

	// 1.b.
	require.Equal(t, updatedDevice.SessionID, vpnCfg.GetSessionId())
}
