/*
 * Copyright 2026 PANTHEON.tech s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package rpc_test

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/peer"

	"github.com/entguard/entguard/pkg/certs"
	"github.com/entguard/entguard/pkg/test"
	pbapi "github.com/entguard/entguard/proto/v1"
	"github.com/entguard/entguard/service/rpc"
	"github.com/entguard/entguard/service/vcm"
)

func TestIntegrationTlsAuth(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	conn := q.GetDbConnection(ctx)

	sm := &rpc.ServerMetadata{
		ServerName: vcm.OrganizationUnit,
		ServerTag:  "testservertag",
	}
	sq := test.PostgresQueriesToVPNConfigQuerier(ctx, q)
	server := test.InsertSampleServer(t, ctx, conn, sm.ServerName)
	err := sq.InsertUsedTag(ctx, sm.ServerTag, server.ID)
	require.NoError(t, err)

	cert := vcManager.GetCACertificate(ctx)
	require.NotNil(t, cert)
	tagValue, err := asn1.Marshal(asn1.RawValue{
		Class: asn1.ClassUniversal,
		Tag:   asn1.TagUTF8String,
		Bytes: []byte(sm.ServerTag),
	})
	require.NoError(t, err)
	cert.Extensions = append(cert.Extensions, pkix.Extension{
		Id:    certs.ServerTagOID,
		Value: tagValue,
	})

	p := &peer.Peer{
		AuthInfo: credentials.TLSInfo{
			State: tls.ConnectionState{
				VerifiedChains: [][]*x509.Certificate{
					{cert},
				},
			},
		},
	}
	peerCtx := peer.NewContext(ctx, p)
	require.NotNil(t, peerCtx)

	tlsCtx, err := vpnSServer.TLSAuth(peerCtx)
	require.NoError(t, err)
	require.NotNil(t, tlsCtx)
	md, ok := rpc.GetServerMetadata(tlsCtx)
	require.True(t, ok)
	require.Equal(t, sm, md)
}

func TestIntegrationVpnsGetConfiguration(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	conn := q.GetDbConnection(ctx)

	sm := &rpc.ServerMetadata{
		ServerName: vcm.OrganizationUnit,
		ServerTag:  "testservertag",
	}
	srv := test.NewSampleServer(t, sm.ServerName)
	sc := test.NewSampleWGServerConfig()
	serverID, err := vcm.InsertServerWithWireGuardConfig(ctx, conn, test.TestEncryptionKey, srv, sc)
	require.NoError(t, err)
	srv.ID = serverID
	server := srv.ToAPI()
	pool := test.InsertSampleAddressPool(t, ctx, uManager.SQLcQ, test.NewSampleInsertAddressPoolParams("name"))
	user := test.InsertSampleUser(t, ctx, q, "testUser").ToAPI()
	dt := test.InsertSampleDeviceTemplate(t, ctx, uManager.SQLcQ, user.ID, []int{pool.ID})
	device := test.InsertSampleDeviceAutoGenerated(t, ctx, uManager, dt.ID)
	adj := test.InsertSampleAdjacency(t, ctx, uManager.SQLcQ, server.ID, device.ID)

	newCtx := rpc.SetServerMetadata(ctx, sm)

	vpnCfg, err := vpnSServer.GetConfiguration(newCtx, &pbapi.Empty{})
	require.NoError(t, err)
	require.NotNil(t, vpnCfg.GetWg())
	require.Equal(t, sc.InterfaceName, vpnCfg.GetWg().Name)

	iface := vpnCfg.GetWg().GetIface()
	require.NotNil(t, iface)
	require.Equal(t, sc.Addresses, iface.Addresses)
	require.Equal(t, sc.DNS, iface.Dns)
	require.Equal(t, sc.PrivateKey, iface.PrivateKey)
	require.Equal(t, fmt.Sprint(sc.ListenPort), iface.ListenPort)
	require.Equal(t, fmt.Sprint(sc.MTU), iface.Mtu)

	peers := vpnCfg.GetWg().GetPeers()

	var ssips []string
	for _, ssip := range adj.ServerSideAllowedIps {
		ssips = append(ssips, ssip.String())
	}
	require.Len(t, peers, 1)
	require.Equal(t, device.PublicKey, peers[0].PublicKey)
	require.Equal(t, test.OpenString(adj.PresharedKeyEncrypted), peers[0].PresharedKey)
	require.Equal(t, ssips, peers[0].AllowedIps)
}
