/*
 * Copyright 2026 PANTHEON.tech s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package user_test

import (
	"context"
	"encoding/base64"
	"net/netip"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	sqlc "github.com/entguard/entguard/db"
	"github.com/entguard/entguard/pkg/db"
	"github.com/entguard/entguard/pkg/ip"
	"github.com/entguard/entguard/pkg/nanoid"
	"github.com/entguard/entguard/pkg/test"
	"github.com/entguard/entguard/service/api/v1"
	"github.com/entguard/entguard/service/session"
	"github.com/entguard/entguard/service/user"
	"github.com/entguard/entguard/service/vcm"
)

func TestIntegrationGetDevicesByTemplateID(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	addressPool1Params := test.NewSampleInsertAddressPoolParams("test-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("10.0.0.1")
	addressPool1Params.EndAddr = netip.MustParseAddr("10.0.0.100")
	addressPool1Params.Description = "Test address pool 1"
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	addressPool2Params := test.NewSampleInsertAddressPoolParams("test-pool-2")
	addressPool2Params.StartAddr = netip.MustParseAddr("192.168.1.1")
	addressPool2Params.EndAddr = netip.MustParseAddr("192.168.1.100")
	addressPool2Params.Description = "Test address pool 2"
	addressPool2 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool2Params)

	u1 := test.InsertSampleUser(t, ctx, q, "user with devices")
	deviceTemplate1 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u1.ID, []int{addressPool1.ID, addressPool2.ID})
	uN := test.InsertSampleUser(t, ctx, q, "user without devices")
	deviceTemplateN := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, uN.ID, []int{addressPool1.ID, addressPool2.ID})

	device1 := test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate1.ID)
	device2 := test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate1.ID)
	device3 := test.InsertSampleDeviceManual(t, ctx, sqlcq, deviceTemplate1.ID)

	deviceInformation := "OS:          iOS\nOS Version:  17.2\nOS Build:    21C66\nAPP Version: 3.5.1\nDevice:      iPhone 15 Pro"

	cases := []struct {
		name             string
		deviceTemplateID int
		want             []*api.Device
		expectedError    error
	}{
		{
			name:             "device template with devices",
			deviceTemplateID: deviceTemplate1.ID,
			want: []*api.Device{
				{
					ID: device1.ID,
					DeviceData: api.DeviceData{
						Description: device1.Description,
						PrivateKey:  device1.PrivateKey,
						PublicKey:   device1.PublicKey,
						Addresses:   []string{"10.0.0.1/24", "192.168.1.1/24"},
					},
					ExternalDeviceID:  device1.ExternalDeviceID,
					SessionID:         device1.SessionID,
					LastTimeConnected: device1.LastTimeConnected,
					DeviceInformation: deviceInformation,
				},
				{
					ID: device2.ID,
					DeviceData: api.DeviceData{
						Description: device2.Description,
						PrivateKey:  device2.PrivateKey,
						PublicKey:   device2.PublicKey,
						Addresses:   []string{"10.0.0.2/24", "192.168.1.2/24"},
					},
					ExternalDeviceID:  device2.ExternalDeviceID,
					SessionID:         device2.SessionID,
					LastTimeConnected: device2.LastTimeConnected,
					DeviceInformation: deviceInformation,
				},
				{
					ID: device3.ID,
					DeviceData: api.DeviceData{
						Description: device3.Description,
						PrivateKey:  test.OpenString(device3.PrivateKeyEncrypted),
						PublicKey:   device3.PublicKey,
						Addresses:   nil,
					},
					ExternalDeviceID:  device3.ExternalDeviceID,
					SessionID:         device3.SessionID,
					LastTimeConnected: device3.LastTimeConnected.Time,
					DeviceInformation: deviceInformation,
				},
			},
			expectedError: nil,
		},
		{
			name:             "device template without devices",
			deviceTemplateID: deviceTemplateN.ID,
			want:             []*api.Device{},
			expectedError:    nil,
		},
		{
			name:             "device template not found",
			deviceTemplateID: 99999,
			expectedError:    user.ErrNotFound,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := manager.GetDevicesByTemplateID(ctx, tc.deviceTemplateID)

			if tc.expectedError != nil {
				require.Error(t, err)
				require.Equal(t, tc.expectedError, err)
				return
			}

			require.NoError(t, err)
			require.Equal(t, tc.want, got)
		})
	}
}

func TestIntegrationCreateDeviceWithAutogenData(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "testuser")

	addressPool1Params := test.NewSampleInsertAddressPoolParams("test-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("10.0.0.1")
	addressPool1Params.EndAddr = netip.MustParseAddr("10.0.0.100")
	addressPool1Params.Description = "Test address pool 1"
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	addressPool2Params := test.NewSampleInsertAddressPoolParams("test-pool-2")
	addressPool2Params.StartAddr = netip.MustParseAddr("192.168.1.1")
	addressPool2Params.EndAddr = netip.MustParseAddr("192.168.1.100")
	addressPool2Params.Description = "Test address pool 2"
	addressPool2 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool2Params)

	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool1.ID, addressPool2.ID})

	tests := []struct {
		name             string
		deviceTemplateID int
		expectError      bool
		errorMessage     string
		setupFunc        func()
	}{
		{
			name:             "successful device creation",
			deviceTemplateID: deviceTemplate.ID,
			expectError:      false,
		},
		{
			name:             "device template not found",
			deviceTemplateID: 99999,
			expectError:      true,
			errorMessage:     "not found",
		},
		{
			name:             "DPU limit exceeded",
			deviceTemplateID: deviceTemplate.ID,
			expectError:      true,
			errorMessage:     "DPU limit exceeded",
			setupFunc: func() {
				for i := 1; i < manager.Feats.GetDPULimit(); i++ { // creates DPULimit - 1 devices(1 device already created in the first test case)
					_, err := manager.CreateDeviceWithAutogenData(ctx, deviceTemplate.ID, "", "")
					require.NoError(t, err)
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			devicesBefore, err := sqlcq.GetDevicesByTemplateID(ctx, tt.deviceTemplateID)
			require.NoError(t, err)
			deviceCountBefore := len(devicesBefore)

			var addrCountBefore int
			if deviceCountBefore > 0 {
				for _, device := range devicesBefore {
					addrs, err := sqlcq.GetDeviceWireGuardIfaceAddrs(ctx, device.ID)
					require.NoError(t, err)
					addrCountBefore += len(addrs)
				}
			}

			// Setup specific test conditions
			if tt.setupFunc != nil {
				tt.setupFunc()
			}

			_, createErr := manager.CreateDeviceWithAutogenData(ctx, tt.deviceTemplateID, "", "")

			if tt.expectError {
				require.Error(t, createErr)
				if tt.errorMessage != "" {
					require.Contains(t, createErr.Error(), tt.errorMessage)
				}
				return
			}
			require.NoError(t, createErr)

			devicesAfter, err := sqlcq.GetDevicesByTemplateID(ctx, tt.deviceTemplateID)
			require.NoError(t, err)
			require.Equal(t, deviceCountBefore+1, len(devicesAfter))

			newDevice := devicesAfter[len(devicesAfter)-1]

			require.Equal(t, tt.deviceTemplateID, newDevice.DeviceTemplateID)
			require.NotEmpty(t, test.OpenString(newDevice.PrivateKeyEncrypted))
			require.NotEmpty(t, newDevice.PublicKey)
			require.NotEqual(t, test.OpenString(newDevice.PrivateKeyEncrypted), newDevice.PublicKey)
			require.Empty(t, newDevice.Description)

			addrs, err := sqlcq.GetDeviceWireGuardIfaceAddrs(ctx, newDevice.ID)
			require.NoError(t, err)
			require.Equal(t, 2, len(addrs))

			foundPool1Addr := false
			foundPool2Addr := false
			for _, addr := range addrs {
				addrBytes := addr.Addr().As4()
				switch addrBytes[0] {
				case 10: // 10.x.x.x
					foundPool1Addr = true
				case 192: // 192.x.x.x
					foundPool2Addr = true
				}
			}
			require.True(t, foundPool1Addr, "Should have address from pool 1")
			require.True(t, foundPool2Addr, "Should have address from pool 2")

			_, err = base64.StdEncoding.DecodeString(test.OpenString(newDevice.PrivateKeyEncrypted))
			require.NoError(t, err, "Private key should be valid base64")

			_, err = base64.StdEncoding.DecodeString(newDevice.PublicKey)
			require.NoError(t, err, "Public key should be valid base64")

		})
	}
}

func TestIntegrationCreateDeviceWithAutogenData_CreateAdjacencies(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	conn := q.GetDbConnection(ctx)

	server1 := test.NewSampleServerWithoutHC(t, "server1")
	sc1 := test.NewSampleWGServerConfig()
	sc1.Addresses = []string{"1.1.1.1/24"}
	server1ID, err := vcm.InsertServerWithWireGuardConfig(ctx, conn, test.TestEncryptionKey, server1, sc1)
	require.NoError(t, err)

	server2 := test.NewSampleServerWithoutHC(t, "server2")
	sc2 := test.NewSampleWGServerConfig()
	sc2.Addresses = []string{"1.1.1.2/24"}
	server2ID, err := vcm.InsertServerWithWireGuardConfig(ctx, conn, test.TestEncryptionKey, server2, sc2)
	require.NoError(t, err)

	_ = test.InsertSampleServer(t, ctx, conn, "serverWithoutAdjacencies", test.WithHealthCheckAddress(nil))

	addressPool1Params := test.NewSampleInsertAddressPoolParams("test-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("1.1.1.11")
	addressPool1Params.EndAddr = netip.MustParseAddr("1.1.1.99")
	addressPool1Params.Description = "Test address pool 1"
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	user1 := test.InsertSampleUser(t, ctx, q, "testuser1")
	deviceTemplate1 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, user1.ID, []int{addressPool1.ID})
	user2 := test.InsertSampleUser(t, ctx, q, "testuser2")
	deviceTemplate2 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, user2.ID, []int{addressPool1.ID})
	user3 := test.InsertSampleUser(t, ctx, q, "testuser3")
	deviceTemplate3 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, user3.ID, []int{addressPool1.ID})

	adjTmpl_s1_u1 := test.InsertAdjacencyTemplate(t, ctx, sqlcq, &sqlc.InsertAdjacencyTemplateParams{
		ServerID:             server1ID,
		UserID:               user1.ID,
		ClientSideAllowedIps: []netip.Prefix{netip.MustParsePrefix("10.10.10.0/24")},
		UsePresharedKey:      true,
	})
	adjTmpl_s1_u2 := test.InsertAdjacencyTemplate(t, ctx, sqlcq, &sqlc.InsertAdjacencyTemplateParams{
		ServerID:             server1ID,
		UserID:               user2.ID,
		ClientSideAllowedIps: []netip.Prefix{netip.MustParsePrefix("20.20.20.0/24")},
		UsePresharedKey:      true,
	})
	adjTmpl_s2_u2 := test.InsertAdjacencyTemplate(t, ctx, sqlcq, &sqlc.InsertAdjacencyTemplateParams{
		ServerID:             server2ID,
		UserID:               user2.ID,
		ClientSideAllowedIps: []netip.Prefix{netip.MustParsePrefix("30.30.30.0/24"), netip.MustParsePrefix("40.40.0.0/16")},
		UsePresharedKey:      true,
	})

	cases := []struct {
		name                         string
		deviceTemplateID             int
		expectedAdjacencyTemplates   []*sqlc.AdjacencyTemplate
		expectedServerSideAllowedIPs []netip.Prefix
		expectError                  bool
	}{
		{
			name:                         "one adjacency template",
			deviceTemplateID:             deviceTemplate1.ID,
			expectedAdjacencyTemplates:   []*sqlc.AdjacencyTemplate{adjTmpl_s1_u1},
			expectedServerSideAllowedIPs: []netip.Prefix{netip.MustParsePrefix("1.1.1.11/32")},
			expectError:                  false,
		},
		{
			name:                         "multiple adjacency templates",
			deviceTemplateID:             deviceTemplate2.ID,
			expectedAdjacencyTemplates:   []*sqlc.AdjacencyTemplate{adjTmpl_s1_u2, adjTmpl_s2_u2},
			expectedServerSideAllowedIPs: []netip.Prefix{netip.MustParsePrefix("1.1.1.12/32")},
			expectError:                  false,
		},
		{
			name:                         "another device for the same user",
			deviceTemplateID:             deviceTemplate2.ID,
			expectedAdjacencyTemplates:   []*sqlc.AdjacencyTemplate{adjTmpl_s1_u2, adjTmpl_s2_u2},
			expectedServerSideAllowedIPs: []netip.Prefix{netip.MustParsePrefix("1.1.1.13/32")},
			expectError:                  false,
		},
		{
			name:                         "no adjacency template",
			deviceTemplateID:             deviceTemplate3.ID,
			expectedAdjacencyTemplates:   []*sqlc.AdjacencyTemplate{},
			expectedServerSideAllowedIPs: []netip.Prefix{},
			expectError:                  false,
		},
		{
			name:             "do not create device adjacenices on error",
			deviceTemplateID: 99999,
			expectError:      true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			countBefore := test.CountTableRows(t, conn, "adjacencies")
			device, err := manager.CreateDeviceWithAutogenData(ctx, tc.deviceTemplateID, "", "")
			countAfter := test.CountTableRows(t, conn, "adjacencies")

			if tc.expectError {
				require.Error(t, err)
				require.Equal(t, countBefore, countAfter)
				return
			}
			require.NoError(t, err)
			require.Equal(t, countBefore+len(tc.expectedAdjacencyTemplates), countAfter)

			adjs, err := sqlcq.GetDeviceWireGuardAdjacencies(ctx, device.ID)
			require.NoError(t, err)

			uniquePresharedKeys := make(map[string]struct{})
			for _, adjTmpl := range tc.expectedAdjacencyTemplates {
				count := 0
				for _, adj := range adjs {
					if adj.Serverid == adjTmpl.ServerID {
						count++
						require.Equal(t, adjTmpl.ClientSideAllowedIps, adj.ClientSideAllowedIps)
						require.Equal(t, tc.expectedServerSideAllowedIPs, adj.ServerSideAllowedIps)

						psk := test.OpenString(adj.PresharedKeyEncrypted)
						if adjTmpl.UsePresharedKey {
							require.NotEmpty(t, psk)
							_, exists := uniquePresharedKeys[psk]
							require.False(t, exists)
							uniquePresharedKeys[psk] = struct{}{}
						} else {
							require.Empty(t, psk)
						}
					}
				}
				require.Equal(t, 1, count)
			}
		})
	}
}

func TestIntegrationCreateDevice(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "testuser-custom")

	addressPool1Params := test.NewSampleInsertAddressPoolParams("custom-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("10.10.0.1")
	addressPool1Params.EndAddr = netip.MustParseAddr("10.10.0.100")
	addressPool1Params.Description = "Custom test address pool 1"
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	addressPool2Params := test.NewSampleInsertAddressPoolParams("custom-pool-2")
	addressPool2Params.StartAddr = netip.MustParseAddr("192.168.10.1")
	addressPool2Params.EndAddr = netip.MustParseAddr("192.168.10.100")
	addressPool2Params.Description = "Custom test address pool 2"
	addressPool2 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool2Params)

	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool1.ID, addressPool2.ID})

	// validPrivKey / validPubKey are proper 32-byte base64-encoded WireGuard keys.
	const (
		validPrivKey  = "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo="
		validPubKey   = "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo="
		validPrivKey2 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
		validPubKey2  = "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE="
	)

	tests := []struct {
		name             string
		deviceTemplateID int
		deviceData       *api.DeviceData
		expectError      bool
		expectedErrType  error
		errorMessage     string
		setupFunc        func()
	}{
		{
			name:             "successful device creation with custom data",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				Description: "My Custom Device",
				PrivateKey:  validPrivKey,
				PublicKey:   validPubKey,
				Addresses:   []string{"10.50.50.50/24", "192.168.200.200/16"},
			},
			expectError: false,
		},
		{
			name:             "successful device creation with empty description",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				Description: "",
				PrivateKey:  validPrivKey2,
				PublicKey:   validPubKey2,
				Addresses:   []string{"172.16.0.1/16"},
			},
			expectError: false,
		},
		{
			name:             "nil device data",
			deviceTemplateID: deviceTemplate.ID,
			deviceData:       nil,
			expectError:      true,
			expectedErrType:  user.ErrInvalidData,
			errorMessage:     "DeviceData is required",
		},
		{
			name:             "empty public key",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				PrivateKey: validPrivKey,
				PublicKey:  "",
				Addresses:  []string{"10.0.0.1/24"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name:             "empty private key",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				PrivateKey: "",
				PublicKey:  validPubKey,
				Addresses:  []string{"10.0.0.1/24"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name:             "invalid public key",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				PrivateKey: validPrivKey,
				PublicKey:  "not-a-valid-key",
				Addresses:  []string{"10.0.0.1/24"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name:             "invalid private key",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				PrivateKey: "not-a-valid-key",
				PublicKey:  validPubKey,
				Addresses:  []string{"10.0.0.1/24"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name:             "empty addresses",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				PrivateKey: validPrivKey,
				PublicKey:  validPubKey,
				Addresses:  []string{},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name:             "invalid address format",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				Description: "Invalid Address Device",
				PrivateKey:  validPrivKey,
				PublicKey:   validPubKey,
				Addresses:   []string{"not-a-valid-address"},
			},
			expectError:  true,
			errorMessage: "invalid address",
		},
		{
			name:             "multiple addresses with one invalid",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				Description: "Mixed Addresses Device",
				PrivateKey:  validPrivKey,
				PublicKey:   validPubKey,
				Addresses:   []string{"10.0.0.1/24", "invalid-address", "192.168.1.1/24"},
			},
			expectError:  true,
			errorMessage: "invalid address",
		},
		{
			name:             "device template not found",
			deviceTemplateID: 99999,
			deviceData: &api.DeviceData{
				Description: "Test Device",
				PrivateKey:  validPrivKey,
				PublicKey:   validPubKey,
				Addresses:   []string{"10.0.0.1/24"},
			},
			expectError:  true,
			errorMessage: "not found",
		},
		{
			name:             "DPU limit exceeded",
			deviceTemplateID: deviceTemplate.ID,
			deviceData: &api.DeviceData{
				Description: "Over Limit Device",
				PrivateKey:  validPrivKey,
				PublicKey:   validPubKey,
				Addresses:   []string{"10.0.0.1/24"},
			},
			expectError:  true,
			errorMessage: "DPU limit exceeded",
			setupFunc: func() {
				existingDevices, err := sqlcq.GetDevicesByTemplateID(ctx, deviceTemplate.ID)
				require.NoError(t, err)
				devicesToCreate := manager.Feats.GetDPULimit() - len(existingDevices)

				for i := 0; i < devicesToCreate; i++ {
					_, err := manager.CreateDeviceWithAutogenData(ctx, deviceTemplate.ID, "", "")
					require.NoError(t, err)
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			devicesBefore, err := sqlcq.GetDevicesByTemplateID(ctx, tt.deviceTemplateID)
			require.NoError(t, err)
			deviceCountBefore := len(devicesBefore)

			var addrCountBefore int
			if deviceCountBefore > 0 {
				for _, device := range devicesBefore {
					addrs, err := sqlcq.GetDeviceWireGuardIfaceAddrs(ctx, device.ID)
					require.NoError(t, err)
					addrCountBefore += len(addrs)
				}
			}

			if tt.setupFunc != nil {
				tt.setupFunc()
			}

			device, createErr := manager.CreateDevice(ctx, tt.deviceTemplateID, tt.deviceData)

			if tt.expectError {
				require.Error(t, createErr)
				if tt.expectedErrType != nil {
					require.ErrorIs(t, createErr, tt.expectedErrType)
				}
				if tt.errorMessage != "" {
					require.Contains(t, createErr.Error(), tt.errorMessage)
				}
				return
			}
			require.NoError(t, createErr)

			devicesAfter, err := sqlcq.GetDevicesByTemplateID(ctx, tt.deviceTemplateID)
			require.NoError(t, err)
			require.Equal(t, deviceCountBefore+1, len(devicesAfter))

			require.Equal(t, tt.deviceData.Description, device.Description)
			require.Equal(t, tt.deviceData.PrivateKey, device.PrivateKey)
			require.Equal(t, tt.deviceData.PublicKey, device.PublicKey)
			require.ElementsMatch(t, tt.deviceData.Addresses, device.Addresses)
			require.Empty(t, device.ExternalDeviceID)
			require.Empty(t, device.SessionID)

			newDevice, err := sqlcq.GetDeviceByID(ctx, device.ID)
			require.NoError(t, err)
			require.Equal(t, tt.deviceTemplateID, newDevice.DeviceTemplateID)
			require.Equal(t, tt.deviceData.Description, newDevice.Description)
			require.Equal(t, tt.deviceData.PrivateKey, test.OpenString(newDevice.PrivateKeyEncrypted))
			require.Equal(t, tt.deviceData.PublicKey, newDevice.PublicKey)
			require.NotEqual(t, test.OpenString(newDevice.PrivateKeyEncrypted), newDevice.PublicKey)

			addrs, err := sqlcq.GetDeviceWireGuardIfaceAddrs(ctx, newDevice.ID)
			require.NoError(t, err)
			require.Equal(t, len(tt.deviceData.Addresses), len(addrs))

			var addrStrings []string
			for _, addr := range addrs {
				addrStrings = append(addrStrings, addr.String())
			}
			require.ElementsMatch(t, tt.deviceData.Addresses, addrStrings)
		})
	}
}

func TestIntegrationGenerateDeviceData(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "testuser-generate")

	addressPool1Params := test.NewSampleInsertAddressPoolParams("generate-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("10.20.0.1")
	addressPool1Params.EndAddr = netip.MustParseAddr("10.20.0.100")
	addressPool1Params.Description = "Generate test address pool 1"
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	addressPool2Params := test.NewSampleInsertAddressPoolParams("generate-pool-2")
	addressPool2Params.StartAddr = netip.MustParseAddr("192.168.20.1")
	addressPool2Params.EndAddr = netip.MustParseAddr("192.168.20.100")
	addressPool2Params.Description = "Generate test address pool 2"
	addressPool2 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool2Params)

	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool1.ID, addressPool2.ID})

	tests := []struct {
		name             string
		deviceTemplateID int
		expectError      bool
		errorMessage     string
		setupFunc        func()
	}{
		{
			name:             "successful device data generation",
			deviceTemplateID: deviceTemplate.ID,
			expectError:      false,
		},
		{
			name:             "device template not found",
			deviceTemplateID: 99999,
			expectError:      true,
			errorMessage:     "not found",
		},
		{
			name:             "DPU limit exceeded",
			deviceTemplateID: deviceTemplate.ID,
			expectError:      true,
			errorMessage:     "DPU limit exceeded",
			setupFunc: func() {
				existingDevices, err := sqlcq.GetDevicesByTemplateID(ctx, deviceTemplate.ID)
				require.NoError(t, err)
				devicesToCreate := manager.Feats.GetDPULimit() - len(existingDevices)

				for i := 0; i < devicesToCreate; i++ {
					_, err := manager.CreateDeviceWithAutogenData(ctx, deviceTemplate.ID, "", "")
					require.NoError(t, err)
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			deviceCountBefore := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")

			if tt.setupFunc != nil {
				tt.setupFunc()
			}

			deviceData, err := manager.GenerateDeviceData(ctx, tt.deviceTemplateID)

			if tt.expectError {
				require.Error(t, err)
				if tt.errorMessage != "" {
					require.Contains(t, err.Error(), tt.errorMessage)
				}
				return
			}
			require.NoError(t, err)
			require.NotNil(t, deviceData)

			deviceCountAfter := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")
			require.Equal(t, deviceCountBefore, deviceCountAfter)

			require.Empty(t, deviceData.Description)
			require.NotEmpty(t, deviceData.PrivateKey)
			require.NotEmpty(t, deviceData.PublicKey)
			require.NotEqual(t, deviceData.PrivateKey, deviceData.PublicKey)

			require.Len(t, deviceData.Addresses, 2)

			foundPool1Addr := false
			foundPool2Addr := false
			for _, addrStr := range deviceData.Addresses {
				addr, err := netip.ParsePrefix(addrStr)
				require.NoError(t, err)

				addrBytes := addr.Addr().As4()
				if addrBytes[0] == 10 && addrBytes[1] == 20 { // 10.20.x.x
					foundPool1Addr = true
				} else if addrBytes[0] == 192 && addrBytes[1] == 168 && addrBytes[2] == 20 { // 192.168.20.x
					foundPool2Addr = true
				}
			}
			require.True(t, foundPool1Addr, "Should have address from pool 1")
			require.True(t, foundPool2Addr, "Should have address from pool 2")

			_, err = base64.StdEncoding.DecodeString(deviceData.PrivateKey)
			require.NoError(t, err, "Private key should be valid base64")

			_, err = base64.StdEncoding.DecodeString(deviceData.PublicKey)
			require.NoError(t, err, "Public key should be valid base64")
		})
	}
}

func TestIntegrationGenerateDeviceData_MultipleGenerations(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "testuser-generate")

	addressPool1Params := test.NewSampleInsertAddressPoolParams("generate-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("10.30.0.1")
	addressPool1Params.EndAddr = netip.MustParseAddr("10.30.0.100")
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	addressPool2Params := test.NewSampleInsertAddressPoolParams("generate-pool-2")
	addressPool2Params.StartAddr = netip.MustParseAddr("192.168.30.1")
	addressPool2Params.EndAddr = netip.MustParseAddr("192.168.30.100")
	addressPool2 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool2Params)

	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool1.ID, addressPool2.ID})

	const numGenerations = 5
	generatedData := make([]*api.DeviceData, numGenerations)

	for i := 0; i < numGenerations; i++ {
		data, err := manager.GenerateDeviceData(ctx, deviceTemplate.ID)
		require.NoError(t, err)
		require.NotNil(t, data)
		generatedData[i] = data
	}

	privateKeys := make(map[string]bool)
	publicKeys := make(map[string]bool)
	for _, data := range generatedData {
		privateKeys[data.PrivateKey] = true
		publicKeys[data.PublicKey] = true
	}
	require.Len(t, privateKeys, numGenerations)
	require.Len(t, publicKeys, numGenerations)

	// Note: Addresses will be reused across generations since GenerateDeviceData
	// doesn't actually create devices or reserve addresses

	devices, err := sqlcq.GetDevicesByTemplateID(ctx, deviceTemplate.ID)
	require.NoError(t, err)
	require.Empty(t, devices)
}

func TestIntegrationCreateDevice_CreateAdjacencies(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	conn := q.GetDbConnection(ctx)

	server1 := test.NewSampleServerWithoutHC(t, "server1")
	sc1 := test.NewSampleWGServerConfig()
	sc1.Addresses = []string{"1.1.1.1/24"}
	server1ID, err := vcm.InsertServerWithWireGuardConfig(ctx, conn, test.TestEncryptionKey, server1, sc1)
	require.NoError(t, err)

	server2 := test.NewSampleServerWithoutHC(t, "server2")
	sc2 := test.NewSampleWGServerConfig()
	sc2.Addresses = []string{"1.1.1.2/24"}
	server2ID, err := vcm.InsertServerWithWireGuardConfig(ctx, conn, test.TestEncryptionKey, server2, sc2)
	require.NoError(t, err)

	_ = test.InsertSampleServer(t, ctx, conn, "serverWithoutAdjacencies", test.WithHealthCheckAddress(nil))

	addressPool1Params := test.NewSampleInsertAddressPoolParams("test-pool-custom")
	addressPool1Params.StartAddr = netip.MustParseAddr("1.1.1.11")
	addressPool1Params.EndAddr = netip.MustParseAddr("1.1.1.99")
	addressPool1Params.Description = "Test address pool custom"
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	user1 := test.InsertSampleUser(t, ctx, q, "testuser-custom-1")
	deviceTemplate1 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, user1.ID, []int{addressPool1.ID})
	user2 := test.InsertSampleUser(t, ctx, q, "testuser-custom-2")
	deviceTemplate2 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, user2.ID, []int{addressPool1.ID})
	user3 := test.InsertSampleUser(t, ctx, q, "testuser-custom-3")
	deviceTemplate3 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, user3.ID, []int{addressPool1.ID})

	adjTmpl_s1_u1 := test.InsertAdjacencyTemplate(t, ctx, sqlcq, &sqlc.InsertAdjacencyTemplateParams{
		ServerID:             server1ID,
		UserID:               user1.ID,
		ClientSideAllowedIps: []netip.Prefix{netip.MustParsePrefix("10.10.10.0/24")},
		UsePresharedKey:      true,
	})
	adjTmpl_s1_u2 := test.InsertAdjacencyTemplate(t, ctx, sqlcq, &sqlc.InsertAdjacencyTemplateParams{
		ServerID:             server1ID,
		UserID:               user2.ID,
		ClientSideAllowedIps: []netip.Prefix{netip.MustParsePrefix("20.20.20.0/24")},
		UsePresharedKey:      true,
	})
	adjTmpl_s2_u2 := test.InsertAdjacencyTemplate(t, ctx, sqlcq, &sqlc.InsertAdjacencyTemplateParams{
		ServerID:             server2ID,
		UserID:               user2.ID,
		ClientSideAllowedIps: []netip.Prefix{netip.MustParsePrefix("30.30.30.0/24"), netip.MustParsePrefix("40.40.0.0/16")},
		UsePresharedKey:      true,
	})

	cases := []struct {
		name                         string
		deviceTemplateID             int
		deviceData                   *api.DeviceData
		expectedAdjacencyTemplates   []*sqlc.AdjacencyTemplate
		expectedServerSideAllowedIPs []netip.Prefix
		expectError                  bool
	}{
		{
			name:             "one adjacency template with custom data",
			deviceTemplateID: deviceTemplate1.ID,
			deviceData: &api.DeviceData{
				Description: "Custom Device 1",
				PrivateKey:  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
				PublicKey:   "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				Addresses:   []string{"1.1.1.50/32"},
			},
			expectedAdjacencyTemplates:   []*sqlc.AdjacencyTemplate{adjTmpl_s1_u1},
			expectedServerSideAllowedIPs: []netip.Prefix{netip.MustParsePrefix("1.1.1.50/32")},
			expectError:                  false,
		},
		{
			name:             "multiple adjacency templates with custom data",
			deviceTemplateID: deviceTemplate2.ID,
			deviceData: &api.DeviceData{
				Description: "Custom Device 2",
				PrivateKey:  "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				PublicKey:   "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo=",
				Addresses:   []string{"1.1.1.51/32"},
			},
			expectedAdjacencyTemplates:   []*sqlc.AdjacencyTemplate{adjTmpl_s1_u2, adjTmpl_s2_u2},
			expectedServerSideAllowedIPs: []netip.Prefix{netip.MustParsePrefix("1.1.1.51/32")},
			expectError:                  false,
		},
		{
			name:             "no adjacency template with custom data",
			deviceTemplateID: deviceTemplate3.ID,
			deviceData: &api.DeviceData{
				Description: "Custom Device 3",
				PrivateKey:  "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE=",
				PublicKey:   "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE=",
				Addresses:   []string{"1.1.1.53/32"},
			},
			expectedAdjacencyTemplates:   []*sqlc.AdjacencyTemplate{},
			expectedServerSideAllowedIPs: []netip.Prefix{},
			expectError:                  false,
		},
		{
			name:             "do not create device adjacencies on error",
			deviceTemplateID: 99999,
			deviceData: &api.DeviceData{
				Description: "Error Device",
				PrivateKey:  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
				PublicKey:   "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				Addresses:   []string{"1.1.1.54/32"},
			},
			expectError: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			countBefore := test.CountTableRows(t, conn, "adjacencies")
			device, err := manager.CreateDevice(ctx, tc.deviceTemplateID, tc.deviceData)
			countAfter := test.CountTableRows(t, conn, "adjacencies")

			if tc.expectError {
				require.Error(t, err)
				require.Equal(t, countBefore, countAfter)
				return
			}
			require.NoError(t, err)
			require.Equal(t, countBefore+len(tc.expectedAdjacencyTemplates), countAfter)

			// Verify device has custom data
			require.Equal(t, tc.deviceData.Description, device.Description)
			require.Equal(t, tc.deviceData.PrivateKey, device.PrivateKey)
			require.Equal(t, tc.deviceData.PublicKey, device.PublicKey)
			require.ElementsMatch(t, tc.deviceData.Addresses, device.Addresses)

			adjs, err := sqlcq.GetDeviceWireGuardAdjacencies(ctx, device.ID)
			require.NoError(t, err)

			uniquePresharedKeys := make(map[string]struct{})
			for _, adjTmpl := range tc.expectedAdjacencyTemplates {
				count := 0
				for _, adj := range adjs {
					if adj.Serverid == adjTmpl.ServerID {
						count++
						require.Equal(t, adjTmpl.ClientSideAllowedIps, adj.ClientSideAllowedIps)
						require.ElementsMatch(t, tc.expectedServerSideAllowedIPs, adj.ServerSideAllowedIps)

						psk := test.OpenString(adj.PresharedKeyEncrypted)
						if adjTmpl.UsePresharedKey {
							require.NotEmpty(t, psk)
							_, exists := uniquePresharedKeys[psk]
							require.False(t, exists)
							uniquePresharedKeys[psk] = struct{}{}
						} else {
							require.Empty(t, psk)
						}
					}
				}
				require.Equal(t, 1, count)
			}
		})
	}
}

func TestIntegrationUpdateDevice(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	addressPool1Params := test.NewSampleInsertAddressPoolParams("test-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("10.0.0.1")
	addressPool1Params.EndAddr = netip.MustParseAddr("10.0.0.100")
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	u := test.InsertSampleUser(t, ctx, q, "testuser")
	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool1.ID})

	_ = test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate.ID)
	device2 := test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate.ID)
	_ = test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate.ID)

	cases := []struct {
		name             string
		id               int
		deviceTemplateID int
		deviceUpdate     api.DeviceData
		expectedDevice   api.Device
		expectError      bool
		expectedErrType  error
	}{
		{
			name:             "successful device update",
			id:               device2.ID,
			deviceTemplateID: deviceTemplate.ID,
			deviceUpdate: api.DeviceData{
				Description: "new description",
				PrivateKey:  "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				PublicKey:   "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo=",
				Addresses:   []string{"20.20.20.20/24", "30.30.30.30/16"},
			},
			expectedDevice: api.Device{
				ID: device2.ID,
				DeviceData: api.DeviceData{
					Description: "new description",
					PrivateKey:  "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
					PublicKey:   "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo=",
					Addresses:   []string{"20.20.20.20/24", "30.30.30.30/16"},
				},
				ExternalDeviceID:  device2.ExternalDeviceID,
				SessionID:         "",
				LastTimeConnected: time.Time{},
				DeviceInformation: "OS:          iOS\nOS Version:  17.2\nOS Build:    21C66\nAPP Version: 3.5.1\nDevice:      iPhone 15 Pro",
			},
			expectError: false,
		},
		{
			name: "empty public key",
			id:   device2.ID,
			deviceUpdate: api.DeviceData{
				PrivateKey: "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				PublicKey:  "",
				Addresses:  []string{"10.0.0.1/32"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name: "empty private key",
			id:   device2.ID,
			deviceUpdate: api.DeviceData{
				PrivateKey: "",
				PublicKey:  "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo=",
				Addresses:  []string{"10.0.0.1/32"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name: "invalid public key",
			id:   device2.ID,
			deviceUpdate: api.DeviceData{
				PrivateKey: "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				PublicKey:  "not-a-valid-key",
				Addresses:  []string{"10.0.0.1/32"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name: "invalid private key",
			id:   device2.ID,
			deviceUpdate: api.DeviceData{
				PrivateKey: "not-a-valid-key",
				PublicKey:  "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo=",
				Addresses:  []string{"10.0.0.1/32"},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name: "empty addresses",
			id:   device2.ID,
			deviceUpdate: api.DeviceData{
				PrivateKey: "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				PublicKey:  "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo=",
				Addresses:  []string{},
			},
			expectError:     true,
			expectedErrType: user.ErrInvalidData,
		},
		{
			name: "non-existing device",
			id:   99999,
			deviceUpdate: api.DeviceData{
				PrivateKey: "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV7pDup0xb/2hLAUo=",
				PublicKey:  "uBEC+jx8Yvr9Aw+LIzro0/wZfgpV8pDup0xb/2hLAUo=",
				Addresses:  []string{"10.0.0.1/32"},
			},
			expectError: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			deviceCountBefore := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")

			err := manager.UpdateDevice(ctx, tc.id, tc.deviceUpdate)
			if tc.expectError {
				require.Error(t, err)
				if tc.expectedErrType != nil {
					require.ErrorIs(t, err, tc.expectedErrType)
				}
				return
			}
			require.NoError(t, err)

			newDeviceList, err := manager.GetDevicesByTemplateID(ctx, tc.deviceTemplateID)
			require.NoError(t, err)
			require.Len(t, newDeviceList, deviceCountBefore)

			var newDevice api.Device
			for _, d := range newDeviceList {
				if d.ID == tc.id {
					newDevice = *d
					break
				}
			}
			require.NotEmpty(t, newDevice)
			require.Equal(t, tc.expectedDevice, newDevice)
		})
	}
}

func TestIntegrationDeleteDevice(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	addressPool1Params := test.NewSampleInsertAddressPoolParams("test-pool-1")
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	u := test.InsertSampleUser(t, ctx, q, "testuser")
	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool1.ID})

	_ = test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate.ID)
	device2 := test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate.ID)
	_ = test.InsertSampleDeviceAutoGenerated(t, ctx, manager, deviceTemplate.ID)

	cases := []struct {
		name                    string
		id                      int
		deviceTemplateID        int
		numberOfDeviceAddresses int
		expectedError           error
	}{
		{
			name:                    "successful device delete",
			id:                      device2.ID,
			deviceTemplateID:        deviceTemplate.ID,
			numberOfDeviceAddresses: 1,
			expectedError:           nil,
		},
		{
			name:          "non-existing device",
			id:            99999,
			expectedError: user.ErrNotFound,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var deviceListBefore []*api.Device
			var addrCountBefore int
			var err error

			if tc.expectedError == nil {
				deviceListBefore, err = manager.GetDevicesByTemplateID(ctx, tc.deviceTemplateID)
				require.NoError(t, err)

				for _, device := range deviceListBefore {
					addrCountBefore += len(device.Addresses)
				}
			}

			err = manager.DeleteDevice(ctx, tc.id)

			if tc.expectedError != nil {
				require.Error(t, err)
				require.Equal(t, tc.expectedError, err)
				return
			}
			require.NoError(t, err)

			deviceListAfter, err := manager.GetDevicesByTemplateID(ctx, tc.deviceTemplateID)
			require.NoError(t, err)
			require.Len(t, deviceListAfter, len(deviceListBefore)-1)

			var addrCountAfter int
			for _, device := range deviceListAfter {
				addrCountAfter += len(device.Addresses)
			}
			require.Equal(t, addrCountBefore-tc.numberOfDeviceAddresses, addrCountAfter)

			a, err := sqlcq.GetDeviceWireGuardIfaceAddrs(ctx, tc.id)
			require.NoError(t, err)
			require.Empty(t, a)
		})
	}
}

func TestIntegrationResyncDevices(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	addressPool1Params := test.NewSampleInsertAddressPoolParams("resync-pool-1")
	addressPool1Params.StartAddr = netip.MustParseAddr("10.100.0.1")
	addressPool1Params.EndAddr = netip.MustParseAddr("10.100.0.10")
	addressPool1Params.NetMask = 24
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool1Params)

	addressPool2Params := test.NewSampleInsertAddressPoolParams("resync-pool-2")
	addressPool2Params.StartAddr = netip.MustParseAddr("192.168.100.1")
	addressPool2Params.EndAddr = netip.MustParseAddr("192.168.100.10")
	addressPool2Params.NetMask = 24
	addressPool2 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool2Params)

	addressPool3Params := test.NewSampleInsertAddressPoolParams("resync-pool-3-small")
	addressPool3Params.StartAddr = netip.MustParseAddr("172.16.0.1")
	addressPool3Params.EndAddr = netip.MustParseAddr("172.16.0.1") // only 1 address available
	addressPool3Params.NetMask = 24
	addressPool3 := test.InsertSampleAddressPool(t, ctx, sqlcq, addressPool3Params)

	pool1Range := ip.MustParseAddrRange("10.100.0.1-10.100.0.10/24")
	pool2Range := ip.MustParseAddrRange("192.168.100.1-192.168.100.10/24")

	// devices with correct addresses
	u1 := test.InsertSampleUser(t, ctx, q, "resync-user1")
	dt1 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u1.ID, []int{addressPool1.ID, addressPool2.ID})
	_ = test.InsertSampleDeviceAutoGenerated(t, ctx, manager, dt1.ID)
	_ = test.InsertSampleDeviceAutoGenerated(t, ctx, manager, dt1.ID)

	// device with missing address
	u2 := test.InsertSampleUser(t, ctx, q, "resync-user2")
	dt2 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u2.ID, []int{addressPool1.ID, addressPool2.ID})
	device2 := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt2.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, device2.ID, "10.100.0.5/24")

	// device with invalid address
	u3 := test.InsertSampleUser(t, ctx, q, "resync-user3")
	dt3 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u3.ID, []int{addressPool1.ID, addressPool2.ID})
	device3 := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt3.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, device3.ID, "99.99.99.99/24")

	// device with mixed valid and invalid addresses
	u4 := test.InsertSampleUser(t, ctx, q, "resync-user4")
	dt4 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u4.ID, []int{addressPool1.ID, addressPool2.ID})
	device4 := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt4.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, device4.ID, "10.100.0.7/24")
	test.InsertDeviceAddress(t, ctx, sqlcq, device4.ID, "77.77.77.77/24")

	// multiple devices with mixed issues
	u5 := test.InsertSampleUser(t, ctx, q, "resync-user5")
	dt5 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u5.ID, []int{addressPool1.ID, addressPool2.ID})
	_ = test.InsertSampleDeviceAutoGenerated(t, ctx, manager, dt5.ID)
	device5b := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt5.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, device5b.ID, "10.100.0.6/24")
	device5c := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt5.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, device5c.ID, "88.88.88.88/24")

	// device with duplicate addresses from same pool - should keep only one per pool
	u7 := test.InsertSampleUser(t, ctx, q, "resync-user7")
	dt7 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u7.ID, []int{addressPool1.ID, addressPool2.ID})
	device7 := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt7.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, device7.ID, "10.100.0.2/24")
	test.InsertDeviceAddress(t, ctx, sqlcq, device7.ID, "10.100.0.3/24")
	test.InsertDeviceAddress(t, ctx, sqlcq, device7.ID, "192.168.100.5/24")

	// device deletion - pool exhausted
	u6 := test.InsertSampleUser(t, ctx, q, "resync-user6")
	dt6 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u6.ID, []int{addressPool1.ID, addressPool3.ID})
	deviceThatUsesPool3 := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt6.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, deviceThatUsesPool3.ID, "172.16.0.1/24")
	test.InsertDeviceAddress(t, ctx, sqlcq, deviceThatUsesPool3.ID, "10.100.0.8/24")
	deviceToBeDeleted := test.InsertSampleDeviceManual(t, ctx, sqlcq, dt6.ID)
	test.InsertDeviceAddress(t, ctx, sqlcq, deviceToBeDeleted.ID, "99.99.99.99/24")

	tests := []struct {
		name               string
		templateID         int
		expectedUpdated    int
		expectedDeleted    int
		expectedErrorCount int
		expectError        bool
		skipAddressCheck   bool
	}{
		{
			name:               "devices with correct addresses",
			templateID:         dt1.ID,
			expectedUpdated:    0,
			expectedDeleted:    0,
			expectedErrorCount: 0,
		},
		{
			name:               "device with missing address - should allocate missing address",
			templateID:         dt2.ID,
			expectedUpdated:    1,
			expectedDeleted:    0,
			expectedErrorCount: 0,
		},
		{
			name:               "device with invalid address - should remove and allocate correct address",
			templateID:         dt3.ID,
			expectedUpdated:    1,
			expectedDeleted:    0,
			expectedErrorCount: 0,
		},
		{
			name:               "device with mixed valid and invalid addresses",
			templateID:         dt4.ID,
			expectedUpdated:    1,
			expectedDeleted:    0,
			expectedErrorCount: 0,
		},
		{
			name:               "multiple devices with mixed issues",
			templateID:         dt5.ID,
			expectedUpdated:    2,
			expectedDeleted:    0,
			expectedErrorCount: 0,
		},
		{
			name:               "device deleted - no available addresses in pool",
			templateID:         dt6.ID,
			expectedUpdated:    0,
			expectedDeleted:    1,
			expectedErrorCount: 0,
			skipAddressCheck:   true,
		},
		{
			name:               "device with duplicate addresses from same pool - should keep only one per pool",
			templateID:         dt7.ID,
			expectedUpdated:    1,
			expectedDeleted:    0,
			expectedErrorCount: 0,
		},
		{
			name:        "template not found",
			templateID:  99999,
			expectError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			response, err := manager.ResyncDevices(ctx, tt.templateID)

			if tt.expectError {
				require.Error(t, err)
				require.Equal(t, user.ErrNotFound, err)
				return
			}

			require.NoError(t, err)
			require.NotNil(t, response)
			require.Equal(t, tt.expectedUpdated, response.DevicesUpdated)
			require.Equal(t, tt.expectedDeleted, response.DevicesDeleted)
			require.Len(t, response.Errors, tt.expectedErrorCount)

			if tt.skipAddressCheck {
				return
			}

			devices, err := sqlcq.GetDevicesByTemplateID(ctx, tt.templateID)
			require.NoError(t, err)

			for _, device := range devices {
				addrs, err := sqlcq.GetDeviceWireGuardIfaceAddrs(ctx, device.ID)
				require.NoError(t, err)
				require.Len(t, addrs, 2)

				// verify addresses are from the correct pools
				hasPool1 := false
				hasPool2 := false
				for _, addr := range addrs {
					if pool1Range.Contains(addr) {
						hasPool1 = true
					}
					if pool2Range.Contains(addr) {
						hasPool2 = true
					}
				}
				require.True(t, hasPool1)
				require.True(t, hasPool2)
			}
		})
	}
}

func TestIntegrationAssignDeviceSlotCase1ReuseExistingDevice(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u1 := test.InsertSampleUser(t, ctx, q, "user1")
	addressPool1 := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool1"))
	deviceTemplate1 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u1.ID, []int{addressPool1.ID})
	deviceWithoutSession := test.InsertSampleDeviceManual(t, ctx, sqlcq, deviceTemplate1.ID)

	u2 := test.InsertSampleUser(t, ctx, q, "user2")
	addressPool2 := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool2"))
	deviceTemplate2 := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u2.ID, []int{addressPool2.ID})
	oldTime := time.Now().Add(-1 * time.Hour)
	deviceWithSession, _ := test.InsertSampleDeviceWithSession(t, ctx, sqlcq, deviceTemplate2.ID, &oldTime)

	session1, err := session.GenerateSessionID()
	require.NoError(t, err)
	session2, err := session.GenerateSessionID()
	require.NoError(t, err)

	tests := []struct {
		name            string
		userID          int
		device          *sqlc.Device
		expectedSession string
	}{
		{
			name:            "update session for device without existing session",
			userID:          u1.ID,
			device:          deviceWithoutSession,
			expectedSession: session1,
		},
		{
			name:            "update session for device with existing session",
			userID:          u2.ID,
			device:          deviceWithSession,
			expectedSession: session2,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assignedExtID, err := manager.AssignDeviceSlot(ctx, tt.userID, tt.expectedSession, tt.device.ExternalDeviceID, "")
			require.NoError(t, err)
			require.Equal(t, tt.device.ExternalDeviceID, assignedExtID)

			updatedDevice, err := sqlcq.GetSessionByDeviceID(ctx, tt.device.ID)
			require.NoError(t, err)
			require.Equal(t, tt.expectedSession, updatedDevice.SessionID)
			require.True(t, updatedDevice.LastTimeConnected.Valid)

			now := time.Now().UTC()
			before := now.Add(-5 * time.Second)
			after := now.Add(1 * time.Second)
			test.RequireTimeBetween(t, updatedDevice.LastTimeConnected.Time, before, after)
		})
	}
}

func TestIntegrationAssignDeviceSlotCase2UseFreeSlot(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "user")
	addressPool := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool"))
	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool.ID})

	initialDeviceInfo := "OS:iOS;OSV:16.0;OSB:20A362;APPV:3.0.0;DVCE:iPhone 14"
	deviceFreeSlot, err := manager.CreateDeviceWithAutogenData(ctx, deviceTemplate.ID, "", initialDeviceInfo)
	require.NoError(t, err)

	externalDeviceID, err := nanoid.Generate()
	require.NoError(t, err)
	expectedSession, err := session.GenerateSessionID()
	require.NoError(t, err)
	expectedDeviceInfo := "OS:iOS;OSV:17.2;OSB:21C66;APPV:3.5.1;DVCE:iPhone 15 Pro"

	deviceCountBefore := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")

	assignedExtID, err := manager.AssignDeviceSlot(ctx, u.ID, expectedSession, externalDeviceID, expectedDeviceInfo)
	require.NoError(t, err)
	require.Equal(t, externalDeviceID, assignedExtID)

	deviceCountAfter := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")
	require.Equal(t, deviceCountBefore, deviceCountAfter)

	updatedDevice, err := sqlcq.GetDeviceByID(ctx, deviceFreeSlot.ID)
	require.NoError(t, err)
	require.Equal(t, externalDeviceID, updatedDevice.ExternalDeviceID)
	require.Equal(t, expectedSession, updatedDevice.SessionID)
	require.Equal(t, expectedDeviceInfo, *updatedDevice.DeviceInformation)
	require.True(t, updatedDevice.LastTimeConnected.Valid)

	now := time.Now().UTC()
	before := now.Add(-5 * time.Second)
	after := now.Add(1 * time.Second)
	test.RequireTimeBetween(t, updatedDevice.LastTimeConnected.Time, before, after)
}

func TestIntegrationAssignDeviceSlotCase3CreateNewDevice(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "user")
	addressPool := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool"))
	_ = test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool.ID})

	externalDeviceID, err := nanoid.Generate()
	require.NoError(t, err)
	expectedSession, err := session.GenerateSessionID()
	require.NoError(t, err)

	deviceCountBefore := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")

	assignedExtID, err := manager.AssignDeviceSlot(ctx, u.ID, expectedSession, externalDeviceID, "")
	require.NoError(t, err)
	require.Equal(t, externalDeviceID, assignedExtID)

	deviceCountAfter := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")
	require.Equal(t, deviceCountBefore+1, deviceCountAfter)

	newDevice, err := sqlcq.GetDeviceByExternalIDAndUserID(ctx, sqlc.GetDeviceByExternalIDAndUserIDParams{
		ExternalDeviceID: externalDeviceID,
		UserID:           u.ID,
	})
	require.NoError(t, err)
	require.Equal(t, expectedSession, newDevice.SessionID)
	require.True(t, newDevice.LastTimeConnected.Valid)
	require.NotEmpty(t, test.OpenString(newDevice.PrivateKeyEncrypted))
	require.NotEmpty(t, newDevice.PublicKey)

	now := time.Now().UTC()
	before := now.Add(-5 * time.Second)
	after := now.Add(1 * time.Second)
	test.RequireTimeBetween(t, newDevice.LastTimeConnected.Time, before, after)
}

func TestIntegrationAssignDeviceSlotCase4aOverwriteInactive(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "user")
	addressPool := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool"))
	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool.ID})

	// create DPU limit - 1 devices with external_device_ids
	for i := 0; i < manager.Feats.GetDPULimit()-1; i++ {
		deviceInfo := "OS:iOS;OSV:16.0;OSB:20A362;APPV:3.0.0;DVCE:iPhone 14"
		device, err := manager.CreateDeviceWithAutogenData(ctx, deviceTemplate.ID, "", deviceInfo)
		require.NoError(t, err)
		externalID, err := nanoid.Generate()
		require.NoError(t, err)
		sessionID, err := session.GenerateSessionID()
		require.NoError(t, err)

		_, err = sqlcq.UpdateDeviceFromConfiguration(ctx, sqlc.UpdateDeviceFromConfigurationParams{
			ID:                device.ID,
			ExternalDeviceID:  externalID,
			SessionID:         sessionID,
			LastTimeConnected: db.NewPgTimestamp(time.Now().Add(-time.Duration(i+1) * time.Hour)),
		})
		require.NoError(t, err)
	}

	// device with null session (inactive)
	inactiveDeviceInfo := "OS:Android;OSV:13;OSB:TQ3A.230805.001;APPV:2.5.0;DVCE:Pixel 7"
	inactiveDevice, err := manager.CreateDeviceWithAutogenData(ctx, deviceTemplate.ID, "", inactiveDeviceInfo)
	require.NoError(t, err)
	originalExternalDevID := inactiveDevice.ExternalDeviceID

	externalDeviceID, err := nanoid.Generate()
	require.NoError(t, err)
	expectedSession, err := session.GenerateSessionID()
	require.NoError(t, err)
	expectedDeviceInfo := "OS:iOS;OSV:17.2;OSB:21C66;APPV:3.5.1;DVCE:iPhone 15 Pro"

	deviceCountBefore := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")
	require.Equal(t, manager.Feats.GetDPULimit(), deviceCountBefore)

	assignedExtID, err := manager.AssignDeviceSlot(ctx, u.ID, expectedSession, externalDeviceID, expectedDeviceInfo)
	require.NoError(t, err)
	require.Equal(t, externalDeviceID, assignedExtID)

	deviceCountAfter := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")
	require.Equal(t, deviceCountBefore, deviceCountAfter)

	overwrittenDevice, err := sqlcq.GetDeviceByExternalIDAndUserID(ctx, sqlc.GetDeviceByExternalIDAndUserIDParams{
		ExternalDeviceID: externalDeviceID,
		UserID:           u.ID,
	})
	require.NoError(t, err)
	require.Equal(t, inactiveDevice.ID, overwrittenDevice.ID)
	require.Equal(t, expectedSession, overwrittenDevice.SessionID)
	require.Equal(t, expectedDeviceInfo, *overwrittenDevice.DeviceInformation)
	require.True(t, overwrittenDevice.LastTimeConnected.Valid)
	require.NotEqual(t, originalExternalDevID, overwrittenDevice.ExternalDeviceID)

	now := time.Now().UTC()
	before := now.Add(-5 * time.Second)
	after := now.Add(1 * time.Second)
	test.RequireTimeBetween(t, overwrittenDevice.LastTimeConnected.Time, before, after)
}

func TestIntegrationAssignDeviceSlotCase4bKickOldest(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "user")
	addressPool := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool"))
	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool.ID})

	var oldestDeviceID int
	deviceInfo := "OS:iOS;OSV:16.0;OSB:20A362;APPV:3.0.0;DVCE:iPhone 14"
	for i := 0; i < manager.Feats.GetDPULimit(); i++ {
		activeTime := time.Now().Add(-time.Duration(i+1) * time.Hour)
		device := test.InsertSampleDeviceManual(t, ctx, sqlcq, deviceTemplate.ID)

		externalID, err := nanoid.Generate()
		require.NoError(t, err)
		sessionID, err := session.GenerateSessionID()
		require.NoError(t, err)

		updatedDevice, err := sqlcq.UpdateDeviceFromConfiguration(ctx, sqlc.UpdateDeviceFromConfigurationParams{
			ID:                device.ID,
			ExternalDeviceID:  externalID,
			SessionID:         sessionID,
			LastTimeConnected: db.NewPgTimestamp(activeTime),
			DeviceInformation: db.StringToPtr(deviceInfo),
		})
		require.NoError(t, err)

		if i == manager.Feats.GetDPULimit()-1 {
			oldestDeviceID = updatedDevice.ID
		}
	}
	require.NotZero(t, oldestDeviceID)

	externalDeviceID, err := nanoid.Generate()
	require.NoError(t, err)
	expectedSession, err := session.GenerateSessionID()
	require.NoError(t, err)
	expectedDeviceInfo := "OS:iOS;OSV:17.2;OSB:21C66;APPV:3.5.1;DVCE:iPhone 15 Pro"

	deviceCountBefore := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")
	require.Equal(t, manager.Feats.GetDPULimit(), deviceCountBefore)

	assignedExtID, err := manager.AssignDeviceSlot(ctx, u.ID, expectedSession, externalDeviceID, expectedDeviceInfo)
	require.NoError(t, err)
	require.Equal(t, externalDeviceID, assignedExtID)

	deviceCountAfter := test.CountTableRows(t, q.GetDbConnection(ctx), "devices")
	require.Equal(t, deviceCountBefore, deviceCountAfter)

	overwrittenDevice, err := sqlcq.GetDeviceByExternalIDAndUserID(ctx, sqlc.GetDeviceByExternalIDAndUserIDParams{
		ExternalDeviceID: externalDeviceID,
		UserID:           u.ID,
	})
	require.NoError(t, err)
	require.Equal(t, oldestDeviceID, overwrittenDevice.ID)
	require.Equal(t, expectedSession, overwrittenDevice.SessionID)
	require.Equal(t, expectedDeviceInfo, *overwrittenDevice.DeviceInformation)
	require.True(t, overwrittenDevice.LastTimeConnected.Valid)

	now := time.Now().UTC()
	before := now.Add(-5 * time.Second)
	after := now.Add(1 * time.Second)
	test.RequireTimeBetween(t, overwrittenDevice.LastTimeConnected.Time, before, after)
}

func TestIntegrationAssignDeviceSlotValidation(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "user")
	addressPool := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool"))
	_ = test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool.ID})

	uNoTemplate := test.InsertSampleUser(t, ctx, q, "userWithoutTemplate")

	sessionID, err := session.GenerateSessionID()
	require.NoError(t, err)
	tests := []struct {
		name             string
		userID           int
		session          string
		externalDeviceID string
		expectedErrType  error
	}{
		{
			name:             "error when user ID is empty",
			userID:           0,
			session:          sessionID,
			externalDeviceID: "device-123",
			expectedErrType:  user.ErrInvalidData,
		},
		{
			name:             "error when session is empty",
			userID:           u.ID,
			session:          "",
			externalDeviceID: "valid-device-id-12345",
			expectedErrType:  user.ErrInvalidData,
		},
		{
			name:             "error when user has no device template",
			userID:           uNoTemplate.ID,
			session:          sessionID,
			externalDeviceID: "valid-device-id-12345",
			expectedErrType:  user.ErrNotFound,
		},
		{
			name:             "error when external device ID is invalid",
			userID:           u.ID,
			session:          sessionID,
			externalDeviceID: "invalid-id-with-spaces and special chars!",
			expectedErrType:  user.ErrInvalidData,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := manager.AssignDeviceSlot(ctx, tt.userID, tt.session, tt.externalDeviceID, "")
			require.Error(t, err)
			require.ErrorIs(t, err, tt.expectedErrType)
		})
	}
}

func TestIntegrationAssignDeviceSlotBackwardCompatibility(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "user")
	addressPool := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool"))
	_ = test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool.ID})

	s1, err := session.GenerateSessionID()
	require.NoError(t, err)

	// crete new device slot
	assignedExtID, err := manager.AssignDeviceSlot(ctx, u.ID, s1, "", "")
	require.NoError(t, err)
	require.NotEmpty(t, assignedExtID)
	require.Equal(t, assignedExtID, user.DummyExternalDeviceID)

	d1, err := manager.GetDeviceByExternalIDAndUserID(ctx, assignedExtID, u.ID)
	require.NoError(t, err)
	require.NotEmpty(t, d1.ID)
	require.Equal(t, assignedExtID, d1.ExternalDeviceID)
	require.Equal(t, s1, d1.SessionID)

	s2, err := session.GenerateSessionID()
	require.NoError(t, err)

	conn := q.GetDbConnection(ctx)
	countBefore := test.CountTableRows(t, conn, "devices")
	require.Equal(t, 1, countBefore)

	// assigning existing device slot
	assignedExtID, err = manager.AssignDeviceSlot(ctx, u.ID, s2, "", "")
	require.NoError(t, err)
	require.NotEmpty(t, assignedExtID)
	require.Equal(t, assignedExtID, user.DummyExternalDeviceID)

	d2, err := manager.GetDeviceByExternalIDAndUserID(ctx, assignedExtID, u.ID)
	require.NoError(t, err)
	require.NotEmpty(t, d2.ID)
	require.Equal(t, d2.ID, d1.ID)
	require.Equal(t, d2.ExternalDeviceID, assignedExtID)
	require.Equal(t, s2, d2.SessionID)

	countAfter := test.CountTableRows(t, conn, "devices")
	require.Equal(t, countBefore, countAfter)
}

func TestIntegrationParseDeviceInformation(t *testing.T) {
	ctx := context.Background()
	test.SkipOrSetupIntegrationTest(t, ctx, q)

	u := test.InsertSampleUser(t, ctx, q, "test-user")
	addressPool := test.InsertSampleAddressPool(t, ctx, sqlcq, test.NewSampleInsertAddressPoolParams("pool"))
	deviceTemplate := test.InsertSampleDeviceTemplate(t, ctx, sqlcq, u.ID, []int{addressPool.ID})

	tests := []struct {
		name              string
		deviceTemplateID  int
		deviceInformation string
		expectedParsed    string
	}{
		{
			name:              "full device information with all fields",
			deviceTemplateID:  deviceTemplate.ID,
			deviceInformation: "OS:iOS;OSV:17.2;OSB:21C66;APPV:3.5.1;DVCE:iPhone 15 Pro",
			expectedParsed:    "OS:          iOS\nOS Version:  17.2\nOS Build:    21C66\nAPP Version: 3.5.1\nDevice:      iPhone 15 Pro",
		},
		{
			name:              "device information without optional OSB field",
			deviceTemplateID:  deviceTemplate.ID,
			deviceInformation: "OS:iOS;OSV:17.2;APPV:3.5.1;DVCE:iPhone 15 Pro",
			expectedParsed:    "OS:          iOS\nOS Version:  17.2\nAPP Version: 3.5.1\nDevice:      iPhone 15 Pro",
		},
		{
			name:              "device information without optional DVCE field",
			deviceTemplateID:  deviceTemplate.ID,
			deviceInformation: "OS:Android;OSV:14;OSB:UP1A.231005.007;APPV:2.1.0",
			expectedParsed:    "OS:          Android\nOS Version:  14\nOS Build:    UP1A.231005.007\nAPP Version: 2.1.0",
		},
		{
			name:              "device information without both optional fields",
			deviceTemplateID:  deviceTemplate.ID,
			deviceInformation: "OS:Android;OSV:14;APPV:2.1.0",
			expectedParsed:    "OS:          Android\nOS Version:  14\nAPP Version: 2.1.0",
		},
		{
			name:              "empty string",
			deviceTemplateID:  deviceTemplate.ID,
			deviceInformation: "",
			expectedParsed:    "",
		},
		{
			name:              "fields in different order",
			deviceTemplateID:  deviceTemplate.ID,
			deviceInformation: "DVCE:iPad Pro;APPV:3.0.0;OSV:16.5;OSB:20F66;OS:iOS",
			expectedParsed:    "OS:          iOS\nOS Version:  16.5\nOS Build:    20F66\nAPP Version: 3.0.0\nDevice:      iPad Pro",
		},
		{
			name:              "device with spaces and special characters",
			deviceTemplateID:  deviceTemplate.ID,
			deviceInformation: "OS:iOS;OSV:17.2;DVCE:iPhone 15 Pro Max (256GB);APPV:3.5.1-beta",
			expectedParsed:    "OS:          iOS\nOS Version:  17.2\nAPP Version: 3.5.1-beta\nDevice:      iPhone 15 Pro Max (256GB)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			device, err := manager.CreateDeviceWithAutogenData(ctx, tt.deviceTemplateID, "test-device-123456", tt.deviceInformation)
			require.NoError(t, err)
			require.NotNil(t, device)
			require.Equal(t, tt.expectedParsed, device.DeviceInformation)

			devices, err := manager.GetDevicesByTemplateID(ctx, tt.deviceTemplateID)
			require.NoError(t, err)
			require.NotEmpty(t, devices)

			var foundDevice *api.Device
			for _, d := range devices {
				if d.ID == device.ID {
					foundDevice = d
					break
				}
			}
			require.NotNil(t, foundDevice)
			require.Equal(t, tt.expectedParsed, foundDevice.DeviceInformation)

			// clean up(to not hit device per user limit)
			err = manager.DeleteDevice(ctx, device.ID)
			require.NoError(t, err)
		})
	}
}
