// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/entguard/entguard/pkg/crypto/aesgcm"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthServiceType string

const (
	AuthServiceTypeIntr AuthServiceType = "intr"
	AuthServiceTypeLdap AuthServiceType = "ldap"
)

func (e *AuthServiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthServiceType(s)
	case string:
		*e = AuthServiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthServiceType: %T", src)
	}
	return nil
}

type NullAuthServiceType struct {
	AuthServiceType AuthServiceType
	Valid           bool // Valid is true if AuthServiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthServiceType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthServiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthServiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthServiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthServiceType), nil
}

type MfaAuthType string

const (
	MfaAuthTypeNone MfaAuthType = "none"
	MfaAuthTypeTotp MfaAuthType = "totp"
	MfaAuthTypeCert MfaAuthType = "cert"
)

func (e *MfaAuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MfaAuthType(s)
	case string:
		*e = MfaAuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for MfaAuthType: %T", src)
	}
	return nil
}

type NullMfaAuthType struct {
	MfaAuthType MfaAuthType
	Valid       bool // Valid is true if MfaAuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMfaAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.MfaAuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MfaAuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMfaAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MfaAuthType), nil
}

type MfaCertType string

const (
	MfaCertTypeCa  MfaCertType = "ca"
	MfaCertTypeCrl MfaCertType = "crl"
)

func (e *MfaCertType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MfaCertType(s)
	case string:
		*e = MfaCertType(s)
	default:
		return fmt.Errorf("unsupported scan type for MfaCertType: %T", src)
	}
	return nil
}

type NullMfaCertType struct {
	MfaCertType MfaCertType
	Valid       bool // Valid is true if MfaCertType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMfaCertType) Scan(value interface{}) error {
	if value == nil {
		ns.MfaCertType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MfaCertType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMfaCertType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MfaCertType), nil
}

type AddressPool struct {
	ID          int
	Name        string
	Description string
	StartAddr   netip.Addr
	EndAddr     netip.Addr
	NetMask     int
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Adjacency struct {
	ID                    int
	ServerID              int
	DeviceID              int
	ServerSideAllowedIps  []netip.Prefix
	ClientSideAllowedIps  []netip.Prefix
	PresharedKey          *string
	PresharedKeyEncrypted aesgcm.Ciphertext
}

type AdjacencyTemplate struct {
	ID                   int
	ServerID             int
	UserID               int
	ClientSideAllowedIps []netip.Prefix
	UsePresharedKey      bool
}

type Device struct {
	ID                  int
	Description         string
	DeviceTemplateID    int
	PrivateKey          *string
	PublicKey           string
	ExternalDeviceID    string
	SessionID           string
	LastTimeConnected   pgtype.Timestamp
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeviceInformation   *string
	PrivateKeyEncrypted aesgcm.Ciphertext
}

type DeviceTemplate struct {
	ID            int
	UserID        int
	InterfaceName string
	ListenPort    *int
	Mtu           *int
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type DeviceTemplateAddressPool struct {
	ID               int
	DeviceTemplateID int
	AddressPoolID    int
}

type DeviceTemplateWgIfaceDnss struct {
	ID               int
	DeviceTemplateID int
	Dns              string
}

type DeviceWgIfaceAddress struct {
	ID       int
	DeviceID int
	Addr     netip.Prefix
}

type Ldap struct {
	ID                string
	Priority          int
	Host              string
	Port              int
	BaseDn            string
	BindDn            string
	BindPw            *string
	UserListFilter    string
	UsernameAttribute string
	UidAttribute      string
	UseTls            bool
	Fqdn              string
	CaCert            []byte
	TemplateID        *int
	BindPwEncrypted   aesgcm.Ciphertext
}

type LdapTemplate struct {
	ID            int
	Name          string
	Filter        *string
	InterfaceName string
	IsAdmin       bool
	MfaAuth       MfaAuthType
	ListenPort    *string
	Mtu           *string
	Dns           []string
}

type LdapTemplateAddressPool struct {
	ID             int
	LdapTemplateID int
	AddressPoolID  int
}

type LdapTemplateServer struct {
	ID              int
	LdapTemplateID  int
	ServerID        *int
	AllowedIps      []netip.Prefix
	UsePresharedKey bool
}

type MfaCert struct {
	ID       int
	Cert     []byte
	CertType MfaCertType
}

type RootCa struct {
	ID           int
	Cert         []byte
	Key          []byte
	KeyEncrypted aesgcm.Ciphertext
}

type Server struct {
	ID                 int
	Name               string
	Endpoint           netip.Addr
	Description        string
	RunningReplicas    int16
	HealthcheckAddress *netip.Addr
}

type ServerWgConfig struct {
	ID                  int
	ServerID            int
	InterfaceName       string
	PrivateKey          *string
	PublicKey           string
	ListenPort          *int
	Mtu                 *int
	PersistentKeepalive *int
	PrivateKeyEncrypted aesgcm.Ciphertext
}

type ServerWgIfaceAddress struct {
	ID             int
	ServerConfigID int
	Addr           netip.Prefix
}

type ServerWgIfaceDnss struct {
	ID             int
	ServerConfigID int
	Dns            string
}

type Tag struct {
	ID       int
	ServerID *int
	Tag      string
	Created  pgtype.Timestamp
}

type Totp struct {
	ID           int
	UserID       *int
	Key          *string
	KeyEncrypted aesgcm.Ciphertext
}

type User struct {
	ID          int
	Username    string
	Password    string
	IsAdmin     bool
	AuthService AuthServiceType
	MfaAuth     MfaAuthType
	Ntf         string
	UpdatedAt   pgtype.Timestamp
}

type UsersToLdap struct {
	ID        int
	UserID    *int
	LdapID    pgtype.UUID
	UserUid   string
	UserDn    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
