// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"net/netip"

	"github.com/entguard/entguard/pkg/crypto/aesgcm"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjacencyExists = `-- name: AdjacencyExists :one
SELECT EXISTS(
    SELECT 1 FROM adjacencies
    WHERE server_id=$1
    AND device_id=$2
)
`

type AdjacencyExistsParams struct {
	ServerID int
	DeviceID int
}

func (q *Queries) AdjacencyExists(ctx context.Context, arg AdjacencyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, adjacencyExists, arg.ServerID, arg.DeviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const adjacencyTemplateExists = `-- name: AdjacencyTemplateExists :one
SELECT EXISTS(
    SELECT 1 FROM adjacency_templates
    WHERE server_id=$1
    AND user_id=$2
)
`

type AdjacencyTemplateExistsParams struct {
	ServerID int
	UserID   int
}

func (q *Queries) AdjacencyTemplateExists(ctx context.Context, arg AdjacencyTemplateExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, adjacencyTemplateExists, arg.ServerID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const adjacencyTemplateExistsByID = `-- name: AdjacencyTemplateExistsByID :one
SELECT EXISTS(
    SELECT 1 FROM adjacency_templates
    WHERE id=$1
)
`

func (q *Queries) AdjacencyTemplateExistsByID(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRow(ctx, adjacencyTemplateExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decreaseServerReplicas = `-- name: DecreaseServerReplicas :one
UPDATE servers 
SET running_replicas = running_replicas - 1
WHERE running_replicas > 0 
AND id=$1
RETURNING id, name, endpoint, description, running_replicas, healthcheck_address
`

func (q *Queries) DecreaseServerReplicas(ctx context.Context, id int) (Server, error) {
	row := q.db.QueryRow(ctx, decreaseServerReplicas, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Description,
		&i.RunningReplicas,
		&i.HealthcheckAddress,
	)
	return i, err
}

const deleteAddressPool = `-- name: DeleteAddressPool :one
DELETE FROM address_pools
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteAddressPool(ctx context.Context, id int) (int, error) {
	row := q.db.QueryRow(ctx, deleteAddressPool, id)
	err := row.Scan(&id)
	return id, err
}

const deleteAdjacency = `-- name: DeleteAdjacency :exec
DELETE FROM adjacencies
WHERE id=$1
`

func (q *Queries) DeleteAdjacency(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteAdjacency, id)
	return err
}

const deleteAdjacencyTemplate = `-- name: DeleteAdjacencyTemplate :exec
DELETE FROM adjacency_templates
WHERE id=$1
`

func (q *Queries) DeleteAdjacencyTemplate(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteAdjacencyTemplate, id)
	return err
}

const deleteCA = `-- name: DeleteCA :exec
TRUNCATE TABLE root_ca
`

func (q *Queries) DeleteCA(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteCA)
	return err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id=$1
`

func (q *Queries) DeleteDevice(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeviceTemplate = `-- name: DeleteDeviceTemplate :exec
DELETE FROM device_templates
WHERE id=$1
`

func (q *Queries) DeleteDeviceTemplate(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteDeviceTemplate, id)
	return err
}

const deleteDeviceTemplateAddressPools = `-- name: DeleteDeviceTemplateAddressPools :exec
DELETE FROM device_template_address_pools
WHERE device_template_id=$1
`

func (q *Queries) DeleteDeviceTemplateAddressPools(ctx context.Context, deviceTemplateID int) error {
	_, err := q.db.Exec(ctx, deleteDeviceTemplateAddressPools, deviceTemplateID)
	return err
}

const deleteDeviceTemplateWireGuardDNS = `-- name: DeleteDeviceTemplateWireGuardDNS :exec
DELETE FROM device_template_wg_iface_dnss
WHERE device_template_id=$1
`

func (q *Queries) DeleteDeviceTemplateWireGuardDNS(ctx context.Context, deviceTemplateID int) error {
	_, err := q.db.Exec(ctx, deleteDeviceTemplateWireGuardDNS, deviceTemplateID)
	return err
}

const deleteDeviceWireGuardIfaceAddrs = `-- name: DeleteDeviceWireGuardIfaceAddrs :exec
DELETE FROM device_wg_iface_addresses
WHERE device_id=$1
`

func (q *Queries) DeleteDeviceWireGuardIfaceAddrs(ctx context.Context, deviceID int) error {
	_, err := q.db.Exec(ctx, deleteDeviceWireGuardIfaceAddrs, deviceID)
	return err
}

const deleteLdapConfig = `-- name: DeleteLdapConfig :exec
DELETE FROM ldaps WHERE id=$1
`

func (q *Queries) DeleteLdapConfig(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLdapConfig, id)
	return err
}

const deleteLdapRelations = `-- name: DeleteLdapRelations :exec
DELETE FROM users_to_ldaps
WHERE updated_at < $1
`

func (q *Queries) DeleteLdapRelations(ctx context.Context, updatedAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteLdapRelations, updatedAt)
	return err
}

const deleteLdapTemplate = `-- name: DeleteLdapTemplate :exec
DELETE FROM ldap_templates WHERE id=$1
`

func (q *Queries) DeleteLdapTemplate(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteLdapTemplate, id)
	return err
}

const deleteLdapTemplateAddressPools = `-- name: DeleteLdapTemplateAddressPools :exec
DELETE FROM ldap_template_address_pools WHERE ldap_template_id = $1
`

func (q *Queries) DeleteLdapTemplateAddressPools(ctx context.Context, ldapTemplateID int) error {
	_, err := q.db.Exec(ctx, deleteLdapTemplateAddressPools, ldapTemplateID)
	return err
}

const deleteLdapTemplateServer = `-- name: DeleteLdapTemplateServer :exec
DELETE FROM ldap_template_servers
WHERE ldap_template_id = $1
AND server_id = $2
`

type DeleteLdapTemplateServerParams struct {
	LdapTemplateID int
	ServerID       *int
}

func (q *Queries) DeleteLdapTemplateServer(ctx context.Context, arg DeleteLdapTemplateServerParams) error {
	_, err := q.db.Exec(ctx, deleteLdapTemplateServer, arg.LdapTemplateID, arg.ServerID)
	return err
}

const deleteMFACert = `-- name: DeleteMFACert :exec
DELETE FROM mfa_certs WHERE id=$1
`

func (q *Queries) DeleteMFACert(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteMFACert, id)
	return err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id=$1
`

func (q *Queries) DeleteServer(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const deleteServerWireGuardConfig = `-- name: DeleteServerWireGuardConfig :exec
DELETE FROM server_wg_configs
WHERE server_id=$1
`

func (q *Queries) DeleteServerWireGuardConfig(ctx context.Context, serverID int) error {
	_, err := q.db.Exec(ctx, deleteServerWireGuardConfig, serverID)
	return err
}

const deleteServerWireGuardDNS = `-- name: DeleteServerWireGuardDNS :exec
DELETE FROM server_wg_iface_dnss
WHERE server_config_id=$1
`

func (q *Queries) DeleteServerWireGuardDNS(ctx context.Context, serverConfigID int) error {
	_, err := q.db.Exec(ctx, deleteServerWireGuardDNS, serverConfigID)
	return err
}

const deleteServerWireGuardIfaceAddrs = `-- name: DeleteServerWireGuardIfaceAddrs :exec
DELETE FROM server_wg_iface_addresses
WHERE server_config_id=$1
`

func (q *Queries) DeleteServerWireGuardIfaceAddrs(ctx context.Context, serverConfigID int) error {
	_, err := q.db.Exec(ctx, deleteServerWireGuardIfaceAddrs, serverConfigID)
	return err
}

const deleteTags = `-- name: DeleteTags :exec
TRUNCATE TABLE tags
`

func (q *Queries) DeleteTags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteTags)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deviceTemplateExists = `-- name: DeviceTemplateExists :one
SELECT 1 FROM device_templates 
WHERE id=$1
`

func (q *Queries) DeviceTemplateExists(ctx context.Context, id int) (int, error) {
	row := q.db.QueryRow(ctx, deviceTemplateExists, id)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getAddressPoolByID = `-- name: GetAddressPoolByID :one
SELECT id, name, description, start_addr, end_addr, net_mask, created_at, updated_at FROM address_pools
WHERE id = $1
`

func (q *Queries) GetAddressPoolByID(ctx context.Context, id int) (AddressPool, error) {
	row := q.db.QueryRow(ctx, getAddressPoolByID, id)
	var i AddressPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartAddr,
		&i.EndAddr,
		&i.NetMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressPoolByName = `-- name: GetAddressPoolByName :one
SELECT id, name, description, start_addr, end_addr, net_mask, created_at, updated_at FROM address_pools
WHERE name = $1
`

func (q *Queries) GetAddressPoolByName(ctx context.Context, name string) (AddressPool, error) {
	row := q.db.QueryRow(ctx, getAddressPoolByName, name)
	var i AddressPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartAddr,
		&i.EndAddr,
		&i.NetMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdjacenciesByServerID = `-- name: GetAdjacenciesByServerID :many
SELECT id, server_id, device_id, server_side_allowed_ips, client_side_allowed_ips, preshared_key, preshared_key_encrypted FROM adjacencies
WHERE server_id=$1
`

func (q *Queries) GetAdjacenciesByServerID(ctx context.Context, serverID int) ([]Adjacency, error) {
	rows, err := q.db.Query(ctx, getAdjacenciesByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Adjacency
	for rows.Next() {
		var i Adjacency
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.DeviceID,
			&i.ServerSideAllowedIps,
			&i.ClientSideAllowedIps,
			&i.PresharedKey,
			&i.PresharedKeyEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdjacency = `-- name: GetAdjacency :one
SELECT id, server_id, device_id, server_side_allowed_ips, client_side_allowed_ips, preshared_key, preshared_key_encrypted FROM adjacencies WHERE id=$1
`

func (q *Queries) GetAdjacency(ctx context.Context, id int) (Adjacency, error) {
	row := q.db.QueryRow(ctx, getAdjacency, id)
	var i Adjacency
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.DeviceID,
		&i.ServerSideAllowedIps,
		&i.ClientSideAllowedIps,
		&i.PresharedKey,
		&i.PresharedKeyEncrypted,
	)
	return i, err
}

const getAdjacencyTemplateByID = `-- name: GetAdjacencyTemplateByID :one
SELECT id, server_id, user_id, client_side_allowed_ips, use_preshared_key FROM adjacency_templates
WHERE id=$1
`

func (q *Queries) GetAdjacencyTemplateByID(ctx context.Context, id int) (AdjacencyTemplate, error) {
	row := q.db.QueryRow(ctx, getAdjacencyTemplateByID, id)
	var i AdjacencyTemplate
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.ClientSideAllowedIps,
		&i.UsePresharedKey,
	)
	return i, err
}

const getAdjacencyTemplatesByServerID = `-- name: GetAdjacencyTemplatesByServerID :many
SELECT id, server_id, user_id, client_side_allowed_ips, use_preshared_key FROM adjacency_templates
WHERE server_id=$1
`

func (q *Queries) GetAdjacencyTemplatesByServerID(ctx context.Context, serverID int) ([]AdjacencyTemplate, error) {
	rows, err := q.db.Query(ctx, getAdjacencyTemplatesByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdjacencyTemplate
	for rows.Next() {
		var i AdjacencyTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.ClientSideAllowedIps,
			&i.UsePresharedKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAddressPools = `-- name: GetAllAddressPools :many
SELECT id, name, description, start_addr, end_addr, net_mask, created_at, updated_at FROM address_pools
ORDER BY start_addr
`

func (q *Queries) GetAllAddressPools(ctx context.Context) ([]AddressPool, error) {
	rows, err := q.db.Query(ctx, getAllAddressPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddressPool
	for rows.Next() {
		var i AddressPool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StartAddr,
			&i.EndAddr,
			&i.NetMask,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDevices = `-- name: GetAllDevices :many
SELECT id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted FROM devices ORDER BY id
`

func (q *Queries) GetAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, getAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DeviceTemplateID,
			&i.PrivateKey,
			&i.PublicKey,
			&i.ExternalDeviceID,
			&i.SessionID,
			&i.LastTimeConnected,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceInformation,
			&i.PrivateKeyEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLdapConfigs = `-- name: GetAllLdapConfigs :many
SELECT
    id, priority, host, port, base_dn, bind_dn, bind_pw_encrypted,
    user_list_filter, username_attribute, uid_attribute,
    use_tls, fqdn, ca_cert, COALESCE(template_id, 0)
FROM ldaps
ORDER BY priority
`

type GetAllLdapConfigsRow struct {
	ID                string
	Priority          int
	Host              string
	Port              int
	BaseDn            string
	BindDn            string
	BindPwEncrypted   aesgcm.Ciphertext
	UserListFilter    string
	UsernameAttribute string
	UidAttribute      string
	UseTls            bool
	Fqdn              string
	CaCert            []byte
	TemplateID        int
}

func (q *Queries) GetAllLdapConfigs(ctx context.Context) ([]GetAllLdapConfigsRow, error) {
	rows, err := q.db.Query(ctx, getAllLdapConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLdapConfigsRow
	for rows.Next() {
		var i GetAllLdapConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.Host,
			&i.Port,
			&i.BaseDn,
			&i.BindDn,
			&i.BindPwEncrypted,
			&i.UserListFilter,
			&i.UsernameAttribute,
			&i.UidAttribute,
			&i.UseTls,
			&i.Fqdn,
			&i.CaCert,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLdapTemplates = `-- name: GetAllLdapTemplates :many
SELECT id, name, filter, interface_name, is_admin, mfa_auth, listen_port, mtu, dns FROM ldap_templates
`

func (q *Queries) GetAllLdapTemplates(ctx context.Context) ([]LdapTemplate, error) {
	rows, err := q.db.Query(ctx, getAllLdapTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LdapTemplate
	for rows.Next() {
		var i LdapTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Filter,
			&i.InterfaceName,
			&i.IsAdmin,
			&i.MfaAuth,
			&i.ListenPort,
			&i.Mtu,
			&i.Dns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllServers = `-- name: GetAllServers :many
SELECT id, name, endpoint, description, healthcheck_address
FROM servers
`

type GetAllServersRow struct {
	ID                 int
	Name               string
	Endpoint           netip.Addr
	Description        string
	HealthcheckAddress *netip.Addr
}

func (q *Queries) GetAllServers(ctx context.Context) ([]GetAllServersRow, error) {
	rows, err := q.db.Query(ctx, getAllServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllServersRow
	for rows.Next() {
		var i GetAllServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Description,
			&i.HealthcheckAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSessions = `-- name: GetAllSessions :many
SELECT session_id FROM devices WHERE session_id != '' AND session_id IS NOT NULL
`

func (q *Queries) GetAllSessions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, is_admin, auth_service, mfa_auth, ntf, updated_at
FROM users
ORDER BY id
`

type GetAllUsersRow struct {
	ID          int
	Username    string
	IsAdmin     bool
	AuthService AuthServiceType
	MfaAuth     MfaAuthType
	Ntf         string
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsAdmin,
			&i.AuthService,
			&i.MfaAuth,
			&i.Ntf,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCA = `-- name: GetCA :one
SELECT cert, key_encrypted
FROM root_ca
LIMIT 1
`

type GetCARow struct {
	Cert         []byte
	KeyEncrypted aesgcm.Ciphertext
}

func (q *Queries) GetCA(ctx context.Context) (GetCARow, error) {
	row := q.db.QueryRow(ctx, getCA)
	var i GetCARow
	err := row.Scan(&i.Cert, &i.KeyEncrypted)
	return i, err
}

const getDeviceByExternalID = `-- name: GetDeviceByExternalID :one
SELECT id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted FROM devices WHERE external_device_id=$1
`

func (q *Queries) GetDeviceByExternalID(ctx context.Context, externalDeviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByExternalID, externalDeviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const getDeviceByExternalIDAndUserID = `-- name: GetDeviceByExternalIDAndUserID :one
SELECT d.id, d.description, d.device_template_id, d.private_key, d.public_key, d.external_device_id, d.session_id, d.last_time_connected, d.created_at, d.updated_at, d.device_information, d.private_key_encrypted FROM devices d
JOIN device_templates dt ON d.device_template_id = dt.id
WHERE d.external_device_id=$1 AND d.external_device_id!='' AND dt.user_id=$2
`

type GetDeviceByExternalIDAndUserIDParams struct {
	ExternalDeviceID string
	UserID           int
}

func (q *Queries) GetDeviceByExternalIDAndUserID(ctx context.Context, arg GetDeviceByExternalIDAndUserIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByExternalIDAndUserID, arg.ExternalDeviceID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted FROM devices WHERE id=$1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id int) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const getDeviceByUserID = `-- name: GetDeviceByUserID :one
SELECT d.id, d.description, d.device_template_id, d.private_key, d.public_key, d.external_device_id, d.session_id, d.last_time_connected, d.created_at, d.updated_at, d.device_information, d.private_key_encrypted FROM devices d
JOIN device_templates dt ON d.device_template_id = dt.id
WHERE dt.user_id=$1
LIMIT 1
`

func (q *Queries) GetDeviceByUserID(ctx context.Context, userID int) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByUserID, userID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const getDeviceTemplateAddressPoolIDs = `-- name: GetDeviceTemplateAddressPoolIDs :many
SELECT address_pool_id
FROM device_template_address_pools
WHERE device_template_id=$1
`

func (q *Queries) GetDeviceTemplateAddressPoolIDs(ctx context.Context, deviceTemplateID int) ([]int, error) {
	rows, err := q.db.Query(ctx, getDeviceTemplateAddressPoolIDs, deviceTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var address_pool_id int
		if err := rows.Scan(&address_pool_id); err != nil {
			return nil, err
		}
		items = append(items, address_pool_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceTemplateAddressPools = `-- name: GetDeviceTemplateAddressPools :many
SELECT ap.id, ap.name, ap.description, ap.start_addr, ap.end_addr, ap.net_mask, ap.created_at, ap.updated_at FROM address_pools ap
JOIN device_template_address_pools dtap ON ap.id = dtap.address_pool_id
WHERE dtap.device_template_id=$1
`

func (q *Queries) GetDeviceTemplateAddressPools(ctx context.Context, deviceTemplateID int) ([]AddressPool, error) {
	rows, err := q.db.Query(ctx, getDeviceTemplateAddressPools, deviceTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddressPool
	for rows.Next() {
		var i AddressPool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StartAddr,
			&i.EndAddr,
			&i.NetMask,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceTemplateByID = `-- name: GetDeviceTemplateByID :one
SELECT
    id,
    user_id,
    interface_name,
    COALESCE(listen_port, -1),
    COALESCE(mtu, -1)
FROM device_templates
WHERE id=$1
`

type GetDeviceTemplateByIDRow struct {
	ID            int
	UserID        int
	InterfaceName string
	ListenPort    int
	Mtu           int
}

func (q *Queries) GetDeviceTemplateByID(ctx context.Context, id int) (GetDeviceTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeviceTemplateByID, id)
	var i GetDeviceTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InterfaceName,
		&i.ListenPort,
		&i.Mtu,
	)
	return i, err
}

const getDeviceTemplateByUserID = `-- name: GetDeviceTemplateByUserID :one
SELECT
    id,
    user_id,
    interface_name,
    COALESCE(listen_port, -1),
    COALESCE(mtu, -1)
FROM device_templates
WHERE user_id=$1
`

type GetDeviceTemplateByUserIDRow struct {
	ID            int
	UserID        int
	InterfaceName string
	ListenPort    int
	Mtu           int
}

func (q *Queries) GetDeviceTemplateByUserID(ctx context.Context, userID int) (GetDeviceTemplateByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getDeviceTemplateByUserID, userID)
	var i GetDeviceTemplateByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InterfaceName,
		&i.ListenPort,
		&i.Mtu,
	)
	return i, err
}

const getDeviceTemplateWireGuardIfaceDNSs = `-- name: GetDeviceTemplateWireGuardIfaceDNSs :many
SELECT dns
FROM device_template_wg_iface_dnss
WHERE device_template_id=$1
`

func (q *Queries) GetDeviceTemplateWireGuardIfaceDNSs(ctx context.Context, deviceTemplateID int) ([]string, error) {
	rows, err := q.db.Query(ctx, getDeviceTemplateWireGuardIfaceDNSs, deviceTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dns string
		if err := rows.Scan(&dns); err != nil {
			return nil, err
		}
		items = append(items, dns)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceWireGuardAdjacencies = `-- name: GetDeviceWireGuardAdjacencies :many
SELECT
    adjacencies.id,
    adjacencies.server_side_allowed_ips,
    adjacencies.client_side_allowed_ips,
    COALESCE(adjacencies.preshared_key_encrypted, ''),
    COALESCE(server_wg_configs.persistent_keepalive, -1),
    COALESCE(server_wg_configs.listen_port, -1),
    server_wg_configs.public_key,
    servers.id AS serverID,
    servers.name AS serverName,
    servers.endpoint AS serverEndpoint,
    servers.description AS serverDescription,
    servers.healthcheck_address AS serverHealthcheckAddress
FROM adjacencies
JOIN servers ON adjacencies.server_id=servers.id
JOIN server_wg_configs ON adjacencies.server_id=server_wg_configs.server_id
WHERE adjacencies.device_id=$1
`

type GetDeviceWireGuardAdjacenciesRow struct {
	ID                       int
	ServerSideAllowedIps     []netip.Prefix
	ClientSideAllowedIps     []netip.Prefix
	PresharedKeyEncrypted    aesgcm.Ciphertext
	PersistentKeepalive      int
	ListenPort               int
	PublicKey                string
	Serverid                 int
	Servername               string
	Serverendpoint           netip.Addr
	Serverdescription        string
	Serverhealthcheckaddress *netip.Addr
}

func (q *Queries) GetDeviceWireGuardAdjacencies(ctx context.Context, deviceID int) ([]GetDeviceWireGuardAdjacenciesRow, error) {
	rows, err := q.db.Query(ctx, getDeviceWireGuardAdjacencies, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceWireGuardAdjacenciesRow
	for rows.Next() {
		var i GetDeviceWireGuardAdjacenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerSideAllowedIps,
			&i.ClientSideAllowedIps,
			&i.PresharedKeyEncrypted,
			&i.PersistentKeepalive,
			&i.ListenPort,
			&i.PublicKey,
			&i.Serverid,
			&i.Servername,
			&i.Serverendpoint,
			&i.Serverdescription,
			&i.Serverhealthcheckaddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceWireGuardIfaceAddrs = `-- name: GetDeviceWireGuardIfaceAddrs :many
SELECT addr
FROM device_wg_iface_addresses
WHERE device_id=$1
`

func (q *Queries) GetDeviceWireGuardIfaceAddrs(ctx context.Context, deviceID int) ([]netip.Prefix, error) {
	rows, err := q.db.Query(ctx, getDeviceWireGuardIfaceAddrs, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []netip.Prefix
	for rows.Next() {
		var addr netip.Prefix
		if err := rows.Scan(&addr); err != nil {
			return nil, err
		}
		items = append(items, addr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceWithNoExternalIDByUserID = `-- name: GetDeviceWithNoExternalIDByUserID :one
SELECT d.id, d.description, d.device_template_id, d.private_key, d.public_key, d.external_device_id, d.session_id, d.last_time_connected, d.created_at, d.updated_at, d.device_information, d.private_key_encrypted FROM devices d
JOIN device_templates dt ON d.device_template_id = dt.id
WHERE d.external_device_id='' AND dt.user_id=$1
LIMIT 1
`

func (q *Queries) GetDeviceWithNoExternalIDByUserID(ctx context.Context, userID int) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceWithNoExternalIDByUserID, userID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const getDeviceWithNoSessionIDOrderedByTimestamp = `-- name: GetDeviceWithNoSessionIDOrderedByTimestamp :one
SELECT d.id, d.description, d.device_template_id, d.private_key, d.public_key, d.external_device_id, d.session_id, d.last_time_connected, d.created_at, d.updated_at, d.device_information, d.private_key_encrypted FROM devices d
JOIN device_templates dt ON d.device_template_id = dt.id
WHERE d.session_id='' AND dt.user_id=$1
ORDER BY d.last_time_connected ASC NULLS FIRST
LIMIT 1
`

func (q *Queries) GetDeviceWithNoSessionIDOrderedByTimestamp(ctx context.Context, userID int) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceWithNoSessionIDOrderedByTimestamp, userID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const getDeviceWithOldestTimestampByUserID = `-- name: GetDeviceWithOldestTimestampByUserID :one
SELECT d.id, d.description, d.device_template_id, d.private_key, d.public_key, d.external_device_id, d.session_id, d.last_time_connected, d.created_at, d.updated_at, d.device_information, d.private_key_encrypted FROM devices d
JOIN device_templates dt ON d.device_template_id = dt.id
WHERE dt.user_id=$1
ORDER BY d.last_time_connected ASC NULLS FIRST
LIMIT 1
`

func (q *Queries) GetDeviceWithOldestTimestampByUserID(ctx context.Context, userID int) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceWithOldestTimestampByUserID, userID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const getDevicesByTemplateID = `-- name: GetDevicesByTemplateID :many
SELECT id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted FROM devices WHERE device_template_id=$1
`

func (q *Queries) GetDevicesByTemplateID(ctx context.Context, deviceTemplateID int) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByTemplateID, deviceTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DeviceTemplateID,
			&i.PrivateKey,
			&i.PublicKey,
			&i.ExternalDeviceID,
			&i.SessionID,
			&i.LastTimeConnected,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceInformation,
			&i.PrivateKeyEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesByUserID = `-- name: GetDevicesByUserID :many
SELECT d.id, d.description, d.device_template_id, d.private_key, d.public_key, d.external_device_id, d.session_id, d.last_time_connected, d.created_at, d.updated_at, d.device_information, d.private_key_encrypted FROM devices d
JOIN device_templates dt ON d.device_template_id = dt.id
WHERE dt.user_id=$1
`

func (q *Queries) GetDevicesByUserID(ctx context.Context, userID int) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DeviceTemplateID,
			&i.PrivateKey,
			&i.PublicKey,
			&i.ExternalDeviceID,
			&i.SessionID,
			&i.LastTimeConnected,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceInformation,
			&i.PrivateKeyEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLdapConfigByID = `-- name: GetLdapConfigByID :one
SELECT
    priority, host, port, base_dn, bind_dn, bind_pw_encrypted,
    user_list_filter, username_attribute, uid_attribute,
    use_tls, fqdn, ca_cert, COALESCE(template_id, 0)
FROM ldaps
WHERE id=$1
`

type GetLdapConfigByIDRow struct {
	Priority          int
	Host              string
	Port              int
	BaseDn            string
	BindDn            string
	BindPwEncrypted   aesgcm.Ciphertext
	UserListFilter    string
	UsernameAttribute string
	UidAttribute      string
	UseTls            bool
	Fqdn              string
	CaCert            []byte
	TemplateID        int
}

func (q *Queries) GetLdapConfigByID(ctx context.Context, id string) (GetLdapConfigByIDRow, error) {
	row := q.db.QueryRow(ctx, getLdapConfigByID, id)
	var i GetLdapConfigByIDRow
	err := row.Scan(
		&i.Priority,
		&i.Host,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindPwEncrypted,
		&i.UserListFilter,
		&i.UsernameAttribute,
		&i.UidAttribute,
		&i.UseTls,
		&i.Fqdn,
		&i.CaCert,
		&i.TemplateID,
	)
	return i, err
}

const getLdapRelationByLdapIdAndUserID = `-- name: GetLdapRelationByLdapIdAndUserID :one
SELECT id, user_id, user_dn, created_at, updated_at
FROM users_to_ldaps
WHERE ldap_id=$1
AND user_uid=$2
`

type GetLdapRelationByLdapIdAndUserIDParams struct {
	LdapID  pgtype.UUID
	UserUid string
}

type GetLdapRelationByLdapIdAndUserIDRow struct {
	ID        int
	UserID    *int
	UserDn    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// struct_name: UsersToLdaps
func (q *Queries) GetLdapRelationByLdapIdAndUserID(ctx context.Context, arg GetLdapRelationByLdapIdAndUserIDParams) (GetLdapRelationByLdapIdAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, getLdapRelationByLdapIdAndUserID, arg.LdapID, arg.UserUid)
	var i GetLdapRelationByLdapIdAndUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserDn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLdapTemplateAddressPools = `-- name: GetLdapTemplateAddressPools :many
SELECT ap.id, ap.name, ap.description, ap.start_addr, ap.end_addr, ap.net_mask, ap.created_at, ap.updated_at
FROM address_pools ap
JOIN ldap_template_address_pools ltap ON ap.id = ltap.address_pool_id
WHERE ltap.ldap_template_id = $1
`

func (q *Queries) GetLdapTemplateAddressPools(ctx context.Context, ldapTemplateID int) ([]AddressPool, error) {
	rows, err := q.db.Query(ctx, getLdapTemplateAddressPools, ldapTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddressPool
	for rows.Next() {
		var i AddressPool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StartAddr,
			&i.EndAddr,
			&i.NetMask,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLdapTemplateByID = `-- name: GetLdapTemplateByID :one
SELECT id, name, filter, interface_name, is_admin, mfa_auth, listen_port, mtu, dns FROM ldap_templates
WHERE id=$1
`

func (q *Queries) GetLdapTemplateByID(ctx context.Context, id int) (LdapTemplate, error) {
	row := q.db.QueryRow(ctx, getLdapTemplateByID, id)
	var i LdapTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filter,
		&i.InterfaceName,
		&i.IsAdmin,
		&i.MfaAuth,
		&i.ListenPort,
		&i.Mtu,
		&i.Dns,
	)
	return i, err
}

const getLdapTemplateServers = `-- name: GetLdapTemplateServers :many
SELECT servers.name, server_id, ldap_template_id, allowed_ips, use_preshared_key
FROM ldap_template_servers
LEFT JOIN servers
ON ldap_template_servers.server_id = servers.id
WHERE ldap_template_servers.ldap_template_id=$1
`

type GetLdapTemplateServersRow struct {
	Name            *string
	ServerID        *int
	LdapTemplateID  int
	AllowedIps      []netip.Prefix
	UsePresharedKey bool
}

func (q *Queries) GetLdapTemplateServers(ctx context.Context, ldapTemplateID int) ([]GetLdapTemplateServersRow, error) {
	rows, err := q.db.Query(ctx, getLdapTemplateServers, ldapTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLdapTemplateServersRow
	for rows.Next() {
		var i GetLdapTemplateServersRow
		if err := rows.Scan(
			&i.Name,
			&i.ServerID,
			&i.LdapTemplateID,
			&i.AllowedIps,
			&i.UsePresharedKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLdapTemplateServersByServerID = `-- name: GetLdapTemplateServersByServerID :many
SELECT ldap_template_id, server_id, allowed_ips, use_preshared_key
FROM ldap_template_servers
WHERE server_id=$1
`

type GetLdapTemplateServersByServerIDRow struct {
	LdapTemplateID  int
	ServerID        *int
	AllowedIps      []netip.Prefix
	UsePresharedKey bool
}

func (q *Queries) GetLdapTemplateServersByServerID(ctx context.Context, serverID *int) ([]GetLdapTemplateServersByServerIDRow, error) {
	rows, err := q.db.Query(ctx, getLdapTemplateServersByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLdapTemplateServersByServerIDRow
	for rows.Next() {
		var i GetLdapTemplateServersByServerIDRow
		if err := rows.Scan(
			&i.LdapTemplateID,
			&i.ServerID,
			&i.AllowedIps,
			&i.UsePresharedKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLdapUserAuths = `-- name: GetLdapUserAuths :many
SELECT ldaps.priority, ldaps.host, ldaps.port, users_to_ldaps.user_dn, ldaps.use_tls, ldaps.fqdn, ldaps.ca_cert
FROM users_to_ldaps
JOIN ldaps ON users_to_ldaps.ldap_id=ldaps.id
WHERE users_to_ldaps.user_id=$1
ORDER BY ldaps.priority
`

type GetLdapUserAuthsRow struct {
	Priority int
	Host     string
	Port     int
	UserDn   string
	UseTls   bool
	Fqdn     string
	CaCert   []byte
}

func (q *Queries) GetLdapUserAuths(ctx context.Context, userID *int) ([]GetLdapUserAuthsRow, error) {
	rows, err := q.db.Query(ctx, getLdapUserAuths, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLdapUserAuthsRow
	for rows.Next() {
		var i GetLdapUserAuthsRow
		if err := rows.Scan(
			&i.Priority,
			&i.Host,
			&i.Port,
			&i.UserDn,
			&i.UseTls,
			&i.Fqdn,
			&i.CaCert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLdapUsersPriorities = `-- name: GetLdapUsersPriorities :many
SELECT ldaps.priority, users_to_ldaps.user_id, users_to_ldaps.ldap_id
FROM users_to_ldaps
JOIN ldaps ON users_to_ldaps.ldap_id=ldaps.id
ORDER BY ldaps.priority
`

type GetLdapUsersPrioritiesRow struct {
	Priority int
	UserID   *int
	LdapID   pgtype.UUID
}

func (q *Queries) GetLdapUsersPriorities(ctx context.Context) ([]GetLdapUsersPrioritiesRow, error) {
	rows, err := q.db.Query(ctx, getLdapUsersPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLdapUsersPrioritiesRow
	for rows.Next() {
		var i GetLdapUsersPrioritiesRow
		if err := rows.Scan(&i.Priority, &i.UserID, &i.LdapID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLdapUsersWithoutRelations = `-- name: GetLdapUsersWithoutRelations :many
SELECT id, username
FROM users
WHERE id IN (
    SELECT users.id
    FROM users
    LEFT JOIN users_to_ldaps ON users.id=users_to_ldaps.user_id
    WHERE users.auth_service='ldap'
    GROUP BY users.id
    HAVING COUNT(users_to_ldaps.id) = 0
)
`

type GetLdapUsersWithoutRelationsRow struct {
	ID       int
	Username string
}

func (q *Queries) GetLdapUsersWithoutRelations(ctx context.Context) ([]GetLdapUsersWithoutRelationsRow, error) {
	rows, err := q.db.Query(ctx, getLdapUsersWithoutRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLdapUsersWithoutRelationsRow
	for rows.Next() {
		var i GetLdapUsersWithoutRelationsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMFACertsByType = `-- name: GetMFACertsByType :many
SELECT id, cert
FROM mfa_certs
WHERE cert_type=$1
`

type GetMFACertsByTypeRow struct {
	ID   int
	Cert []byte
}

func (q *Queries) GetMFACertsByType(ctx context.Context, certType MfaCertType) ([]GetMFACertsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getMFACertsByType, certType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMFACertsByTypeRow
	for rows.Next() {
		var i GetMFACertsByTypeRow
		if err := rows.Scan(&i.ID, &i.Cert); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerByID = `-- name: GetServerByID :one
SELECT name, endpoint, description, healthcheck_address
FROM servers
WHERE id=$1
`

type GetServerByIDRow struct {
	Name               string
	Endpoint           netip.Addr
	Description        string
	HealthcheckAddress *netip.Addr
}

func (q *Queries) GetServerByID(ctx context.Context, id int) (GetServerByIDRow, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i GetServerByIDRow
	err := row.Scan(
		&i.Name,
		&i.Endpoint,
		&i.Description,
		&i.HealthcheckAddress,
	)
	return i, err
}

const getServerByName = `-- name: GetServerByName :one
SELECT id, endpoint, description, healthcheck_address
FROM servers
WHERE name=$1
`

type GetServerByNameRow struct {
	ID                 int
	Endpoint           netip.Addr
	Description        string
	HealthcheckAddress *netip.Addr
}

func (q *Queries) GetServerByName(ctx context.Context, name string) (GetServerByNameRow, error) {
	row := q.db.QueryRow(ctx, getServerByName, name)
	var i GetServerByNameRow
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.Description,
		&i.HealthcheckAddress,
	)
	return i, err
}

const getServerReplicas = `-- name: GetServerReplicas :many
SELECT running_replicas
FROM servers
WHERE id=$1
`

func (q *Queries) GetServerReplicas(ctx context.Context, id int) ([]int16, error) {
	rows, err := q.db.Query(ctx, getServerReplicas, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var running_replicas int16
		if err := rows.Scan(&running_replicas); err != nil {
			return nil, err
		}
		items = append(items, running_replicas)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerTags = `-- name: GetServerTags :many
SELECT tag FROM tags
WHERE server_id=$1
`

func (q *Queries) GetServerTags(ctx context.Context, serverID *int) ([]string, error) {
	rows, err := q.db.Query(ctx, getServerTags, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerTagsByName = `-- name: GetServerTagsByName :many
SELECT tag FROM tags
WHERE server_id IN (
    SELECT id FROM servers WHERE name=$1)
ORDER BY created DESC
`

func (q *Queries) GetServerTagsByName(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getServerTagsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerWireGuardAdjacencies = `-- name: GetServerWireGuardAdjacencies :many
SELECT
    adjacencies.id,
    adjacencies.device_id,
    adjacencies.server_side_allowed_ips,
    adjacencies.client_side_allowed_ips,
    COALESCE(adjacencies.preshared_key_encrypted, ''),
    COALESCE(dt.listen_port, -1),
    d.public_key
FROM adjacencies
JOIN devices d ON adjacencies.device_id = d.id
JOIN device_templates dt ON dt.id = d.device_template_id
WHERE adjacencies.server_id=$1
`

type GetServerWireGuardAdjacenciesRow struct {
	ID                    int
	DeviceID              int
	ServerSideAllowedIps  []netip.Prefix
	ClientSideAllowedIps  []netip.Prefix
	PresharedKeyEncrypted aesgcm.Ciphertext
	ListenPort            int
	PublicKey             string
}

func (q *Queries) GetServerWireGuardAdjacencies(ctx context.Context, serverID int) ([]GetServerWireGuardAdjacenciesRow, error) {
	rows, err := q.db.Query(ctx, getServerWireGuardAdjacencies, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServerWireGuardAdjacenciesRow
	for rows.Next() {
		var i GetServerWireGuardAdjacenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.ServerSideAllowedIps,
			&i.ClientSideAllowedIps,
			&i.PresharedKeyEncrypted,
			&i.ListenPort,
			&i.PublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerWireGuardConfig = `-- name: GetServerWireGuardConfig :one
SELECT
    id,
    interface_name,
    private_key_encrypted,
    public_key,
    COALESCE(listen_port, -1),
    COALESCE(mtu, -1),
    COALESCE(persistent_keepalive, -1)
FROM server_wg_configs
WHERE server_id=$1
`

type GetServerWireGuardConfigRow struct {
	ID                  int
	InterfaceName       string
	PrivateKeyEncrypted aesgcm.Ciphertext
	PublicKey           string
	ListenPort          int
	Mtu                 int
	PersistentKeepalive int
}

func (q *Queries) GetServerWireGuardConfig(ctx context.Context, serverID int) (GetServerWireGuardConfigRow, error) {
	row := q.db.QueryRow(ctx, getServerWireGuardConfig, serverID)
	var i GetServerWireGuardConfigRow
	err := row.Scan(
		&i.ID,
		&i.InterfaceName,
		&i.PrivateKeyEncrypted,
		&i.PublicKey,
		&i.ListenPort,
		&i.Mtu,
		&i.PersistentKeepalive,
	)
	return i, err
}

const getServerWireGuardIfaceAddrs = `-- name: GetServerWireGuardIfaceAddrs :many
SELECT addr
FROM server_wg_iface_addresses
WHERE server_config_id=$1
`

func (q *Queries) GetServerWireGuardIfaceAddrs(ctx context.Context, serverConfigID int) ([]netip.Prefix, error) {
	rows, err := q.db.Query(ctx, getServerWireGuardIfaceAddrs, serverConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []netip.Prefix
	for rows.Next() {
		var addr netip.Prefix
		if err := rows.Scan(&addr); err != nil {
			return nil, err
		}
		items = append(items, addr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerWireGuardIfaceDNSs = `-- name: GetServerWireGuardIfaceDNSs :many
SELECT dns
FROM server_wg_iface_dnss
WHERE server_config_id=$1
`

func (q *Queries) GetServerWireGuardIfaceDNSs(ctx context.Context, serverConfigID int) ([]string, error) {
	rows, err := q.db.Query(ctx, getServerWireGuardIfaceDNSs, serverConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dns string
		if err := rows.Scan(&dns); err != nil {
			return nil, err
		}
		items = append(items, dns)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByDeviceID = `-- name: GetSessionByDeviceID :one
SELECT session_id, last_time_connected FROM devices WHERE id=$1
`

type GetSessionByDeviceIDRow struct {
	SessionID         string
	LastTimeConnected pgtype.Timestamp
}

func (q *Queries) GetSessionByDeviceID(ctx context.Context, id int) (GetSessionByDeviceIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByDeviceID, id)
	var i GetSessionByDeviceIDRow
	err := row.Scan(&i.SessionID, &i.LastTimeConnected)
	return i, err
}

const getUserAdjacencyTemplates = `-- name: GetUserAdjacencyTemplates :many
SELECT
    adjacency_templates.id,
    adjacency_templates.server_id,
    adjacency_templates.user_id,
    adjacency_templates.client_side_allowed_ips,
    adjacency_templates.use_preshared_key,
    servers.name AS server_name,
    servers.endpoint AS server_endpoint,
    servers.description AS server_description,
    servers.healthcheck_address AS server_healthcheck_address
FROM adjacency_templates
JOIN servers ON adjacency_templates.server_id=servers.id
WHERE adjacency_templates.user_id=$1
`

type GetUserAdjacencyTemplatesRow struct {
	ID                       int
	ServerID                 int
	UserID                   int
	ClientSideAllowedIps     []netip.Prefix
	UsePresharedKey          bool
	ServerName               string
	ServerEndpoint           netip.Addr
	ServerDescription        string
	ServerHealthcheckAddress *netip.Addr
}

func (q *Queries) GetUserAdjacencyTemplates(ctx context.Context, userID int) ([]GetUserAdjacencyTemplatesRow, error) {
	rows, err := q.db.Query(ctx, getUserAdjacencyTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAdjacencyTemplatesRow
	for rows.Next() {
		var i GetUserAdjacencyTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.ClientSideAllowedIps,
			&i.UsePresharedKey,
			&i.ServerName,
			&i.ServerEndpoint,
			&i.ServerDescription,
			&i.ServerHealthcheckAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT username, password, is_admin, auth_service, mfa_auth, ntf, updated_at
FROM users
WHERE id=$1
`

type GetUserByIDRow struct {
	Username    string
	Password    string
	IsAdmin     bool
	AuthService AuthServiceType
	MfaAuth     MfaAuthType
	Ntf         string
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) GetUserByID(ctx context.Context, id int) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.IsAdmin,
		&i.AuthService,
		&i.MfaAuth,
		&i.Ntf,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, password, is_admin, auth_service, mfa_auth, ntf, updated_at
FROM users
WHERE username=$1
`

type GetUserByUsernameRow struct {
	ID          int
	Password    string
	IsAdmin     bool
	AuthService AuthServiceType
	MfaAuth     MfaAuthType
	Ntf         string
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.IsAdmin,
		&i.AuthService,
		&i.MfaAuth,
		&i.Ntf,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTOTP = `-- name: GetUserTOTP :one
SELECT key_encrypted
FROM totp
WHERE user_id=$1
`

func (q *Queries) GetUserTOTP(ctx context.Context, userID *int) (aesgcm.Ciphertext, error) {
	row := q.db.QueryRow(ctx, getUserTOTP, userID)
	var key_encrypted aesgcm.Ciphertext
	err := row.Scan(&key_encrypted)
	return key_encrypted, err
}

const getWireGuardIfaceAllAddrs = `-- name: GetWireGuardIfaceAllAddrs :many
SELECT addr FROM device_wg_iface_addresses
UNION ALL
SELECT addr FROM server_wg_iface_addresses
`

func (q *Queries) GetWireGuardIfaceAllAddrs(ctx context.Context) ([]netip.Prefix, error) {
	rows, err := q.db.Query(ctx, getWireGuardIfaceAllAddrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []netip.Prefix
	for rows.Next() {
		var addr netip.Prefix
		if err := rows.Scan(&addr); err != nil {
			return nil, err
		}
		items = append(items, addr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseServerReplicas = `-- name: IncreaseServerReplicas :one
UPDATE servers 
SET running_replicas = running_replicas + 1
WHERE id=$1
RETURNING id, name, endpoint, description, running_replicas, healthcheck_address
`

func (q *Queries) IncreaseServerReplicas(ctx context.Context, id int) (Server, error) {
	row := q.db.QueryRow(ctx, increaseServerReplicas, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Description,
		&i.RunningReplicas,
		&i.HealthcheckAddress,
	)
	return i, err
}

const insertAddressPool = `-- name: InsertAddressPool :one
INSERT INTO address_pools (
    name, description, start_addr, end_addr, net_mask
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, start_addr, end_addr, net_mask, created_at, updated_at
`

type InsertAddressPoolParams struct {
	Name        string
	Description string
	StartAddr   netip.Addr
	EndAddr     netip.Addr
	NetMask     int
}

func (q *Queries) InsertAddressPool(ctx context.Context, arg InsertAddressPoolParams) (AddressPool, error) {
	row := q.db.QueryRow(ctx, insertAddressPool,
		arg.Name,
		arg.Description,
		arg.StartAddr,
		arg.EndAddr,
		arg.NetMask,
	)
	var i AddressPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartAddr,
		&i.EndAddr,
		&i.NetMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAdjacency = `-- name: InsertAdjacency :one
INSERT INTO adjacencies(server_id, device_id, server_side_allowed_ips, client_side_allowed_ips, preshared_key_encrypted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, server_id, device_id, server_side_allowed_ips, client_side_allowed_ips, preshared_key, preshared_key_encrypted
`

type InsertAdjacencyParams struct {
	ServerID              int
	DeviceID              int
	ServerSideAllowedIps  []netip.Prefix
	ClientSideAllowedIps  []netip.Prefix
	PresharedKeyEncrypted aesgcm.Ciphertext
}

func (q *Queries) InsertAdjacency(ctx context.Context, arg InsertAdjacencyParams) (Adjacency, error) {
	row := q.db.QueryRow(ctx, insertAdjacency,
		arg.ServerID,
		arg.DeviceID,
		arg.ServerSideAllowedIps,
		arg.ClientSideAllowedIps,
		arg.PresharedKeyEncrypted,
	)
	var i Adjacency
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.DeviceID,
		&i.ServerSideAllowedIps,
		&i.ClientSideAllowedIps,
		&i.PresharedKey,
		&i.PresharedKeyEncrypted,
	)
	return i, err
}

const insertAdjacencyTemplate = `-- name: InsertAdjacencyTemplate :one
INSERT INTO adjacency_templates(server_id, user_id, client_side_allowed_ips, use_preshared_key)
VALUES ($1, $2, $3, $4)
RETURNING id, server_id, user_id, client_side_allowed_ips, use_preshared_key
`

type InsertAdjacencyTemplateParams struct {
	ServerID             int
	UserID               int
	ClientSideAllowedIps []netip.Prefix
	UsePresharedKey      bool
}

func (q *Queries) InsertAdjacencyTemplate(ctx context.Context, arg InsertAdjacencyTemplateParams) (AdjacencyTemplate, error) {
	row := q.db.QueryRow(ctx, insertAdjacencyTemplate,
		arg.ServerID,
		arg.UserID,
		arg.ClientSideAllowedIps,
		arg.UsePresharedKey,
	)
	var i AdjacencyTemplate
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.ClientSideAllowedIps,
		&i.UsePresharedKey,
	)
	return i, err
}

const insertCA = `-- name: InsertCA :one
INSERT INTO root_ca (cert, key_encrypted) VALUES ($1, $2)
RETURNING id, cert, key, key_encrypted
`

type InsertCAParams struct {
	Cert         []byte
	KeyEncrypted aesgcm.Ciphertext
}

func (q *Queries) InsertCA(ctx context.Context, arg InsertCAParams) (RootCa, error) {
	row := q.db.QueryRow(ctx, insertCA, arg.Cert, arg.KeyEncrypted)
	var i RootCa
	err := row.Scan(
		&i.ID,
		&i.Cert,
		&i.Key,
		&i.KeyEncrypted,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices(description, device_template_id, external_device_id, private_key_encrypted, public_key, device_information, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted
`

type InsertDeviceParams struct {
	Description         string
	DeviceTemplateID    int
	ExternalDeviceID    string
	PrivateKeyEncrypted aesgcm.Ciphertext
	PublicKey           string
	DeviceInformation   *string
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, insertDevice,
		arg.Description,
		arg.DeviceTemplateID,
		arg.ExternalDeviceID,
		arg.PrivateKeyEncrypted,
		arg.PublicKey,
		arg.DeviceInformation,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const insertDeviceTemplate = `-- name: InsertDeviceTemplate :one
INSERT INTO device_templates(user_id, interface_name, listen_port, mtu, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, user_id, interface_name, listen_port, mtu, created_at, updated_at
`

type InsertDeviceTemplateParams struct {
	UserID        int
	InterfaceName string
	ListenPort    *int
	Mtu           *int
}

func (q *Queries) InsertDeviceTemplate(ctx context.Context, arg InsertDeviceTemplateParams) (DeviceTemplate, error) {
	row := q.db.QueryRow(ctx, insertDeviceTemplate,
		arg.UserID,
		arg.InterfaceName,
		arg.ListenPort,
		arg.Mtu,
	)
	var i DeviceTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InterfaceName,
		&i.ListenPort,
		&i.Mtu,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeviceTemplateAddressPool = `-- name: InsertDeviceTemplateAddressPool :one
INSERT INTO device_template_address_pools(device_template_id, address_pool_id)
VALUES ($1, $2)
RETURNING id, device_template_id, address_pool_id
`

type InsertDeviceTemplateAddressPoolParams struct {
	DeviceTemplateID int
	AddressPoolID    int
}

func (q *Queries) InsertDeviceTemplateAddressPool(ctx context.Context, arg InsertDeviceTemplateAddressPoolParams) (DeviceTemplateAddressPool, error) {
	row := q.db.QueryRow(ctx, insertDeviceTemplateAddressPool, arg.DeviceTemplateID, arg.AddressPoolID)
	var i DeviceTemplateAddressPool
	err := row.Scan(&i.ID, &i.DeviceTemplateID, &i.AddressPoolID)
	return i, err
}

const insertDeviceTemplateWireGuardIfaceDNS = `-- name: InsertDeviceTemplateWireGuardIfaceDNS :one
INSERT INTO device_template_wg_iface_dnss(device_template_id, dns)
VALUES ($1, $2)
RETURNING id, device_template_id, dns
`

type InsertDeviceTemplateWireGuardIfaceDNSParams struct {
	DeviceTemplateID int
	Dns              string
}

func (q *Queries) InsertDeviceTemplateWireGuardIfaceDNS(ctx context.Context, arg InsertDeviceTemplateWireGuardIfaceDNSParams) (DeviceTemplateWgIfaceDnss, error) {
	row := q.db.QueryRow(ctx, insertDeviceTemplateWireGuardIfaceDNS, arg.DeviceTemplateID, arg.Dns)
	var i DeviceTemplateWgIfaceDnss
	err := row.Scan(&i.ID, &i.DeviceTemplateID, &i.Dns)
	return i, err
}

const insertDeviceWireGuardIfaceAddr = `-- name: InsertDeviceWireGuardIfaceAddr :one
INSERT INTO device_wg_iface_addresses(device_id, addr)
VALUES ($1, $2)
RETURNING id, device_id, addr
`

type InsertDeviceWireGuardIfaceAddrParams struct {
	DeviceID int
	Addr     netip.Prefix
}

func (q *Queries) InsertDeviceWireGuardIfaceAddr(ctx context.Context, arg InsertDeviceWireGuardIfaceAddrParams) (DeviceWgIfaceAddress, error) {
	row := q.db.QueryRow(ctx, insertDeviceWireGuardIfaceAddr, arg.DeviceID, arg.Addr)
	var i DeviceWgIfaceAddress
	err := row.Scan(&i.ID, &i.DeviceID, &i.Addr)
	return i, err
}

const insertLdapConfig = `-- name: InsertLdapConfig :one
INSERT INTO ldaps (
    priority, host, port, base_dn,
    bind_dn, bind_pw_encrypted,
    user_list_filter, username_attribute, uid_attribute,
    use_tls, fqdn, ca_cert, template_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, priority, host, port, base_dn, bind_dn, bind_pw, user_list_filter, username_attribute, uid_attribute, use_tls, fqdn, ca_cert, template_id, bind_pw_encrypted
`

type InsertLdapConfigParams struct {
	Priority          int
	Host              string
	Port              int
	BaseDn            string
	BindDn            string
	BindPwEncrypted   aesgcm.Ciphertext
	UserListFilter    string
	UsernameAttribute string
	UidAttribute      string
	UseTls            bool
	Fqdn              string
	CaCert            []byte
	TemplateID        *int
}

func (q *Queries) InsertLdapConfig(ctx context.Context, arg InsertLdapConfigParams) (Ldap, error) {
	row := q.db.QueryRow(ctx, insertLdapConfig,
		arg.Priority,
		arg.Host,
		arg.Port,
		arg.BaseDn,
		arg.BindDn,
		arg.BindPwEncrypted,
		arg.UserListFilter,
		arg.UsernameAttribute,
		arg.UidAttribute,
		arg.UseTls,
		arg.Fqdn,
		arg.CaCert,
		arg.TemplateID,
	)
	var i Ldap
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Host,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindPw,
		&i.UserListFilter,
		&i.UsernameAttribute,
		&i.UidAttribute,
		&i.UseTls,
		&i.Fqdn,
		&i.CaCert,
		&i.TemplateID,
		&i.BindPwEncrypted,
	)
	return i, err
}

const insertLdapRelation = `-- name: InsertLdapRelation :one
INSERT INTO users_to_ldaps (user_id, ldap_id, user_uid, user_dn, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, ldap_id, user_uid, user_dn, created_at, updated_at
`

type InsertLdapRelationParams struct {
	UserID    *int
	LdapID    pgtype.UUID
	UserUid   string
	UserDn    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// struct_name: UsersToLdaps
func (q *Queries) InsertLdapRelation(ctx context.Context, arg InsertLdapRelationParams) (UsersToLdap, error) {
	row := q.db.QueryRow(ctx, insertLdapRelation,
		arg.UserID,
		arg.LdapID,
		arg.UserUid,
		arg.UserDn,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UsersToLdap
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LdapID,
		&i.UserUid,
		&i.UserDn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLdapTemplate = `-- name: InsertLdapTemplate :one
INSERT INTO ldap_templates (
    name, filter, interface_name, is_admin, mfa_auth, listen_port, mtu, dns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, filter, interface_name, is_admin, mfa_auth, listen_port, mtu, dns
`

type InsertLdapTemplateParams struct {
	Name          string
	Filter        *string
	InterfaceName string
	IsAdmin       bool
	MfaAuth       MfaAuthType
	ListenPort    *string
	Mtu           *string
	Dns           []string
}

func (q *Queries) InsertLdapTemplate(ctx context.Context, arg InsertLdapTemplateParams) (LdapTemplate, error) {
	row := q.db.QueryRow(ctx, insertLdapTemplate,
		arg.Name,
		arg.Filter,
		arg.InterfaceName,
		arg.IsAdmin,
		arg.MfaAuth,
		arg.ListenPort,
		arg.Mtu,
		arg.Dns,
	)
	var i LdapTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filter,
		&i.InterfaceName,
		&i.IsAdmin,
		&i.MfaAuth,
		&i.ListenPort,
		&i.Mtu,
		&i.Dns,
	)
	return i, err
}

const insertLdapTemplateAddressPool = `-- name: InsertLdapTemplateAddressPool :exec
INSERT INTO ldap_template_address_pools (ldap_template_id, address_pool_id)
VALUES ($1, $2)
`

type InsertLdapTemplateAddressPoolParams struct {
	LdapTemplateID int
	AddressPoolID  int
}

func (q *Queries) InsertLdapTemplateAddressPool(ctx context.Context, arg InsertLdapTemplateAddressPoolParams) error {
	_, err := q.db.Exec(ctx, insertLdapTemplateAddressPool, arg.LdapTemplateID, arg.AddressPoolID)
	return err
}

const insertLdapTemplateServer = `-- name: InsertLdapTemplateServer :one
INSERT INTO ldap_template_servers (
    ldap_template_id, server_id, allowed_ips, use_preshared_key
)
VALUES ($1, $2, $3, $4)
RETURNING id, ldap_template_id, server_id, allowed_ips, use_preshared_key
`

type InsertLdapTemplateServerParams struct {
	LdapTemplateID  int
	ServerID        *int
	AllowedIps      []netip.Prefix
	UsePresharedKey bool
}

func (q *Queries) InsertLdapTemplateServer(ctx context.Context, arg InsertLdapTemplateServerParams) (LdapTemplateServer, error) {
	row := q.db.QueryRow(ctx, insertLdapTemplateServer,
		arg.LdapTemplateID,
		arg.ServerID,
		arg.AllowedIps,
		arg.UsePresharedKey,
	)
	var i LdapTemplateServer
	err := row.Scan(
		&i.ID,
		&i.LdapTemplateID,
		&i.ServerID,
		&i.AllowedIps,
		&i.UsePresharedKey,
	)
	return i, err
}

const insertMFACert = `-- name: InsertMFACert :one
INSERT INTO mfa_certs(cert, cert_type)
VALUES ($1, $2)
RETURNING id, cert, cert_type
`

type InsertMFACertParams struct {
	Cert     []byte
	CertType MfaCertType
}

func (q *Queries) InsertMFACert(ctx context.Context, arg InsertMFACertParams) (MfaCert, error) {
	row := q.db.QueryRow(ctx, insertMFACert, arg.Cert, arg.CertType)
	var i MfaCert
	err := row.Scan(&i.ID, &i.Cert, &i.CertType)
	return i, err
}

const insertServer = `-- name: InsertServer :one
INSERT INTO servers (name, endpoint, description, healthcheck_address)
VALUES ($1, $2, $3, $4)
RETURNING id, name, endpoint, description, running_replicas, healthcheck_address
`

type InsertServerParams struct {
	Name               string
	Endpoint           netip.Addr
	Description        string
	HealthcheckAddress *netip.Addr
}

func (q *Queries) InsertServer(ctx context.Context, arg InsertServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, insertServer,
		arg.Name,
		arg.Endpoint,
		arg.Description,
		arg.HealthcheckAddress,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Description,
		&i.RunningReplicas,
		&i.HealthcheckAddress,
	)
	return i, err
}

const insertServerTag = `-- name: InsertServerTag :one
INSERT INTO tags (tag, created, server_id)
VALUES ($1, $2, $3)
RETURNING id, server_id, tag, created
`

type InsertServerTagParams struct {
	Tag      string
	Created  pgtype.Timestamp
	ServerID *int
}

func (q *Queries) InsertServerTag(ctx context.Context, arg InsertServerTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertServerTag, arg.Tag, arg.Created, arg.ServerID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Tag,
		&i.Created,
	)
	return i, err
}

const insertServerWireGuardConfig = `-- name: InsertServerWireGuardConfig :one
INSERT INTO server_wg_configs(server_id, interface_name, private_key_encrypted, public_key, listen_port, mtu, persistent_keepalive)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, server_id, interface_name, private_key, public_key, listen_port, mtu, persistent_keepalive, private_key_encrypted
`

type InsertServerWireGuardConfigParams struct {
	ServerID            int
	InterfaceName       string
	PrivateKeyEncrypted aesgcm.Ciphertext
	PublicKey           string
	ListenPort          *int
	Mtu                 *int
	PersistentKeepalive *int
}

func (q *Queries) InsertServerWireGuardConfig(ctx context.Context, arg InsertServerWireGuardConfigParams) (ServerWgConfig, error) {
	row := q.db.QueryRow(ctx, insertServerWireGuardConfig,
		arg.ServerID,
		arg.InterfaceName,
		arg.PrivateKeyEncrypted,
		arg.PublicKey,
		arg.ListenPort,
		arg.Mtu,
		arg.PersistentKeepalive,
	)
	var i ServerWgConfig
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.InterfaceName,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ListenPort,
		&i.Mtu,
		&i.PersistentKeepalive,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const insertServerWireGuardIfaceAddr = `-- name: InsertServerWireGuardIfaceAddr :one
INSERT INTO server_wg_iface_addresses(server_config_id, addr)
VALUES ($1, $2)
RETURNING id, server_config_id, addr
`

type InsertServerWireGuardIfaceAddrParams struct {
	ServerConfigID int
	Addr           netip.Prefix
}

func (q *Queries) InsertServerWireGuardIfaceAddr(ctx context.Context, arg InsertServerWireGuardIfaceAddrParams) (ServerWgIfaceAddress, error) {
	row := q.db.QueryRow(ctx, insertServerWireGuardIfaceAddr, arg.ServerConfigID, arg.Addr)
	var i ServerWgIfaceAddress
	err := row.Scan(&i.ID, &i.ServerConfigID, &i.Addr)
	return i, err
}

const insertServerWireGuardIfaceDNS = `-- name: InsertServerWireGuardIfaceDNS :one
INSERT INTO server_wg_iface_dnss(server_config_id, dns)
VALUES ($1, $2)
RETURNING id, server_config_id, dns
`

type InsertServerWireGuardIfaceDNSParams struct {
	ServerConfigID int
	Dns            string
}

func (q *Queries) InsertServerWireGuardIfaceDNS(ctx context.Context, arg InsertServerWireGuardIfaceDNSParams) (ServerWgIfaceDnss, error) {
	row := q.db.QueryRow(ctx, insertServerWireGuardIfaceDNS, arg.ServerConfigID, arg.Dns)
	var i ServerWgIfaceDnss
	err := row.Scan(&i.ID, &i.ServerConfigID, &i.Dns)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, password, is_admin, auth_service, mfa_auth, ntf, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, password, is_admin, auth_service, mfa_auth, ntf, updated_at
`

type InsertUserParams struct {
	Username    string
	Password    string
	IsAdmin     bool
	AuthService AuthServiceType
	MfaAuth     MfaAuthType
	Ntf         string
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Password,
		arg.IsAdmin,
		arg.AuthService,
		arg.MfaAuth,
		arg.Ntf,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsAdmin,
		&i.AuthService,
		&i.MfaAuth,
		&i.Ntf,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserTOTP = `-- name: InsertUserTOTP :one
INSERT INTO totp (key_encrypted, user_id)
VALUES ($1, $2)
RETURNING id, user_id, key, key_encrypted
`

type InsertUserTOTPParams struct {
	KeyEncrypted aesgcm.Ciphertext
	UserID       *int
}

func (q *Queries) InsertUserTOTP(ctx context.Context, arg InsertUserTOTPParams) (Totp, error) {
	row := q.db.QueryRow(ctx, insertUserTOTP, arg.KeyEncrypted, arg.UserID)
	var i Totp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.KeyEncrypted,
	)
	return i, err
}

const invalidateAllDeviceSessionsByServerID = `-- name: InvalidateAllDeviceSessionsByServerID :execrows
WITH t AS (
    SELECT d.id AS row_id
    FROM devices d
    JOIN adjacencies adj ON adj.device_id = d.id
    WHERE adj.server_id = $1
)
UPDATE devices
SET session_id='', updated_at=now()
FROM t
WHERE id = t.row_id
`

func (q *Queries) InvalidateAllDeviceSessionsByServerID(ctx context.Context, serverID int) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateAllDeviceSessionsByServerID, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const invalidateAllDeviceSessionsWithCert = `-- name: InvalidateAllDeviceSessionsWithCert :execrows
WITH t AS (
    SELECT d.id AS row_id
    FROM devices d
    JOIN device_templates dt ON d.device_template_id = dt.id
    JOIN users u ON dt.user_id = u.id
    WHERE u.mfa_auth = 'cert'
)
UPDATE devices
SET session_id='', updated_at=now()
FROM t
WHERE id = t.row_id
`

func (q *Queries) InvalidateAllDeviceSessionsWithCert(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateAllDeviceSessionsWithCert)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const invalidateDeviceSession = `-- name: InvalidateDeviceSession :one
UPDATE devices
SET session_id='', updated_at=now()
WHERE id=$1
RETURNING id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted
`

func (q *Queries) InvalidateDeviceSession(ctx context.Context, id int) (Device, error) {
	row := q.db.QueryRow(ctx, invalidateDeviceSession, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const invalidateOldDeviceSessions = `-- name: InvalidateOldDeviceSessions :execrows
UPDATE devices
SET session_id='', updated_at=now() 
WHERE last_time_connected < $1
`

func (q *Queries) InvalidateOldDeviceSessions(ctx context.Context, lastTimeConnected pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateOldDeviceSessions, lastTimeConnected)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const invalidateTemplateDeviceSessions = `-- name: InvalidateTemplateDeviceSessions :execrows
UPDATE devices
SET session_id='', updated_at=now()
WHERE device_template_id=$1
`

func (q *Queries) InvalidateTemplateDeviceSessions(ctx context.Context, deviceTemplateID int) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateTemplateDeviceSessions, deviceTemplateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isHealthCheckEnabledForDevice = `-- name: IsHealthCheckEnabledForDevice :one
SELECT EXISTS(
    SELECT 1 FROM adjacencies AS a
    JOIN servers AS s
        ON a.server_id=s.id
    WHERE a.device_id=$1
        AND s.healthcheck_address IS NOT NULL
    LIMIT 1
)
`

func (q *Queries) IsHealthCheckEnabledForDevice(ctx context.Context, deviceID int) (bool, error) {
	row := q.db.QueryRow(ctx, isHealthCheckEnabledForDevice, deviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ldapConfigVerifyPriority = `-- name: LdapConfigVerifyPriority :one
SELECT 1 FROM ldaps WHERE priority=$1
`

func (q *Queries) LdapConfigVerifyPriority(ctx context.Context, priority int) (int, error) {
	row := q.db.QueryRow(ctx, ldapConfigVerifyPriority, priority)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const ldapTemplateIDCheck = `-- name: LdapTemplateIDCheck :one
SELECT EXISTS(SELECT 1 FROM ldap_templates WHERE id=$1 LIMIT 1)
`

func (q *Queries) LdapTemplateIDCheck(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRow(ctx, ldapTemplateIDCheck, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ldapTemplateNameCheck = `-- name: LdapTemplateNameCheck :one
SELECT EXISTS(SELECT 1 FROM ldap_templates WHERE name=$1 LIMIT 1)
`

func (q *Queries) LdapTemplateNameCheck(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, ldapTemplateNameCheck, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const serverIDCheck = `-- name: ServerIDCheck :one
SELECT 1 FROM servers
WHERE id=$1
LIMIT 1
`

func (q *Queries) ServerIDCheck(ctx context.Context, id int) (int, error) {
	row := q.db.QueryRow(ctx, serverIDCheck, id)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const serverNameCheck = `-- name: ServerNameCheck :one
SELECT 1 FROM servers
WHERE name=$1
LIMIT 1
`

func (q *Queries) ServerNameCheck(ctx context.Context, name string) (int, error) {
	row := q.db.QueryRow(ctx, serverNameCheck, name)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAddressPool = `-- name: UpdateAddressPool :one
UPDATE address_pools
SET
    name = $2,
    description = $3,
    start_addr = $4,
    end_addr = $5,
    net_mask = $6,
    updated_at = $7
WHERE id = $1
RETURNING id, name, description, start_addr, end_addr, net_mask, created_at, updated_at
`

type UpdateAddressPoolParams struct {
	ID          int
	Name        string
	Description string
	StartAddr   netip.Addr
	EndAddr     netip.Addr
	NetMask     int
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) UpdateAddressPool(ctx context.Context, arg UpdateAddressPoolParams) (AddressPool, error) {
	row := q.db.QueryRow(ctx, updateAddressPool,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StartAddr,
		arg.EndAddr,
		arg.NetMask,
		arg.UpdatedAt,
	)
	var i AddressPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartAddr,
		&i.EndAddr,
		&i.NetMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdjacency = `-- name: UpdateAdjacency :one
UPDATE adjacencies
SET server_id=$2, device_id=$3, preshared_key_encrypted=$4,
    server_side_allowed_ips=COALESCE($5, server_side_allowed_ips),
    client_side_allowed_ips=$6
WHERE id=$1
RETURNING id, server_id, device_id, server_side_allowed_ips, client_side_allowed_ips, preshared_key, preshared_key_encrypted
`

type UpdateAdjacencyParams struct {
	ID                    int
	ServerID              int
	DeviceID              int
	PresharedKeyEncrypted aesgcm.Ciphertext
	ServerSideAllowedIps  []netip.Prefix
	ClientSideAllowedIps  []netip.Prefix
}

func (q *Queries) UpdateAdjacency(ctx context.Context, arg UpdateAdjacencyParams) (Adjacency, error) {
	row := q.db.QueryRow(ctx, updateAdjacency,
		arg.ID,
		arg.ServerID,
		arg.DeviceID,
		arg.PresharedKeyEncrypted,
		arg.ServerSideAllowedIps,
		arg.ClientSideAllowedIps,
	)
	var i Adjacency
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.DeviceID,
		&i.ServerSideAllowedIps,
		&i.ClientSideAllowedIps,
		&i.PresharedKey,
		&i.PresharedKeyEncrypted,
	)
	return i, err
}

const updateAdjacencyClientSideAllowedIPs = `-- name: UpdateAdjacencyClientSideAllowedIPs :exec
UPDATE adjacencies
SET client_side_allowed_ips=$2
WHERE id=$1
`

type UpdateAdjacencyClientSideAllowedIPsParams struct {
	ID                   int
	ClientSideAllowedIps []netip.Prefix
}

func (q *Queries) UpdateAdjacencyClientSideAllowedIPs(ctx context.Context, arg UpdateAdjacencyClientSideAllowedIPsParams) error {
	_, err := q.db.Exec(ctx, updateAdjacencyClientSideAllowedIPs, arg.ID, arg.ClientSideAllowedIps)
	return err
}

const updateAdjacencyTemplate = `-- name: UpdateAdjacencyTemplate :one
UPDATE adjacency_templates
SET server_id=$2, client_side_allowed_ips=$3, use_preshared_key=$4
WHERE id=$1
RETURNING id, server_id, user_id, client_side_allowed_ips, use_preshared_key
`

type UpdateAdjacencyTemplateParams struct {
	ID                   int
	ServerID             int
	ClientSideAllowedIps []netip.Prefix
	UsePresharedKey      bool
}

func (q *Queries) UpdateAdjacencyTemplate(ctx context.Context, arg UpdateAdjacencyTemplateParams) (AdjacencyTemplate, error) {
	row := q.db.QueryRow(ctx, updateAdjacencyTemplate,
		arg.ID,
		arg.ServerID,
		arg.ClientSideAllowedIps,
		arg.UsePresharedKey,
	)
	var i AdjacencyTemplate
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.ClientSideAllowedIps,
		&i.UsePresharedKey,
	)
	return i, err
}

const updateAdjacencyTemplateClientSideAllowedIPs = `-- name: UpdateAdjacencyTemplateClientSideAllowedIPs :exec
UPDATE adjacency_templates
SET client_side_allowed_ips=$2
WHERE id=$1
`

type UpdateAdjacencyTemplateClientSideAllowedIPsParams struct {
	ID                   int
	ClientSideAllowedIps []netip.Prefix
}

func (q *Queries) UpdateAdjacencyTemplateClientSideAllowedIPs(ctx context.Context, arg UpdateAdjacencyTemplateClientSideAllowedIPsParams) error {
	_, err := q.db.Exec(ctx, updateAdjacencyTemplateClientSideAllowedIPs, arg.ID, arg.ClientSideAllowedIps)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET description=$2, private_key_encrypted=$3, public_key=$4,
    updated_at=now()
WHERE id=$1
RETURNING id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted
`

type UpdateDeviceParams struct {
	ID                  int
	Description         string
	PrivateKeyEncrypted aesgcm.Ciphertext
	PublicKey           string
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Description,
		arg.PrivateKeyEncrypted,
		arg.PublicKey,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const updateDeviceFromConfiguration = `-- name: UpdateDeviceFromConfiguration :one
UPDATE devices
SET external_device_id=$2, session_id=$3, last_time_connected=$4, device_information=$5, updated_at=now()
WHERE id=$1
RETURNING id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted
`

type UpdateDeviceFromConfigurationParams struct {
	ID                int
	ExternalDeviceID  string
	SessionID         string
	LastTimeConnected pgtype.Timestamp
	DeviceInformation *string
}

func (q *Queries) UpdateDeviceFromConfiguration(ctx context.Context, arg UpdateDeviceFromConfigurationParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceFromConfiguration,
		arg.ID,
		arg.ExternalDeviceID,
		arg.SessionID,
		arg.LastTimeConnected,
		arg.DeviceInformation,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const updateDeviceSessionAndLastTimeConnected = `-- name: UpdateDeviceSessionAndLastTimeConnected :one
UPDATE devices
SET session_id=$2, last_time_connected=$3,
    updated_at=now()
WHERE id=$1
RETURNING id, description, device_template_id, private_key, public_key, external_device_id, session_id, last_time_connected, created_at, updated_at, device_information, private_key_encrypted
`

type UpdateDeviceSessionAndLastTimeConnectedParams struct {
	ID                int
	SessionID         string
	LastTimeConnected pgtype.Timestamp
}

func (q *Queries) UpdateDeviceSessionAndLastTimeConnected(ctx context.Context, arg UpdateDeviceSessionAndLastTimeConnectedParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceSessionAndLastTimeConnected, arg.ID, arg.SessionID, arg.LastTimeConnected)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DeviceTemplateID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ExternalDeviceID,
		&i.SessionID,
		&i.LastTimeConnected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceInformation,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const updateDeviceTemplateByUserID = `-- name: UpdateDeviceTemplateByUserID :one
UPDATE device_templates
SET interface_name=$2, listen_port=$3, mtu=$4
WHERE user_id=$1
RETURNING id, user_id, interface_name, listen_port, mtu, created_at, updated_at
`

type UpdateDeviceTemplateByUserIDParams struct {
	UserID        int
	InterfaceName string
	ListenPort    *int
	Mtu           *int
}

func (q *Queries) UpdateDeviceTemplateByUserID(ctx context.Context, arg UpdateDeviceTemplateByUserIDParams) (DeviceTemplate, error) {
	row := q.db.QueryRow(ctx, updateDeviceTemplateByUserID,
		arg.UserID,
		arg.InterfaceName,
		arg.ListenPort,
		arg.Mtu,
	)
	var i DeviceTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InterfaceName,
		&i.ListenPort,
		&i.Mtu,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLdapConfig = `-- name: UpdateLdapConfig :one
UPDATE ldaps
SET
    priority=$1, host=$2, port=$3, base_dn=$4,
    bind_dn=$5, bind_pw_encrypted=$6,
    user_list_filter=$7, username_attribute=$8, uid_attribute=$9,
    use_tls=$10, fqdn=$11, ca_cert=$12, template_id=$13
WHERE id=$14
RETURNING id, priority, host, port, base_dn, bind_dn, bind_pw, user_list_filter, username_attribute, uid_attribute, use_tls, fqdn, ca_cert, template_id, bind_pw_encrypted
`

type UpdateLdapConfigParams struct {
	Priority          int
	Host              string
	Port              int
	BaseDn            string
	BindDn            string
	BindPwEncrypted   aesgcm.Ciphertext
	UserListFilter    string
	UsernameAttribute string
	UidAttribute      string
	UseTls            bool
	Fqdn              string
	CaCert            []byte
	TemplateID        *int
	ID                string
}

func (q *Queries) UpdateLdapConfig(ctx context.Context, arg UpdateLdapConfigParams) (Ldap, error) {
	row := q.db.QueryRow(ctx, updateLdapConfig,
		arg.Priority,
		arg.Host,
		arg.Port,
		arg.BaseDn,
		arg.BindDn,
		arg.BindPwEncrypted,
		arg.UserListFilter,
		arg.UsernameAttribute,
		arg.UidAttribute,
		arg.UseTls,
		arg.Fqdn,
		arg.CaCert,
		arg.TemplateID,
		arg.ID,
	)
	var i Ldap
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Host,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindPw,
		&i.UserListFilter,
		&i.UsernameAttribute,
		&i.UidAttribute,
		&i.UseTls,
		&i.Fqdn,
		&i.CaCert,
		&i.TemplateID,
		&i.BindPwEncrypted,
	)
	return i, err
}

const updateLdapRelation = `-- name: UpdateLdapRelation :one
UPDATE users_to_ldaps
SET user_id=$1, user_dn=$2, updated_at=$3
WHERE id=$4
AND ldap_id=$5
AND user_uid=$6
RETURNING id, user_id, ldap_id, user_uid, user_dn, created_at, updated_at
`

type UpdateLdapRelationParams struct {
	UserID    *int
	UserDn    string
	UpdatedAt pgtype.Timestamp
	ID        int
	LdapID    pgtype.UUID
	UserUid   string
}

// struct_name: UsersToLdaps
func (q *Queries) UpdateLdapRelation(ctx context.Context, arg UpdateLdapRelationParams) (UsersToLdap, error) {
	row := q.db.QueryRow(ctx, updateLdapRelation,
		arg.UserID,
		arg.UserDn,
		arg.UpdatedAt,
		arg.ID,
		arg.LdapID,
		arg.UserUid,
	)
	var i UsersToLdap
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LdapID,
		&i.UserUid,
		&i.UserDn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLdapTemplate = `-- name: UpdateLdapTemplate :one
UPDATE ldap_templates
SET name=$1, filter=$2, interface_name=$3, is_admin=$4, mfa_auth=$5, listen_port=$6, mtu=$7, dns=$8
WHERE id=$9
RETURNING id, name, filter, interface_name, is_admin, mfa_auth, listen_port, mtu, dns
`

type UpdateLdapTemplateParams struct {
	Name          string
	Filter        *string
	InterfaceName string
	IsAdmin       bool
	MfaAuth       MfaAuthType
	ListenPort    *string
	Mtu           *string
	Dns           []string
	ID            int
}

func (q *Queries) UpdateLdapTemplate(ctx context.Context, arg UpdateLdapTemplateParams) (LdapTemplate, error) {
	row := q.db.QueryRow(ctx, updateLdapTemplate,
		arg.Name,
		arg.Filter,
		arg.InterfaceName,
		arg.IsAdmin,
		arg.MfaAuth,
		arg.ListenPort,
		arg.Mtu,
		arg.Dns,
		arg.ID,
	)
	var i LdapTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filter,
		&i.InterfaceName,
		&i.IsAdmin,
		&i.MfaAuth,
		&i.ListenPort,
		&i.Mtu,
		&i.Dns,
	)
	return i, err
}

const updateLdapTemplateServer = `-- name: UpdateLdapTemplateServer :one
UPDATE ldap_template_servers
SET server_id = $1,
allowed_ips = $2, use_preshared_key = $3
WHERE ldap_template_id = $4 AND server_id = $5
RETURNING id, ldap_template_id, server_id, allowed_ips, use_preshared_key
`

type UpdateLdapTemplateServerParams struct {
	ServerID        *int
	AllowedIps      []netip.Prefix
	UsePresharedKey bool
	LdapTemplateID  int
	ServerID_2      *int
}

func (q *Queries) UpdateLdapTemplateServer(ctx context.Context, arg UpdateLdapTemplateServerParams) (LdapTemplateServer, error) {
	row := q.db.QueryRow(ctx, updateLdapTemplateServer,
		arg.ServerID,
		arg.AllowedIps,
		arg.UsePresharedKey,
		arg.LdapTemplateID,
		arg.ServerID_2,
	)
	var i LdapTemplateServer
	err := row.Scan(
		&i.ID,
		&i.LdapTemplateID,
		&i.ServerID,
		&i.AllowedIps,
		&i.UsePresharedKey,
	)
	return i, err
}

const updateLdapTemplateServerAllowedIPs = `-- name: UpdateLdapTemplateServerAllowedIPs :exec
UPDATE ldap_template_servers
SET allowed_ips=$3
WHERE ldap_template_id=$1 AND server_id=$2
`

type UpdateLdapTemplateServerAllowedIPsParams struct {
	LdapTemplateID int
	ServerID       *int
	AllowedIps     []netip.Prefix
}

func (q *Queries) UpdateLdapTemplateServerAllowedIPs(ctx context.Context, arg UpdateLdapTemplateServerAllowedIPsParams) error {
	_, err := q.db.Exec(ctx, updateLdapTemplateServerAllowedIPs, arg.LdapTemplateID, arg.ServerID, arg.AllowedIps)
	return err
}

const updateServer = `-- name: UpdateServer :one
UPDATE servers SET name=$1, endpoint=$2, description=$3, healthcheck_address=$4
WHERE id=$5
RETURNING id, name, endpoint, description, running_replicas, healthcheck_address
`

type UpdateServerParams struct {
	Name               string
	Endpoint           netip.Addr
	Description        string
	HealthcheckAddress *netip.Addr
	ID                 int
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServer,
		arg.Name,
		arg.Endpoint,
		arg.Description,
		arg.HealthcheckAddress,
		arg.ID,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Description,
		&i.RunningReplicas,
		&i.HealthcheckAddress,
	)
	return i, err
}

const updateServerWireGuardConfig = `-- name: UpdateServerWireGuardConfig :one
UPDATE server_wg_configs
SET interface_name=$2, private_key_encrypted=$3, public_key=$4, listen_port=$5, mtu=$6, persistent_keepalive=$7
WHERE server_id=$1
RETURNING id, server_id, interface_name, private_key, public_key, listen_port, mtu, persistent_keepalive, private_key_encrypted
`

type UpdateServerWireGuardConfigParams struct {
	ServerID            int
	InterfaceName       string
	PrivateKeyEncrypted aesgcm.Ciphertext
	PublicKey           string
	ListenPort          *int
	Mtu                 *int
	PersistentKeepalive *int
}

func (q *Queries) UpdateServerWireGuardConfig(ctx context.Context, arg UpdateServerWireGuardConfigParams) (ServerWgConfig, error) {
	row := q.db.QueryRow(ctx, updateServerWireGuardConfig,
		arg.ServerID,
		arg.InterfaceName,
		arg.PrivateKeyEncrypted,
		arg.PublicKey,
		arg.ListenPort,
		arg.Mtu,
		arg.PersistentKeepalive,
	)
	var i ServerWgConfig
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.InterfaceName,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ListenPort,
		&i.Mtu,
		&i.PersistentKeepalive,
		&i.PrivateKeyEncrypted,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username=$1, is_admin=$2, mfa_auth=$3, ntf=$4, updated_at=$5 
WHERE id=$6
RETURNING id, username, password, is_admin, auth_service, mfa_auth, ntf, updated_at
`

type UpdateUserParams struct {
	Username  string
	IsAdmin   bool
	MfaAuth   MfaAuthType
	Ntf       string
	UpdatedAt pgtype.Timestamp
	ID        int
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.IsAdmin,
		arg.MfaAuth,
		arg.Ntf,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsAdmin,
		&i.AuthService,
		&i.MfaAuth,
		&i.Ntf,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEditTime = `-- name: UpdateUserEditTime :one
UPDATE users
SET updated_at=$1
WHERE id=$2
RETURNING id, username, password, is_admin, auth_service, mfa_auth, ntf, updated_at
`

type UpdateUserEditTimeParams struct {
	UpdatedAt pgtype.Timestamp
	ID        int
}

func (q *Queries) UpdateUserEditTime(ctx context.Context, arg UpdateUserEditTimeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEditTime, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsAdmin,
		&i.AuthService,
		&i.MfaAuth,
		&i.Ntf,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPwd = `-- name: UpdateUserPwd :one
UPDATE users
SET password=$1, updated_at=$2
WHERE id=$3
RETURNING id, username, password, is_admin, auth_service, mfa_auth, ntf, updated_at
`

type UpdateUserPwdParams struct {
	Password  string
	UpdatedAt pgtype.Timestamp
	ID        int
}

func (q *Queries) UpdateUserPwd(ctx context.Context, arg UpdateUserPwdParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPwd, arg.Password, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsAdmin,
		&i.AuthService,
		&i.MfaAuth,
		&i.Ntf,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTOTP = `-- name: UpdateUserTOTP :one
UPDATE totp
SET key_encrypted=$1
WHERE user_id=$2
RETURNING id, user_id, key, key_encrypted
`

type UpdateUserTOTPParams struct {
	KeyEncrypted aesgcm.Ciphertext
	UserID       *int
}

func (q *Queries) UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) (Totp, error) {
	row := q.db.QueryRow(ctx, updateUserTOTP, arg.KeyEncrypted, arg.UserID)
	var i Totp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.KeyEncrypted,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id=$1 LIMIT 1)
`

func (q *Queries) UserExists(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userIDCheck = `-- name: UserIDCheck :one
SELECT 1 FROM users
WHERE id=$1
LIMIT 1
`

func (q *Queries) UserIDCheck(ctx context.Context, id int) (int, error) {
	row := q.db.QueryRow(ctx, userIDCheck, id)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const usernameCheck = `-- name: UsernameCheck :one
SELECT 1 FROM users
WHERE username=$1
LIMIT 1
`

func (q *Queries) UsernameCheck(ctx context.Context, username string) (int, error) {
	row := q.db.QueryRow(ctx, usernameCheck, username)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}
