// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/v2/healthcheck_client.proto

package pbapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthcheckPingResponse_Status int32

const (
	HealthcheckPingResponse_STATUS_UNDEFINED_UNSPECIFIED    HealthcheckPingResponse_Status = 0
	HealthcheckPingResponse_STATUS_VALID_SESSION            HealthcheckPingResponse_Status = 1
	HealthcheckPingResponse_STATUS_INVALID_SESSION          HealthcheckPingResponse_Status = 2
	HealthcheckPingResponse_STATUS_NOT_INITIALIZED_SESSIONS HealthcheckPingResponse_Status = 3
)

// Enum value maps for HealthcheckPingResponse_Status.
var (
	HealthcheckPingResponse_Status_name = map[int32]string{
		0: "STATUS_UNDEFINED_UNSPECIFIED",
		1: "STATUS_VALID_SESSION",
		2: "STATUS_INVALID_SESSION",
		3: "STATUS_NOT_INITIALIZED_SESSIONS",
	}
	HealthcheckPingResponse_Status_value = map[string]int32{
		"STATUS_UNDEFINED_UNSPECIFIED":    0,
		"STATUS_VALID_SESSION":            1,
		"STATUS_INVALID_SESSION":          2,
		"STATUS_NOT_INITIALIZED_SESSIONS": 3,
	}
)

func (x HealthcheckPingResponse_Status) Enum() *HealthcheckPingResponse_Status {
	p := new(HealthcheckPingResponse_Status)
	*p = x
	return p
}

func (x HealthcheckPingResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthcheckPingResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_healthcheck_client_proto_enumTypes[0].Descriptor()
}

func (HealthcheckPingResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_v2_healthcheck_client_proto_enumTypes[0]
}

func (x HealthcheckPingResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthcheckPingResponse_Status.Descriptor instead.
func (HealthcheckPingResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_client_proto_rawDescGZIP(), []int{1, 0}
}

type HealthcheckPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *HealthcheckPingRequest) Reset() {
	*x = HealthcheckPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_healthcheck_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthcheckPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckPingRequest) ProtoMessage() {}

func (x *HealthcheckPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_healthcheck_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckPingRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckPingRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_client_proto_rawDescGZIP(), []int{0}
}

func (x *HealthcheckPingRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type HealthcheckPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status HealthcheckPingResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.v2.HealthcheckPingResponse_Status" json:"status,omitempty"`
}

func (x *HealthcheckPingResponse) Reset() {
	*x = HealthcheckPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_healthcheck_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthcheckPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckPingResponse) ProtoMessage() {}

func (x *HealthcheckPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_healthcheck_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckPingResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckPingResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_client_proto_rawDescGZIP(), []int{1}
}

func (x *HealthcheckPingResponse) GetStatus() HealthcheckPingResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthcheckPingResponse_STATUS_UNDEFINED_UNSPECIFIED
}

var File_proto_v2_healthcheck_client_proto protoreflect.FileDescriptor

var file_proto_v2_healthcheck_client_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x22, 0x32, 0x0a,
	0x16, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0xe3, 0x01, 0x0a, 0x17, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x85, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x1c, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x53, 0x45, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e,
	0x10, 0x02, 0x12, 0x23, 0x0a, 0x1f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x45, 0x44, 0x5f, 0x53, 0x45, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x03, 0x32, 0x74, 0x0a, 0x18, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76,
	0x32, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x76, 0x32, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x74, 0x67,
	0x75, 0x61, 0x72, 0x64, 0x2f, 0x65, 0x6e, 0x74, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x3b, 0x70, 0x62, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v2_healthcheck_client_proto_rawDescOnce sync.Once
	file_proto_v2_healthcheck_client_proto_rawDescData = file_proto_v2_healthcheck_client_proto_rawDesc
)

func file_proto_v2_healthcheck_client_proto_rawDescGZIP() []byte {
	file_proto_v2_healthcheck_client_proto_rawDescOnce.Do(func() {
		file_proto_v2_healthcheck_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v2_healthcheck_client_proto_rawDescData)
	})
	return file_proto_v2_healthcheck_client_proto_rawDescData
}

var file_proto_v2_healthcheck_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v2_healthcheck_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v2_healthcheck_client_proto_goTypes = []any{
	(HealthcheckPingResponse_Status)(0), // 0: proto.v2.HealthcheckPingResponse.Status
	(*HealthcheckPingRequest)(nil),      // 1: proto.v2.HealthcheckPingRequest
	(*HealthcheckPingResponse)(nil),     // 2: proto.v2.HealthcheckPingResponse
}
var file_proto_v2_healthcheck_client_proto_depIdxs = []int32{
	0, // 0: proto.v2.HealthcheckPingResponse.status:type_name -> proto.v2.HealthcheckPingResponse.Status
	1, // 1: proto.v2.HealthcheckClientService.HealthcheckPing:input_type -> proto.v2.HealthcheckPingRequest
	2, // 2: proto.v2.HealthcheckClientService.HealthcheckPing:output_type -> proto.v2.HealthcheckPingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v2_healthcheck_client_proto_init() }
func file_proto_v2_healthcheck_client_proto_init() {
	if File_proto_v2_healthcheck_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v2_healthcheck_client_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HealthcheckPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_healthcheck_client_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HealthcheckPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v2_healthcheck_client_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v2_healthcheck_client_proto_goTypes,
		DependencyIndexes: file_proto_v2_healthcheck_client_proto_depIdxs,
		EnumInfos:         file_proto_v2_healthcheck_client_proto_enumTypes,
		MessageInfos:      file_proto_v2_healthcheck_client_proto_msgTypes,
	}.Build()
	File_proto_v2_healthcheck_client_proto = out.File
	file_proto_v2_healthcheck_client_proto_rawDesc = nil
	file_proto_v2_healthcheck_client_proto_goTypes = nil
	file_proto_v2_healthcheck_client_proto_depIdxs = nil
}
