// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/v2/healthcheck_client.proto

package pbapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthcheckClientService_HealthcheckPing_FullMethodName = "/proto.v2.HealthcheckClientService/HealthcheckPing"
)

// HealthcheckClientServiceClient is the client API for HealthcheckClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthcheckClientServiceClient interface {
	HealthcheckPing(ctx context.Context, in *HealthcheckPingRequest, opts ...grpc.CallOption) (*HealthcheckPingResponse, error)
}

type healthcheckClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthcheckClientServiceClient(cc grpc.ClientConnInterface) HealthcheckClientServiceClient {
	return &healthcheckClientServiceClient{cc}
}

func (c *healthcheckClientServiceClient) HealthcheckPing(ctx context.Context, in *HealthcheckPingRequest, opts ...grpc.CallOption) (*HealthcheckPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthcheckPingResponse)
	err := c.cc.Invoke(ctx, HealthcheckClientService_HealthcheckPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthcheckClientServiceServer is the server API for HealthcheckClientService service.
// All implementations must embed UnimplementedHealthcheckClientServiceServer
// for forward compatibility.
type HealthcheckClientServiceServer interface {
	HealthcheckPing(context.Context, *HealthcheckPingRequest) (*HealthcheckPingResponse, error)
	mustEmbedUnimplementedHealthcheckClientServiceServer()
}

// UnimplementedHealthcheckClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthcheckClientServiceServer struct{}

func (UnimplementedHealthcheckClientServiceServer) HealthcheckPing(context.Context, *HealthcheckPingRequest) (*HealthcheckPingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthcheckPing not implemented")
}
func (UnimplementedHealthcheckClientServiceServer) mustEmbedUnimplementedHealthcheckClientServiceServer() {
}
func (UnimplementedHealthcheckClientServiceServer) testEmbeddedByValue() {}

// UnsafeHealthcheckClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthcheckClientServiceServer will
// result in compilation errors.
type UnsafeHealthcheckClientServiceServer interface {
	mustEmbedUnimplementedHealthcheckClientServiceServer()
}

func RegisterHealthcheckClientServiceServer(s grpc.ServiceRegistrar, srv HealthcheckClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedHealthcheckClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthcheckClientService_ServiceDesc, srv)
}

func _HealthcheckClientService_HealthcheckPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthcheckClientServiceServer).HealthcheckPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthcheckClientService_HealthcheckPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthcheckClientServiceServer).HealthcheckPing(ctx, req.(*HealthcheckPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthcheckClientService_ServiceDesc is the grpc.ServiceDesc for HealthcheckClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthcheckClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v2.HealthcheckClientService",
	HandlerType: (*HealthcheckClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthcheckPing",
			Handler:    _HealthcheckClientService_HealthcheckPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v2/healthcheck_client.proto",
}
