// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/v2/healthcheck_orchestrator.proto

package pbapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthcheckOrchestratorService_GetAllSessions_FullMethodName              = "/proto.v2.HealthcheckOrchestratorService/GetAllSessions"
	HealthcheckOrchestratorService_SubscribeForSessionsUpdates_FullMethodName = "/proto.v2.HealthcheckOrchestratorService/SubscribeForSessionsUpdates"
)

// HealthcheckOrchestratorServiceClient is the client API for HealthcheckOrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthcheckOrchestratorServiceClient interface {
	GetAllSessions(ctx context.Context, in *GetAllSessionsRequest, opts ...grpc.CallOption) (*GetAllSessionsResponse, error)
	SubscribeForSessionsUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse], error)
}

type healthcheckOrchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthcheckOrchestratorServiceClient(cc grpc.ClientConnInterface) HealthcheckOrchestratorServiceClient {
	return &healthcheckOrchestratorServiceClient{cc}
}

func (c *healthcheckOrchestratorServiceClient) GetAllSessions(ctx context.Context, in *GetAllSessionsRequest, opts ...grpc.CallOption) (*GetAllSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSessionsResponse)
	err := c.cc.Invoke(ctx, HealthcheckOrchestratorService_GetAllSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthcheckOrchestratorServiceClient) SubscribeForSessionsUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthcheckOrchestratorService_ServiceDesc.Streams[0], HealthcheckOrchestratorService_SubscribeForSessionsUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthcheckOrchestratorService_SubscribeForSessionsUpdatesClient = grpc.BidiStreamingClient[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse]

// HealthcheckOrchestratorServiceServer is the server API for HealthcheckOrchestratorService service.
// All implementations must embed UnimplementedHealthcheckOrchestratorServiceServer
// for forward compatibility.
type HealthcheckOrchestratorServiceServer interface {
	GetAllSessions(context.Context, *GetAllSessionsRequest) (*GetAllSessionsResponse, error)
	SubscribeForSessionsUpdates(grpc.BidiStreamingServer[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse]) error
	mustEmbedUnimplementedHealthcheckOrchestratorServiceServer()
}

// UnimplementedHealthcheckOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthcheckOrchestratorServiceServer struct{}

func (UnimplementedHealthcheckOrchestratorServiceServer) GetAllSessions(context.Context, *GetAllSessionsRequest) (*GetAllSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSessions not implemented")
}
func (UnimplementedHealthcheckOrchestratorServiceServer) SubscribeForSessionsUpdates(grpc.BidiStreamingServer[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeForSessionsUpdates not implemented")
}
func (UnimplementedHealthcheckOrchestratorServiceServer) mustEmbedUnimplementedHealthcheckOrchestratorServiceServer() {
}
func (UnimplementedHealthcheckOrchestratorServiceServer) testEmbeddedByValue() {}

// UnsafeHealthcheckOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthcheckOrchestratorServiceServer will
// result in compilation errors.
type UnsafeHealthcheckOrchestratorServiceServer interface {
	mustEmbedUnimplementedHealthcheckOrchestratorServiceServer()
}

func RegisterHealthcheckOrchestratorServiceServer(s grpc.ServiceRegistrar, srv HealthcheckOrchestratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedHealthcheckOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthcheckOrchestratorService_ServiceDesc, srv)
}

func _HealthcheckOrchestratorService_GetAllSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthcheckOrchestratorServiceServer).GetAllSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthcheckOrchestratorService_GetAllSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthcheckOrchestratorServiceServer).GetAllSessions(ctx, req.(*GetAllSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthcheckOrchestratorService_SubscribeForSessionsUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthcheckOrchestratorServiceServer).SubscribeForSessionsUpdates(&grpc.GenericServerStream[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthcheckOrchestratorService_SubscribeForSessionsUpdatesServer = grpc.BidiStreamingServer[SubscribeForSessionsUpdatesRequest, SubscribeForSessionsUpdatesResponse]

// HealthcheckOrchestratorService_ServiceDesc is the grpc.ServiceDesc for HealthcheckOrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthcheckOrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v2.HealthcheckOrchestratorService",
	HandlerType: (*HealthcheckOrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllSessions",
			Handler:    _HealthcheckOrchestratorService_GetAllSessions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeForSessionsUpdates",
			Handler:       _HealthcheckOrchestratorService_SubscribeForSessionsUpdates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v2/healthcheck_orchestrator.proto",
}
