// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/v2/healthcheck_orchestrator.proto

package pbapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeForSessionsUpdatesResponse_Operation int32

const (
	SubscribeForSessionsUpdatesResponse_OPERATION_UNDEFINED_UNSPECIFIED SubscribeForSessionsUpdatesResponse_Operation = 0
	SubscribeForSessionsUpdatesResponse_OPERATION_ADD_SESSION           SubscribeForSessionsUpdatesResponse_Operation = 1
	SubscribeForSessionsUpdatesResponse_OPERATION_DELETE_SESSION        SubscribeForSessionsUpdatesResponse_Operation = 2
)

// Enum value maps for SubscribeForSessionsUpdatesResponse_Operation.
var (
	SubscribeForSessionsUpdatesResponse_Operation_name = map[int32]string{
		0: "OPERATION_UNDEFINED_UNSPECIFIED",
		1: "OPERATION_ADD_SESSION",
		2: "OPERATION_DELETE_SESSION",
	}
	SubscribeForSessionsUpdatesResponse_Operation_value = map[string]int32{
		"OPERATION_UNDEFINED_UNSPECIFIED": 0,
		"OPERATION_ADD_SESSION":           1,
		"OPERATION_DELETE_SESSION":        2,
	}
)

func (x SubscribeForSessionsUpdatesResponse_Operation) Enum() *SubscribeForSessionsUpdatesResponse_Operation {
	p := new(SubscribeForSessionsUpdatesResponse_Operation)
	*p = x
	return p
}

func (x SubscribeForSessionsUpdatesResponse_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeForSessionsUpdatesResponse_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_healthcheck_orchestrator_proto_enumTypes[0].Descriptor()
}

func (SubscribeForSessionsUpdatesResponse_Operation) Type() protoreflect.EnumType {
	return &file_proto_v2_healthcheck_orchestrator_proto_enumTypes[0]
}

func (x SubscribeForSessionsUpdatesResponse_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeForSessionsUpdatesResponse_Operation.Descriptor instead.
func (SubscribeForSessionsUpdatesResponse_Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_orchestrator_proto_rawDescGZIP(), []int{2, 0}
}

type GetAllSessionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sessions []string `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
}

func (x *GetAllSessionsResponse) Reset() {
	*x = GetAllSessionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSessionsResponse) ProtoMessage() {}

func (x *GetAllSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllSessionsResponse) GetSessions() []string {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SubscribeForSessionsUpdatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SubscribeForSessionsUpdatesRequest_Subscribe
	//	*SubscribeForSessionsUpdatesRequest_Response
	Data isSubscribeForSessionsUpdatesRequest_Data `protobuf_oneof:"data"`
}

func (x *SubscribeForSessionsUpdatesRequest) Reset() {
	*x = SubscribeForSessionsUpdatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeForSessionsUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeForSessionsUpdatesRequest) ProtoMessage() {}

func (x *SubscribeForSessionsUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeForSessionsUpdatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeForSessionsUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (m *SubscribeForSessionsUpdatesRequest) GetData() isSubscribeForSessionsUpdatesRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SubscribeForSessionsUpdatesRequest) GetSubscribe() *Subscribe {
	if x, ok := x.GetData().(*SubscribeForSessionsUpdatesRequest_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (x *SubscribeForSessionsUpdatesRequest) GetResponse() *RPCStatus {
	if x, ok := x.GetData().(*SubscribeForSessionsUpdatesRequest_Response); ok {
		return x.Response
	}
	return nil
}

type isSubscribeForSessionsUpdatesRequest_Data interface {
	isSubscribeForSessionsUpdatesRequest_Data()
}

type SubscribeForSessionsUpdatesRequest_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type SubscribeForSessionsUpdatesRequest_Response struct {
	Response *RPCStatus `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*SubscribeForSessionsUpdatesRequest_Subscribe) isSubscribeForSessionsUpdatesRequest_Data() {}

func (*SubscribeForSessionsUpdatesRequest_Response) isSubscribeForSessionsUpdatesRequest_Data() {}

type SubscribeForSessionsUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation SubscribeForSessionsUpdatesResponse_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.v2.SubscribeForSessionsUpdatesResponse_Operation" json:"operation,omitempty"`
	Session   string                                        `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *SubscribeForSessionsUpdatesResponse) Reset() {
	*x = SubscribeForSessionsUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeForSessionsUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeForSessionsUpdatesResponse) ProtoMessage() {}

func (x *SubscribeForSessionsUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeForSessionsUpdatesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeForSessionsUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeForSessionsUpdatesResponse) GetOperation() SubscribeForSessionsUpdatesResponse_Operation {
	if x != nil {
		return x.Operation
	}
	return SubscribeForSessionsUpdatesResponse_OPERATION_UNDEFINED_UNSPECIFIED
}

func (x *SubscribeForSessionsUpdatesResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type GetAllSessionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllSessionsRequest) Reset() {
	*x = GetAllSessionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSessionsRequest) ProtoMessage() {}

func (x *GetAllSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_healthcheck_orchestrator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_healthcheck_orchestrator_proto_rawDescGZIP(), []int{3}
}

var File_proto_v2_healthcheck_orchestrator_proto protoreflect.FileDescriptor

var file_proto_v2_healthcheck_orchestrator_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x76, 0x32, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x94, 0x01, 0x0a, 0x22, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x6f,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x31, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x50, 0x43, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x81, 0x02, 0x0a, 0x23, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x55, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x69, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a,
	0x1f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46,
	0x49, 0x4e, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x41, 0x44, 0x44, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x1c, 0x0a,
	0x18, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x22, 0x17, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x32, 0xfa, 0x01, 0x0a, 0x1e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x80,
	0x01, 0x0a, 0x1b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x6f, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x46, 0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x46, 0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x6e, 0x74, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2f, 0x65, 0x6e, 0x74, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x3b, 0x70, 0x62, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v2_healthcheck_orchestrator_proto_rawDescOnce sync.Once
	file_proto_v2_healthcheck_orchestrator_proto_rawDescData = file_proto_v2_healthcheck_orchestrator_proto_rawDesc
)

func file_proto_v2_healthcheck_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_v2_healthcheck_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_v2_healthcheck_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v2_healthcheck_orchestrator_proto_rawDescData)
	})
	return file_proto_v2_healthcheck_orchestrator_proto_rawDescData
}

var file_proto_v2_healthcheck_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v2_healthcheck_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v2_healthcheck_orchestrator_proto_goTypes = []any{
	(SubscribeForSessionsUpdatesResponse_Operation)(0), // 0: proto.v2.SubscribeForSessionsUpdatesResponse.Operation
	(*GetAllSessionsResponse)(nil),                     // 1: proto.v2.GetAllSessionsResponse
	(*SubscribeForSessionsUpdatesRequest)(nil),         // 2: proto.v2.SubscribeForSessionsUpdatesRequest
	(*SubscribeForSessionsUpdatesResponse)(nil),        // 3: proto.v2.SubscribeForSessionsUpdatesResponse
	(*GetAllSessionsRequest)(nil),                      // 4: proto.v2.GetAllSessionsRequest
	(*Subscribe)(nil),                                  // 5: proto.v2.Subscribe
	(*RPCStatus)(nil),                                  // 6: proto.v2.RPCStatus
}
var file_proto_v2_healthcheck_orchestrator_proto_depIdxs = []int32{
	5, // 0: proto.v2.SubscribeForSessionsUpdatesRequest.subscribe:type_name -> proto.v2.Subscribe
	6, // 1: proto.v2.SubscribeForSessionsUpdatesRequest.response:type_name -> proto.v2.RPCStatus
	0, // 2: proto.v2.SubscribeForSessionsUpdatesResponse.operation:type_name -> proto.v2.SubscribeForSessionsUpdatesResponse.Operation
	4, // 3: proto.v2.HealthcheckOrchestratorService.GetAllSessions:input_type -> proto.v2.GetAllSessionsRequest
	2, // 4: proto.v2.HealthcheckOrchestratorService.SubscribeForSessionsUpdates:input_type -> proto.v2.SubscribeForSessionsUpdatesRequest
	1, // 5: proto.v2.HealthcheckOrchestratorService.GetAllSessions:output_type -> proto.v2.GetAllSessionsResponse
	3, // 6: proto.v2.HealthcheckOrchestratorService.SubscribeForSessionsUpdates:output_type -> proto.v2.SubscribeForSessionsUpdatesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v2_healthcheck_orchestrator_proto_init() }
func file_proto_v2_healthcheck_orchestrator_proto_init() {
	if File_proto_v2_healthcheck_orchestrator_proto != nil {
		return
	}
	file_proto_v2_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_v2_healthcheck_orchestrator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllSessionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_healthcheck_orchestrator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeForSessionsUpdatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_healthcheck_orchestrator_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeForSessionsUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_healthcheck_orchestrator_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllSessionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_v2_healthcheck_orchestrator_proto_msgTypes[1].OneofWrappers = []any{
		(*SubscribeForSessionsUpdatesRequest_Subscribe)(nil),
		(*SubscribeForSessionsUpdatesRequest_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v2_healthcheck_orchestrator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v2_healthcheck_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_v2_healthcheck_orchestrator_proto_depIdxs,
		EnumInfos:         file_proto_v2_healthcheck_orchestrator_proto_enumTypes,
		MessageInfos:      file_proto_v2_healthcheck_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_v2_healthcheck_orchestrator_proto = out.File
	file_proto_v2_healthcheck_orchestrator_proto_rawDesc = nil
	file_proto_v2_healthcheck_orchestrator_proto_goTypes = nil
	file_proto_v2_healthcheck_orchestrator_proto_depIdxs = nil
}
