// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/v2/vpncfg.proto

package pbapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VpnServerService_GetConfiguration_FullMethodName = "/proto.v2.VpnServerService/GetConfiguration"
	VpnServerService_SubscribeWG_FullMethodName      = "/proto.v2.VpnServerService/SubscribeWG"
	VpnServerService_SendTelemetry_FullMethodName    = "/proto.v2.VpnServerService/SendTelemetry"
)

// VpnServerServiceClient is the client API for VpnServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnServerServiceClient interface {
	GetConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	SubscribeWG(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeWGRequest, SubscribeWGResponse], error)
	SendTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendTelemetryRequest, emptypb.Empty], error)
}

type vpnServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnServerServiceClient(cc grpc.ClientConnInterface) VpnServerServiceClient {
	return &vpnServerServiceClient{cc}
}

func (c *vpnServerServiceClient) GetConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, VpnServerService_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServerServiceClient) SubscribeWG(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeWGRequest, SubscribeWGResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VpnServerService_ServiceDesc.Streams[0], VpnServerService_SubscribeWG_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeWGRequest, SubscribeWGResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnServerService_SubscribeWGClient = grpc.BidiStreamingClient[SubscribeWGRequest, SubscribeWGResponse]

func (c *vpnServerServiceClient) SendTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendTelemetryRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VpnServerService_ServiceDesc.Streams[1], VpnServerService_SendTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendTelemetryRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnServerService_SendTelemetryClient = grpc.ClientStreamingClient[SendTelemetryRequest, emptypb.Empty]

// VpnServerServiceServer is the server API for VpnServerService service.
// All implementations must embed UnimplementedVpnServerServiceServer
// for forward compatibility.
type VpnServerServiceServer interface {
	GetConfiguration(context.Context, *emptypb.Empty) (*GetConfigurationResponse, error)
	SubscribeWG(grpc.BidiStreamingServer[SubscribeWGRequest, SubscribeWGResponse]) error
	SendTelemetry(grpc.ClientStreamingServer[SendTelemetryRequest, emptypb.Empty]) error
	mustEmbedUnimplementedVpnServerServiceServer()
}

// UnimplementedVpnServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnServerServiceServer struct{}

func (UnimplementedVpnServerServiceServer) GetConfiguration(context.Context, *emptypb.Empty) (*GetConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedVpnServerServiceServer) SubscribeWG(grpc.BidiStreamingServer[SubscribeWGRequest, SubscribeWGResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeWG not implemented")
}
func (UnimplementedVpnServerServiceServer) SendTelemetry(grpc.ClientStreamingServer[SendTelemetryRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method SendTelemetry not implemented")
}
func (UnimplementedVpnServerServiceServer) mustEmbedUnimplementedVpnServerServiceServer() {}
func (UnimplementedVpnServerServiceServer) testEmbeddedByValue()                          {}

// UnsafeVpnServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnServerServiceServer will
// result in compilation errors.
type UnsafeVpnServerServiceServer interface {
	mustEmbedUnimplementedVpnServerServiceServer()
}

func RegisterVpnServerServiceServer(s grpc.ServiceRegistrar, srv VpnServerServiceServer) {
	// If the following call pancis, it indicates UnimplementedVpnServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VpnServerService_ServiceDesc, srv)
}

func _VpnServerService_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServerServiceServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnServerService_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServerServiceServer).GetConfiguration(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnServerService_SubscribeWG_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VpnServerServiceServer).SubscribeWG(&grpc.GenericServerStream[SubscribeWGRequest, SubscribeWGResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnServerService_SubscribeWGServer = grpc.BidiStreamingServer[SubscribeWGRequest, SubscribeWGResponse]

func _VpnServerService_SendTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VpnServerServiceServer).SendTelemetry(&grpc.GenericServerStream[SendTelemetryRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnServerService_SendTelemetryServer = grpc.ClientStreamingServer[SendTelemetryRequest, emptypb.Empty]

// VpnServerService_ServiceDesc is the grpc.ServiceDesc for VpnServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v2.VpnServerService",
	HandlerType: (*VpnServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _VpnServerService_GetConfiguration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeWG",
			Handler:       _VpnServerService_SubscribeWG_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendTelemetry",
			Handler:       _VpnServerService_SendTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v2/vpncfg.proto",
}

const (
	VpnClientService_GetConfiguration_FullMethodName = "/proto.v2.VpnClientService/GetConfiguration"
)

// VpnClientServiceClient is the client API for VpnClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnClientServiceClient interface {
	GetConfiguration(ctx context.Context, in *VpnClientServiceGetConfigurationRequest, opts ...grpc.CallOption) (*VpnClientServiceGetConfigurationResponse, error)
}

type vpnClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnClientServiceClient(cc grpc.ClientConnInterface) VpnClientServiceClient {
	return &vpnClientServiceClient{cc}
}

func (c *vpnClientServiceClient) GetConfiguration(ctx context.Context, in *VpnClientServiceGetConfigurationRequest, opts ...grpc.CallOption) (*VpnClientServiceGetConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpnClientServiceGetConfigurationResponse)
	err := c.cc.Invoke(ctx, VpnClientService_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnClientServiceServer is the server API for VpnClientService service.
// All implementations must embed UnimplementedVpnClientServiceServer
// for forward compatibility.
type VpnClientServiceServer interface {
	GetConfiguration(context.Context, *VpnClientServiceGetConfigurationRequest) (*VpnClientServiceGetConfigurationResponse, error)
	mustEmbedUnimplementedVpnClientServiceServer()
}

// UnimplementedVpnClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnClientServiceServer struct{}

func (UnimplementedVpnClientServiceServer) GetConfiguration(context.Context, *VpnClientServiceGetConfigurationRequest) (*VpnClientServiceGetConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedVpnClientServiceServer) mustEmbedUnimplementedVpnClientServiceServer() {}
func (UnimplementedVpnClientServiceServer) testEmbeddedByValue()                          {}

// UnsafeVpnClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnClientServiceServer will
// result in compilation errors.
type UnsafeVpnClientServiceServer interface {
	mustEmbedUnimplementedVpnClientServiceServer()
}

func RegisterVpnClientServiceServer(s grpc.ServiceRegistrar, srv VpnClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedVpnClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VpnClientService_ServiceDesc, srv)
}

func _VpnClientService_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnClientServiceGetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnClientServiceServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnClientService_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnClientServiceServer).GetConfiguration(ctx, req.(*VpnClientServiceGetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VpnClientService_ServiceDesc is the grpc.ServiceDesc for VpnClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v2.VpnClientService",
	HandlerType: (*VpnClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _VpnClientService_GetConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v2/vpncfg.proto",
}
