// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/v2/vpncfg.proto

package pbapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigurationResponse_Type int32

const (
	GetConfigurationResponse_TYPE_UNDEFINED_UNSPECIFIED GetConfigurationResponse_Type = 0
	GetConfigurationResponse_TYPE_WIREGUARD             GetConfigurationResponse_Type = 1
)

// Enum value maps for GetConfigurationResponse_Type.
var (
	GetConfigurationResponse_Type_name = map[int32]string{
		0: "TYPE_UNDEFINED_UNSPECIFIED",
		1: "TYPE_WIREGUARD",
	}
	GetConfigurationResponse_Type_value = map[string]int32{
		"TYPE_UNDEFINED_UNSPECIFIED": 0,
		"TYPE_WIREGUARD":             1,
	}
)

func (x GetConfigurationResponse_Type) Enum() *GetConfigurationResponse_Type {
	p := new(GetConfigurationResponse_Type)
	*p = x
	return p
}

func (x GetConfigurationResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetConfigurationResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_vpncfg_proto_enumTypes[0].Descriptor()
}

func (GetConfigurationResponse_Type) Type() protoreflect.EnumType {
	return &file_proto_v2_vpncfg_proto_enumTypes[0]
}

func (x GetConfigurationResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetConfigurationResponse_Type.Descriptor instead.
func (GetConfigurationResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{1, 0}
}

type WireGuardPeerNotification_Operation int32

const (
	WireGuardPeerNotification_OPERATION_UNDEFINED_UNSPECIFIED WireGuardPeerNotification_Operation = 0
	WireGuardPeerNotification_OPERATION_ADD_PEER              WireGuardPeerNotification_Operation = 1
	WireGuardPeerNotification_OPERATION_DEL_PEER              WireGuardPeerNotification_Operation = 2
)

// Enum value maps for WireGuardPeerNotification_Operation.
var (
	WireGuardPeerNotification_Operation_name = map[int32]string{
		0: "OPERATION_UNDEFINED_UNSPECIFIED",
		1: "OPERATION_ADD_PEER",
		2: "OPERATION_DEL_PEER",
	}
	WireGuardPeerNotification_Operation_value = map[string]int32{
		"OPERATION_UNDEFINED_UNSPECIFIED": 0,
		"OPERATION_ADD_PEER":              1,
		"OPERATION_DEL_PEER":              2,
	}
)

func (x WireGuardPeerNotification_Operation) Enum() *WireGuardPeerNotification_Operation {
	p := new(WireGuardPeerNotification_Operation)
	*p = x
	return p
}

func (x WireGuardPeerNotification_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WireGuardPeerNotification_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_vpncfg_proto_enumTypes[1].Descriptor()
}

func (WireGuardPeerNotification_Operation) Type() protoreflect.EnumType {
	return &file_proto_v2_vpncfg_proto_enumTypes[1]
}

func (x WireGuardPeerNotification_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WireGuardPeerNotification_Operation.Descriptor instead.
func (WireGuardPeerNotification_Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{6, 0}
}

type SubscribeWGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SubscribeWGRequest_Subscribe
	//	*SubscribeWGRequest_Response
	Data isSubscribeWGRequest_Data `protobuf_oneof:"data"`
}

func (x *SubscribeWGRequest) Reset() {
	*x = SubscribeWGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeWGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeWGRequest) ProtoMessage() {}

func (x *SubscribeWGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeWGRequest.ProtoReflect.Descriptor instead.
func (*SubscribeWGRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{0}
}

func (m *SubscribeWGRequest) GetData() isSubscribeWGRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SubscribeWGRequest) GetSubscribe() *Subscribe {
	if x, ok := x.GetData().(*SubscribeWGRequest_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (x *SubscribeWGRequest) GetResponse() *RPCStatus {
	if x, ok := x.GetData().(*SubscribeWGRequest_Response); ok {
		return x.Response
	}
	return nil
}

type isSubscribeWGRequest_Data interface {
	isSubscribeWGRequest_Data()
}

type SubscribeWGRequest_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type SubscribeWGRequest_Response struct {
	Response *RPCStatus `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*SubscribeWGRequest_Subscribe) isSubscribeWGRequest_Data() {}

func (*SubscribeWGRequest_Response) isSubscribeWGRequest_Data() {}

type GetConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             GetConfigurationResponse_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.v2.GetConfigurationResponse_Type" json:"type,omitempty"`
	TelemetryEnabled bool                          `protobuf:"varint,2,opt,name=telemetry_enabled,json=telemetryEnabled,proto3" json:"telemetry_enabled,omitempty"`
	// Types that are assignable to VpnProto:
	//
	//	*GetConfigurationResponse_Wg
	VpnProto isGetConfigurationResponse_VpnProto `protobuf_oneof:"vpn_proto"`
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigurationResponse) GetType() GetConfigurationResponse_Type {
	if x != nil {
		return x.Type
	}
	return GetConfigurationResponse_TYPE_UNDEFINED_UNSPECIFIED
}

func (x *GetConfigurationResponse) GetTelemetryEnabled() bool {
	if x != nil {
		return x.TelemetryEnabled
	}
	return false
}

func (m *GetConfigurationResponse) GetVpnProto() isGetConfigurationResponse_VpnProto {
	if m != nil {
		return m.VpnProto
	}
	return nil
}

func (x *GetConfigurationResponse) GetWg() *WireGuard {
	if x, ok := x.GetVpnProto().(*GetConfigurationResponse_Wg); ok {
		return x.Wg
	}
	return nil
}

type isGetConfigurationResponse_VpnProto interface {
	isGetConfigurationResponse_VpnProto()
}

type GetConfigurationResponse_Wg struct {
	Wg *WireGuard `protobuf:"bytes,100,opt,name=wg,proto3,oneof"`
}

func (*GetConfigurationResponse_Wg) isGetConfigurationResponse_VpnProto() {}

type WireGuard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Iface *WireGuardInterface `protobuf:"bytes,2,opt,name=iface,proto3" json:"iface,omitempty"`
	Peers []*WireGuardPeer    `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *WireGuard) Reset() {
	*x = WireGuard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuard) ProtoMessage() {}

func (x *WireGuard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuard.ProtoReflect.Descriptor instead.
func (*WireGuard) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{2}
}

func (x *WireGuard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WireGuard) GetIface() *WireGuardInterface {
	if x != nil {
		return x.Iface
	}
	return nil
}

func (x *WireGuard) GetPeers() []*WireGuardPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type WireGuardInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Addresses  []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ListenPort string   `protobuf:"bytes,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Dns        []string `protobuf:"bytes,4,rep,name=dns,proto3" json:"dns,omitempty"`
	Mtu        string   `protobuf:"bytes,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *WireGuardInterface) Reset() {
	*x = WireGuardInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardInterface) ProtoMessage() {}

func (x *WireGuardInterface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardInterface.ProtoReflect.Descriptor instead.
func (*WireGuardInterface) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{3}
}

func (x *WireGuardInterface) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireGuardInterface) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *WireGuardInterface) GetListenPort() string {
	if x != nil {
		return x.ListenPort
	}
	return ""
}

func (x *WireGuardInterface) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *WireGuardInterface) GetMtu() string {
	if x != nil {
		return x.Mtu
	}
	return ""
}

type WireGuardPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey           string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey        string   `protobuf:"bytes,2,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	AllowedIps          []string `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Endpoint            string   `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PersistentKeepalive string   `protobuf:"bytes,5,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
}

func (x *WireGuardPeer) Reset() {
	*x = WireGuardPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeer) ProtoMessage() {}

func (x *WireGuardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeer.ProtoReflect.Descriptor instead.
func (*WireGuardPeer) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{4}
}

func (x *WireGuardPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardPeer) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *WireGuardPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *WireGuardPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardPeer) GetPersistentKeepalive() string {
	if x != nil {
		return x.PersistentKeepalive
	}
	return ""
}

type SubscribeWGResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SubscribeWGResponse_PeerNotification
	//	*SubscribeWGResponse_ConfigNotification
	Data isSubscribeWGResponse_Data `protobuf_oneof:"data"`
}

func (x *SubscribeWGResponse) Reset() {
	*x = SubscribeWGResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeWGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeWGResponse) ProtoMessage() {}

func (x *SubscribeWGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeWGResponse.ProtoReflect.Descriptor instead.
func (*SubscribeWGResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{5}
}

func (m *SubscribeWGResponse) GetData() isSubscribeWGResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SubscribeWGResponse) GetPeerNotification() *WireGuardPeerNotification {
	if x, ok := x.GetData().(*SubscribeWGResponse_PeerNotification); ok {
		return x.PeerNotification
	}
	return nil
}

func (x *SubscribeWGResponse) GetConfigNotification() *WireGuard {
	if x, ok := x.GetData().(*SubscribeWGResponse_ConfigNotification); ok {
		return x.ConfigNotification
	}
	return nil
}

type isSubscribeWGResponse_Data interface {
	isSubscribeWGResponse_Data()
}

type SubscribeWGResponse_PeerNotification struct {
	PeerNotification *WireGuardPeerNotification `protobuf:"bytes,1,opt,name=peer_notification,json=peerNotification,proto3,oneof"`
}

type SubscribeWGResponse_ConfigNotification struct {
	ConfigNotification *WireGuard `protobuf:"bytes,2,opt,name=config_notification,json=configNotification,proto3,oneof"`
}

func (*SubscribeWGResponse_PeerNotification) isSubscribeWGResponse_Data() {}

func (*SubscribeWGResponse_ConfigNotification) isSubscribeWGResponse_Data() {}

type WireGuardPeerNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation WireGuardPeerNotification_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.v2.WireGuardPeerNotification_Operation" json:"operation,omitempty"`
	Peer      *WireGuardPeer                      `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *WireGuardPeerNotification) Reset() {
	*x = WireGuardPeerNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardPeerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeerNotification) ProtoMessage() {}

func (x *WireGuardPeerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeerNotification.ProtoReflect.Descriptor instead.
func (*WireGuardPeerNotification) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{6}
}

func (x *WireGuardPeerNotification) GetOperation() WireGuardPeerNotification_Operation {
	if x != nil {
		return x.Operation
	}
	return WireGuardPeerNotification_OPERATION_UNDEFINED_UNSPECIFIED
}

func (x *WireGuardPeerNotification) GetPeer() *WireGuardPeer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type SendTelemetryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendTelemetryRequest) Reset() {
	*x = SendTelemetryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTelemetryRequest) ProtoMessage() {}

func (x *SendTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTelemetryRequest.ProtoReflect.Descriptor instead.
func (*SendTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{7}
}

func (x *SendTelemetryRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VpnClientServiceGetConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalDeviceId  string `protobuf:"bytes,1,opt,name=external_device_id,json=externalDeviceId,proto3" json:"external_device_id,omitempty"`
	DeviceInformation string `protobuf:"bytes,2,opt,name=device_information,json=deviceInformation,proto3" json:"device_information,omitempty"`
}

func (x *VpnClientServiceGetConfigurationRequest) Reset() {
	*x = VpnClientServiceGetConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VpnClientServiceGetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnClientServiceGetConfigurationRequest) ProtoMessage() {}

func (x *VpnClientServiceGetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnClientServiceGetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*VpnClientServiceGetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{8}
}

func (x *VpnClientServiceGetConfigurationRequest) GetExternalDeviceId() string {
	if x != nil {
		return x.ExternalDeviceId
	}
	return ""
}

func (x *VpnClientServiceGetConfigurationRequest) GetDeviceInformation() string {
	if x != nil {
		return x.DeviceInformation
	}
	return ""
}

type VpnClientServiceGetConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration *GetConfigurationResponse `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *VpnClientServiceGetConfigurationResponse) Reset() {
	*x = VpnClientServiceGetConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_vpncfg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VpnClientServiceGetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnClientServiceGetConfigurationResponse) ProtoMessage() {}

func (x *VpnClientServiceGetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_vpncfg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnClientServiceGetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*VpnClientServiceGetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_vpncfg_proto_rawDescGZIP(), []int{9}
}

func (x *VpnClientServiceGetConfigurationResponse) GetConfiguration() *GetConfigurationResponse {
	if x != nil {
		return x.Configuration
	}
	return nil
}

var File_proto_v2_vpncfg_proto protoreflect.FileDescriptor

var file_proto_v2_vpncfg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x76, 0x70, 0x6e, 0x63, 0x66,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76,
	0x32, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x57, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x09,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x52,
	0x50, 0x43, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf4, 0x01, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x02, 0x77, 0x67, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47,
	0x75, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x02, 0x77, 0x67, 0x22, 0x3a, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46,
	0x49, 0x4e, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x49, 0x52, 0x45, 0x47,
	0x55, 0x41, 0x52, 0x44, 0x10, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x76, 0x70, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x09, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e,
	0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x52, 0x05, 0x69, 0x66, 0x61, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x65, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x12, 0x57, 0x69, 0x72,
	0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6e,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x74, 0x75, 0x22, 0xc3, 0x01, 0x0a, 0x0d, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x50, 0x65, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x65,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x14, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74,
	0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x22, 0xb9, 0x01, 0x0a, 0x13, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x57, 0x47, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x52, 0x0a, 0x11, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x10, 0x70, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69,
	0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf7, 0x01, 0x0a, 0x19, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75,
	0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x4b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76,
	0x32, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2b, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75,
	0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x60, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x1f, 0x4f, 0x50,
	0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45,
	0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x44, 0x44,
	0x5f, 0x50, 0x45, 0x45, 0x52, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x50, 0x45, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4c, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x10, 0x02, 0x22,
	0x2a, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x27,
	0x56, 0x70, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x28, 0x56, 0x70, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x48, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x83, 0x02, 0x0a, 0x10, 0x56,
	0x70, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x50, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x57, 0x47,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x57, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x57, 0x47, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01,
	0x32, 0x8f, 0x01, 0x0a, 0x10, 0x56, 0x70, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x56, 0x70, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x56, 0x70, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x6e, 0x74, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2f, 0x65, 0x6e, 0x74, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x3b, 0x70, 0x62, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v2_vpncfg_proto_rawDescOnce sync.Once
	file_proto_v2_vpncfg_proto_rawDescData = file_proto_v2_vpncfg_proto_rawDesc
)

func file_proto_v2_vpncfg_proto_rawDescGZIP() []byte {
	file_proto_v2_vpncfg_proto_rawDescOnce.Do(func() {
		file_proto_v2_vpncfg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v2_vpncfg_proto_rawDescData)
	})
	return file_proto_v2_vpncfg_proto_rawDescData
}

var file_proto_v2_vpncfg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v2_vpncfg_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_v2_vpncfg_proto_goTypes = []any{
	(GetConfigurationResponse_Type)(0),               // 0: proto.v2.GetConfigurationResponse.Type
	(WireGuardPeerNotification_Operation)(0),         // 1: proto.v2.WireGuardPeerNotification.Operation
	(*SubscribeWGRequest)(nil),                       // 2: proto.v2.SubscribeWGRequest
	(*GetConfigurationResponse)(nil),                 // 3: proto.v2.GetConfigurationResponse
	(*WireGuard)(nil),                                // 4: proto.v2.WireGuard
	(*WireGuardInterface)(nil),                       // 5: proto.v2.WireGuardInterface
	(*WireGuardPeer)(nil),                            // 6: proto.v2.WireGuardPeer
	(*SubscribeWGResponse)(nil),                      // 7: proto.v2.SubscribeWGResponse
	(*WireGuardPeerNotification)(nil),                // 8: proto.v2.WireGuardPeerNotification
	(*SendTelemetryRequest)(nil),                     // 9: proto.v2.SendTelemetryRequest
	(*VpnClientServiceGetConfigurationRequest)(nil),  // 10: proto.v2.VpnClientServiceGetConfigurationRequest
	(*VpnClientServiceGetConfigurationResponse)(nil), // 11: proto.v2.VpnClientServiceGetConfigurationResponse
	(*Subscribe)(nil),                                // 12: proto.v2.Subscribe
	(*RPCStatus)(nil),                                // 13: proto.v2.RPCStatus
	(*emptypb.Empty)(nil),                            // 14: google.protobuf.Empty
}
var file_proto_v2_vpncfg_proto_depIdxs = []int32{
	12, // 0: proto.v2.SubscribeWGRequest.subscribe:type_name -> proto.v2.Subscribe
	13, // 1: proto.v2.SubscribeWGRequest.response:type_name -> proto.v2.RPCStatus
	0,  // 2: proto.v2.GetConfigurationResponse.type:type_name -> proto.v2.GetConfigurationResponse.Type
	4,  // 3: proto.v2.GetConfigurationResponse.wg:type_name -> proto.v2.WireGuard
	5,  // 4: proto.v2.WireGuard.iface:type_name -> proto.v2.WireGuardInterface
	6,  // 5: proto.v2.WireGuard.peers:type_name -> proto.v2.WireGuardPeer
	8,  // 6: proto.v2.SubscribeWGResponse.peer_notification:type_name -> proto.v2.WireGuardPeerNotification
	4,  // 7: proto.v2.SubscribeWGResponse.config_notification:type_name -> proto.v2.WireGuard
	1,  // 8: proto.v2.WireGuardPeerNotification.operation:type_name -> proto.v2.WireGuardPeerNotification.Operation
	6,  // 9: proto.v2.WireGuardPeerNotification.peer:type_name -> proto.v2.WireGuardPeer
	3,  // 10: proto.v2.VpnClientServiceGetConfigurationResponse.configuration:type_name -> proto.v2.GetConfigurationResponse
	14, // 11: proto.v2.VpnServerService.GetConfiguration:input_type -> google.protobuf.Empty
	2,  // 12: proto.v2.VpnServerService.SubscribeWG:input_type -> proto.v2.SubscribeWGRequest
	9,  // 13: proto.v2.VpnServerService.SendTelemetry:input_type -> proto.v2.SendTelemetryRequest
	10, // 14: proto.v2.VpnClientService.GetConfiguration:input_type -> proto.v2.VpnClientServiceGetConfigurationRequest
	3,  // 15: proto.v2.VpnServerService.GetConfiguration:output_type -> proto.v2.GetConfigurationResponse
	7,  // 16: proto.v2.VpnServerService.SubscribeWG:output_type -> proto.v2.SubscribeWGResponse
	14, // 17: proto.v2.VpnServerService.SendTelemetry:output_type -> google.protobuf.Empty
	11, // 18: proto.v2.VpnClientService.GetConfiguration:output_type -> proto.v2.VpnClientServiceGetConfigurationResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_v2_vpncfg_proto_init() }
func file_proto_v2_vpncfg_proto_init() {
	if File_proto_v2_vpncfg_proto != nil {
		return
	}
	file_proto_v2_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_v2_vpncfg_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeWGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeWGResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardPeerNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SendTelemetryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*VpnClientServiceGetConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_vpncfg_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*VpnClientServiceGetConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_v2_vpncfg_proto_msgTypes[0].OneofWrappers = []any{
		(*SubscribeWGRequest_Subscribe)(nil),
		(*SubscribeWGRequest_Response)(nil),
	}
	file_proto_v2_vpncfg_proto_msgTypes[1].OneofWrappers = []any{
		(*GetConfigurationResponse_Wg)(nil),
	}
	file_proto_v2_vpncfg_proto_msgTypes[5].OneofWrappers = []any{
		(*SubscribeWGResponse_PeerNotification)(nil),
		(*SubscribeWGResponse_ConfigNotification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v2_vpncfg_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_v2_vpncfg_proto_goTypes,
		DependencyIndexes: file_proto_v2_vpncfg_proto_depIdxs,
		EnumInfos:         file_proto_v2_vpncfg_proto_enumTypes,
		MessageInfos:      file_proto_v2_vpncfg_proto_msgTypes,
	}.Build()
	File_proto_v2_vpncfg_proto = out.File
	file_proto_v2_vpncfg_proto_rawDesc = nil
	file_proto_v2_vpncfg_proto_goTypes = nil
	file_proto_v2_vpncfg_proto_depIdxs = nil
}
