{
 "title": "EntGuard",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": { "query": "label_values(server)" } },
   { "name": "key", "label": "key", "query": { "query": "label_values(public_key)" } }
  ]
 },
 "panels": [
  {
   "title": "WireGuard Peer Transmit & Receive Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(wireguard_peer_tx_bytes{server=~\"${server}\", public_key=~\"${key}\"}[1m])",
     "legendFormat": "TX byte rate of peer with public key {{public_key}} at {{server}} server"
    },
    {
     "expr": "rate(wireguard_peer_rx_bytes{server=~\"${server}\", public_key=~\"${key}\"}[1m])",
     "legendFormat": "RX byte rate of peer with public key {{public_key}} at {{server}} server"
    }
   ]
  },
  {
   "title": "Transmit Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_sent{server=~\"${server}\"}[1m])",
     "legendFormat": "TX bytes rate of {{interface}} device of {{server}} server"
    }
   ]
  },
  {
   "title": "Receive Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{server=~\"${server}\"}[1m])",
     "legendFormat": "RX bytes rate of {{interface}} device of {{server}} server"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Quantity of time spend by CPU in specific mode",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\", server=~\"${server}\"}",
     "legendFormat": "total cpu time spent in system mode by {{server}} server"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_active{server=~\"${server}\"}",
     "legendFormat": "active memory of {{server}} server"
    },
    {
     "expr": "mem_total{server=~\"${server}\"}",
     "legendFormat": "total memory of {{server}} server"
    }
   ]
  },
  {
   "title": "Configured WireGuard Peer Count",
   "type": "timeseries",
   "description": "Configured WireGuard Peer Count shows how many peers are in the WireGuard device configuration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wireguard_device_peers{server=~\"${server}\"}",
     "legendFormat": "peer count of {{server}} server"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "net_err_in{server=~\"${server}\"} - net_err_in{server=~\"${server}\"} offset $__interval >= 0",
     "legendFormat": "incoming errors detected on {{interface}} interface at {{server}} server"
    },
    {
     "expr": "net_err_out{server=~\"${server}\"} - net_err_out{server=~\"${server}\"} offset $__interval >= 0",
     "legendFormat": "outcoming errors detected on {{interface}} interface at {{server}} server"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}