// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/v1/vpncfg.proto

package pbapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error codes for gRPC APIs.
// For more information: https://grpc.github.io/grpc/core/md_doc_statuscodes.html
type RPCErrorCode int32

const (
	RPCErrorCode_OK                  RPCErrorCode = 0
	RPCErrorCode_CANCELLED           RPCErrorCode = 1
	RPCErrorCode_UNKNOWN             RPCErrorCode = 2
	RPCErrorCode_INVALID_ARGUMENT    RPCErrorCode = 3
	RPCErrorCode_DEADLINE_EXCEEDED   RPCErrorCode = 4
	RPCErrorCode_NOT_FOUND           RPCErrorCode = 5
	RPCErrorCode_ALREADY_EXISTS      RPCErrorCode = 6
	RPCErrorCode_PERMISSION_DENIED   RPCErrorCode = 7
	RPCErrorCode_RESOURCE_EXHAUSTED  RPCErrorCode = 8
	RPCErrorCode_FAILED_PRECONDITION RPCErrorCode = 9
	RPCErrorCode_ABORTED             RPCErrorCode = 10
	RPCErrorCode_OUT_OF_RANGE        RPCErrorCode = 11
	RPCErrorCode_UNIMPLEMENTED       RPCErrorCode = 12
	RPCErrorCode_INTERNAL            RPCErrorCode = 13
	RPCErrorCode_UNAVAILABLE         RPCErrorCode = 14
	RPCErrorCode_DATA_LOSS           RPCErrorCode = 15
	RPCErrorCode_UNAUTHENTICATED     RPCErrorCode = 16
)

// Enum value maps for RPCErrorCode.
var (
	RPCErrorCode_name = map[int32]string{
		0:  "OK",
		1:  "CANCELLED",
		2:  "UNKNOWN",
		3:  "INVALID_ARGUMENT",
		4:  "DEADLINE_EXCEEDED",
		5:  "NOT_FOUND",
		6:  "ALREADY_EXISTS",
		7:  "PERMISSION_DENIED",
		8:  "RESOURCE_EXHAUSTED",
		9:  "FAILED_PRECONDITION",
		10: "ABORTED",
		11: "OUT_OF_RANGE",
		12: "UNIMPLEMENTED",
		13: "INTERNAL",
		14: "UNAVAILABLE",
		15: "DATA_LOSS",
		16: "UNAUTHENTICATED",
	}
	RPCErrorCode_value = map[string]int32{
		"OK":                  0,
		"CANCELLED":           1,
		"UNKNOWN":             2,
		"INVALID_ARGUMENT":    3,
		"DEADLINE_EXCEEDED":   4,
		"NOT_FOUND":           5,
		"ALREADY_EXISTS":      6,
		"PERMISSION_DENIED":   7,
		"RESOURCE_EXHAUSTED":  8,
		"FAILED_PRECONDITION": 9,
		"ABORTED":             10,
		"OUT_OF_RANGE":        11,
		"UNIMPLEMENTED":       12,
		"INTERNAL":            13,
		"UNAVAILABLE":         14,
		"DATA_LOSS":           15,
		"UNAUTHENTICATED":     16,
	}
)

func (x RPCErrorCode) Enum() *RPCErrorCode {
	p := new(RPCErrorCode)
	*p = x
	return p
}

func (x RPCErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPCErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_vpncfg_proto_enumTypes[0].Descriptor()
}

func (RPCErrorCode) Type() protoreflect.EnumType {
	return &file_proto_v1_vpncfg_proto_enumTypes[0]
}

func (x RPCErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPCErrorCode.Descriptor instead.
func (RPCErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{0}
}

type Configuration_Type int32

const (
	Configuration_UNDEFINED_TYPE Configuration_Type = 0
	Configuration_WIREGUARD      Configuration_Type = 1
)

// Enum value maps for Configuration_Type.
var (
	Configuration_Type_name = map[int32]string{
		0: "UNDEFINED_TYPE",
		1: "WIREGUARD",
	}
	Configuration_Type_value = map[string]int32{
		"UNDEFINED_TYPE": 0,
		"WIREGUARD":      1,
	}
)

func (x Configuration_Type) Enum() *Configuration_Type {
	p := new(Configuration_Type)
	*p = x
	return p
}

func (x Configuration_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Configuration_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_vpncfg_proto_enumTypes[1].Descriptor()
}

func (Configuration_Type) Type() protoreflect.EnumType {
	return &file_proto_v1_vpncfg_proto_enumTypes[1]
}

func (x Configuration_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Configuration_Type.Descriptor instead.
func (Configuration_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{4, 0}
}

type WireGuardPeerNotification_Operation int32

const (
	WireGuardPeerNotification_UNDEFINED WireGuardPeerNotification_Operation = 0
	WireGuardPeerNotification_ADD_PEER  WireGuardPeerNotification_Operation = 1
	WireGuardPeerNotification_DEL_PEER  WireGuardPeerNotification_Operation = 2
)

// Enum value maps for WireGuardPeerNotification_Operation.
var (
	WireGuardPeerNotification_Operation_name = map[int32]string{
		0: "UNDEFINED",
		1: "ADD_PEER",
		2: "DEL_PEER",
	}
	WireGuardPeerNotification_Operation_value = map[string]int32{
		"UNDEFINED": 0,
		"ADD_PEER":  1,
		"DEL_PEER":  2,
	}
)

func (x WireGuardPeerNotification_Operation) Enum() *WireGuardPeerNotification_Operation {
	p := new(WireGuardPeerNotification_Operation)
	*p = x
	return p
}

func (x WireGuardPeerNotification_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WireGuardPeerNotification_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_vpncfg_proto_enumTypes[2].Descriptor()
}

func (WireGuardPeerNotification_Operation) Type() protoreflect.EnumType {
	return &file_proto_v1_vpncfg_proto_enumTypes[2]
}

func (x WireGuardPeerNotification_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WireGuardPeerNotification_Operation.Descriptor instead.
func (WireGuardPeerNotification_Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{9, 0}
}

type RPCStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    RPCErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=proto.RPCErrorCode" json:"code,omitempty"`
	Message string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RPCStatus) Reset() {
	*x = RPCStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCStatus) ProtoMessage() {}

func (x *RPCStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCStatus.ProtoReflect.Descriptor instead.
func (*RPCStatus) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{0}
}

func (x *RPCStatus) GetCode() RPCErrorCode {
	if x != nil {
		return x.Code
	}
	return RPCErrorCode_OK
}

func (x *RPCStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{1}
}

type Subscribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{2}
}

type SubscribeWGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SubscribeWGRequest_Subscribe
	//	*SubscribeWGRequest_Response
	Data isSubscribeWGRequest_Data `protobuf_oneof:"data"`
}

func (x *SubscribeWGRequest) Reset() {
	*x = SubscribeWGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeWGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeWGRequest) ProtoMessage() {}

func (x *SubscribeWGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeWGRequest.ProtoReflect.Descriptor instead.
func (*SubscribeWGRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{3}
}

func (m *SubscribeWGRequest) GetData() isSubscribeWGRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SubscribeWGRequest) GetSubscribe() *Subscribe {
	if x, ok := x.GetData().(*SubscribeWGRequest_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (x *SubscribeWGRequest) GetResponse() *RPCStatus {
	if x, ok := x.GetData().(*SubscribeWGRequest_Response); ok {
		return x.Response
	}
	return nil
}

type isSubscribeWGRequest_Data interface {
	isSubscribeWGRequest_Data()
}

type SubscribeWGRequest_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type SubscribeWGRequest_Response struct {
	Response *RPCStatus `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*SubscribeWGRequest_Subscribe) isSubscribeWGRequest_Data() {}

func (*SubscribeWGRequest_Response) isSubscribeWGRequest_Data() {}

type Configuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             Configuration_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.Configuration_Type" json:"type,omitempty"`
	TelemetryEnabled bool               `protobuf:"varint,2,opt,name=telemetry_enabled,json=telemetryEnabled,proto3" json:"telemetry_enabled,omitempty"`
	// Types that are assignable to VpnProto:
	//
	//	*Configuration_Wg
	VpnProto isConfiguration_VpnProto `protobuf_oneof:"vpn_proto"`
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{4}
}

func (x *Configuration) GetType() Configuration_Type {
	if x != nil {
		return x.Type
	}
	return Configuration_UNDEFINED_TYPE
}

func (x *Configuration) GetTelemetryEnabled() bool {
	if x != nil {
		return x.TelemetryEnabled
	}
	return false
}

func (m *Configuration) GetVpnProto() isConfiguration_VpnProto {
	if m != nil {
		return m.VpnProto
	}
	return nil
}

func (x *Configuration) GetWg() *WireGuard {
	if x, ok := x.GetVpnProto().(*Configuration_Wg); ok {
		return x.Wg
	}
	return nil
}

type isConfiguration_VpnProto interface {
	isConfiguration_VpnProto()
}

type Configuration_Wg struct {
	Wg *WireGuard `protobuf:"bytes,100,opt,name=wg,proto3,oneof"`
}

func (*Configuration_Wg) isConfiguration_VpnProto() {}

type WireGuard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Iface *WireGuardInterface `protobuf:"bytes,2,opt,name=iface,proto3" json:"iface,omitempty"`
	Peers []*WireGuardPeer    `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *WireGuard) Reset() {
	*x = WireGuard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuard) ProtoMessage() {}

func (x *WireGuard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuard.ProtoReflect.Descriptor instead.
func (*WireGuard) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{5}
}

func (x *WireGuard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WireGuard) GetIface() *WireGuardInterface {
	if x != nil {
		return x.Iface
	}
	return nil
}

func (x *WireGuard) GetPeers() []*WireGuardPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type WireGuardInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Addresses  []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ListenPort string   `protobuf:"bytes,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Dns        []string `protobuf:"bytes,4,rep,name=dns,proto3" json:"dns,omitempty"`
	Mtu        string   `protobuf:"bytes,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *WireGuardInterface) Reset() {
	*x = WireGuardInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardInterface) ProtoMessage() {}

func (x *WireGuardInterface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardInterface.ProtoReflect.Descriptor instead.
func (*WireGuardInterface) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{6}
}

func (x *WireGuardInterface) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireGuardInterface) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *WireGuardInterface) GetListenPort() string {
	if x != nil {
		return x.ListenPort
	}
	return ""
}

func (x *WireGuardInterface) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *WireGuardInterface) GetMtu() string {
	if x != nil {
		return x.Mtu
	}
	return ""
}

// In the WireGuardPeer message, all occurences of "endpoint" mean "address:port"
type WireGuardPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey           string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey        string   `protobuf:"bytes,2,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	AllowedIps          []string `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Endpoint            string   `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PersistentKeepalive string   `protobuf:"bytes,5,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	HealthcheckEndpoint string   `protobuf:"bytes,6,opt,name=healthcheck_endpoint,json=healthcheckEndpoint,proto3" json:"healthcheck_endpoint,omitempty"`
}

func (x *WireGuardPeer) Reset() {
	*x = WireGuardPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeer) ProtoMessage() {}

func (x *WireGuardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeer.ProtoReflect.Descriptor instead.
func (*WireGuardPeer) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{7}
}

func (x *WireGuardPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardPeer) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *WireGuardPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *WireGuardPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardPeer) GetPersistentKeepalive() string {
	if x != nil {
		return x.PersistentKeepalive
	}
	return ""
}

func (x *WireGuardPeer) GetHealthcheckEndpoint() string {
	if x != nil {
		return x.HealthcheckEndpoint
	}
	return ""
}

type WireGuardNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*WireGuardNotification_PeerNotification
	//	*WireGuardNotification_ConfigNotification
	Data isWireGuardNotification_Data `protobuf_oneof:"data"`
}

func (x *WireGuardNotification) Reset() {
	*x = WireGuardNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardNotification) ProtoMessage() {}

func (x *WireGuardNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardNotification.ProtoReflect.Descriptor instead.
func (*WireGuardNotification) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{8}
}

func (m *WireGuardNotification) GetData() isWireGuardNotification_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *WireGuardNotification) GetPeerNotification() *WireGuardPeerNotification {
	if x, ok := x.GetData().(*WireGuardNotification_PeerNotification); ok {
		return x.PeerNotification
	}
	return nil
}

func (x *WireGuardNotification) GetConfigNotification() *WireGuard {
	if x, ok := x.GetData().(*WireGuardNotification_ConfigNotification); ok {
		return x.ConfigNotification
	}
	return nil
}

type isWireGuardNotification_Data interface {
	isWireGuardNotification_Data()
}

type WireGuardNotification_PeerNotification struct {
	PeerNotification *WireGuardPeerNotification `protobuf:"bytes,1,opt,name=peer_notification,json=peerNotification,proto3,oneof"`
}

type WireGuardNotification_ConfigNotification struct {
	ConfigNotification *WireGuard `protobuf:"bytes,2,opt,name=config_notification,json=configNotification,proto3,oneof"`
}

func (*WireGuardNotification_PeerNotification) isWireGuardNotification_Data() {}

func (*WireGuardNotification_ConfigNotification) isWireGuardNotification_Data() {}

type WireGuardPeerNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation WireGuardPeerNotification_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.WireGuardPeerNotification_Operation" json:"operation,omitempty"`
	Peer      *WireGuardPeer                      `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *WireGuardPeerNotification) Reset() {
	*x = WireGuardPeerNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardPeerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeerNotification) ProtoMessage() {}

func (x *WireGuardPeerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeerNotification.ProtoReflect.Descriptor instead.
func (*WireGuardPeerNotification) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{9}
}

func (x *WireGuardPeerNotification) GetOperation() WireGuardPeerNotification_Operation {
	if x != nil {
		return x.Operation
	}
	return WireGuardPeerNotification_UNDEFINED
}

func (x *WireGuardPeerNotification) GetPeer() *WireGuardPeer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type WireGuardTelemetry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WireGuardTelemetry) Reset() {
	*x = WireGuardTelemetry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardTelemetry) ProtoMessage() {}

func (x *WireGuardTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardTelemetry.ProtoReflect.Descriptor instead.
func (*WireGuardTelemetry) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{10}
}

func (x *WireGuardTelemetry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClientConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalDeviceId  string `protobuf:"bytes,1,opt,name=external_device_id,json=externalDeviceId,proto3" json:"external_device_id,omitempty"`
	DeviceInformation string `protobuf:"bytes,2,opt,name=device_information,json=deviceInformation,proto3" json:"device_information,omitempty"`
}

func (x *ClientConfigurationRequest) Reset() {
	*x = ClientConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigurationRequest) ProtoMessage() {}

func (x *ClientConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ClientConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{11}
}

func (x *ClientConfigurationRequest) GetExternalDeviceId() string {
	if x != nil {
		return x.ExternalDeviceId
	}
	return ""
}

func (x *ClientConfigurationRequest) GetDeviceInformation() string {
	if x != nil {
		return x.DeviceInformation
	}
	return ""
}

type ClientConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration *Configuration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	SessionId     string         `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *ClientConfigurationResponse) Reset() {
	*x = ClientConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_vpncfg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigurationResponse) ProtoMessage() {}

func (x *ClientConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_vpncfg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigurationResponse.ProtoReflect.Descriptor instead.
func (*ClientConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_vpncfg_proto_rawDescGZIP(), []int{12}
}

func (x *ClientConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *ClientConfigurationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_proto_v1_vpncfg_proto protoreflect.FileDescriptor

var file_proto_v1_vpncfg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x70, 0x6e, 0x63, 0x66,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e,
	0x0a, 0x09, 0x52, 0x50, 0x43, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x22, 0x7e, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x57, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x2e, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x50, 0x43, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xc7, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x12, 0x22, 0x0a, 0x02, 0x77, 0x67, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x02, 0x77, 0x67, 0x22, 0x29, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x0e, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x49, 0x52, 0x45, 0x47, 0x55, 0x41, 0x52, 0x44, 0x10,
	0x01, 0x42, 0x0b, 0x0a, 0x09, 0x76, 0x70, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c,
	0x0a, 0x09, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2f, 0x0a, 0x05, 0x69, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x05, 0x69, 0x66, 0x61, 0x63, 0x65,
	0x12, 0x2a, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x22, 0x98, 0x01, 0x0a,
	0x12, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x22, 0xf6, 0x01, 0x0a, 0x0d, 0x57, 0x69, 0x72, 0x65,
	0x47, 0x75, 0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x70, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a,
	0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x70, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x14, 0x70, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69,
	0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x31, 0x0a,
	0x14, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x22, 0xb5, 0x01, 0x0a, 0x15, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x11, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69,
	0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x10, 0x70, 0x65, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x13, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xc7, 0x01, 0x0a, 0x19, 0x57, 0x69, 0x72,
	0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x28, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x09, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46,
	0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x44, 0x5f, 0x50, 0x45,
	0x45, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x4c, 0x5f, 0x50, 0x45, 0x45, 0x52,
	0x10, 0x02, 0x22, 0x28, 0x0a, 0x12, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x54,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x79, 0x0a, 0x1a,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x78, 0x0a, 0x1b, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x2a, 0xbf, 0x02, 0x0a, 0x0c, 0x52, 0x50, 0x43, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41,
	0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11,
	0x44, 0x45, 0x41, 0x44, 0x4c, 0x49, 0x4e, 0x45, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45,
	0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58,
	0x49, 0x53, 0x54, 0x53, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x07, 0x12, 0x16, 0x0a,
	0x12, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x45, 0x58, 0x48, 0x41, 0x55, 0x53,
	0x54, 0x45, 0x44, 0x10, 0x08, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f,
	0x50, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x09, 0x12, 0x0b,
	0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x4f,
	0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x0b, 0x12, 0x11, 0x0a,
	0x0d, 0x55, 0x4e, 0x49, 0x4d, 0x50, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x0c,
	0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x0d, 0x12, 0x0f,
	0x0a, 0x0b, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x0e, 0x12,
	0x0d, 0x0a, 0x09, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4c, 0x4f, 0x53, 0x53, 0x10, 0x0f, 0x12, 0x13,
	0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45,
	0x44, 0x10, 0x10, 0x32, 0xcc, 0x01, 0x0a, 0x04, 0x56, 0x70, 0x6e, 0x53, 0x12, 0x38, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x57, 0x47, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x57, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61,
	0x72, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x3c, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69,
	0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x28, 0x01, 0x32, 0x63, 0x0a, 0x04, 0x56, 0x70, 0x6e, 0x43, 0x12, 0x5b, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x74, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2f, 0x65,
	0x6e, 0x74, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31,
	0x3b, 0x70, 0x62, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_vpncfg_proto_rawDescOnce sync.Once
	file_proto_v1_vpncfg_proto_rawDescData = file_proto_v1_vpncfg_proto_rawDesc
)

func file_proto_v1_vpncfg_proto_rawDescGZIP() []byte {
	file_proto_v1_vpncfg_proto_rawDescOnce.Do(func() {
		file_proto_v1_vpncfg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_vpncfg_proto_rawDescData)
	})
	return file_proto_v1_vpncfg_proto_rawDescData
}

var file_proto_v1_vpncfg_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_v1_vpncfg_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_v1_vpncfg_proto_goTypes = []any{
	(RPCErrorCode)(0),                        // 0: proto.RPCErrorCode
	(Configuration_Type)(0),                  // 1: proto.Configuration.Type
	(WireGuardPeerNotification_Operation)(0), // 2: proto.WireGuardPeerNotification.Operation
	(*RPCStatus)(nil),                        // 3: proto.RPCStatus
	(*Empty)(nil),                            // 4: proto.Empty
	(*Subscribe)(nil),                        // 5: proto.Subscribe
	(*SubscribeWGRequest)(nil),               // 6: proto.SubscribeWGRequest
	(*Configuration)(nil),                    // 7: proto.Configuration
	(*WireGuard)(nil),                        // 8: proto.WireGuard
	(*WireGuardInterface)(nil),               // 9: proto.WireGuardInterface
	(*WireGuardPeer)(nil),                    // 10: proto.WireGuardPeer
	(*WireGuardNotification)(nil),            // 11: proto.WireGuardNotification
	(*WireGuardPeerNotification)(nil),        // 12: proto.WireGuardPeerNotification
	(*WireGuardTelemetry)(nil),               // 13: proto.WireGuardTelemetry
	(*ClientConfigurationRequest)(nil),       // 14: proto.ClientConfigurationRequest
	(*ClientConfigurationResponse)(nil),      // 15: proto.ClientConfigurationResponse
}
var file_proto_v1_vpncfg_proto_depIdxs = []int32{
	0,  // 0: proto.RPCStatus.code:type_name -> proto.RPCErrorCode
	5,  // 1: proto.SubscribeWGRequest.subscribe:type_name -> proto.Subscribe
	3,  // 2: proto.SubscribeWGRequest.response:type_name -> proto.RPCStatus
	1,  // 3: proto.Configuration.type:type_name -> proto.Configuration.Type
	8,  // 4: proto.Configuration.wg:type_name -> proto.WireGuard
	9,  // 5: proto.WireGuard.iface:type_name -> proto.WireGuardInterface
	10, // 6: proto.WireGuard.peers:type_name -> proto.WireGuardPeer
	12, // 7: proto.WireGuardNotification.peer_notification:type_name -> proto.WireGuardPeerNotification
	8,  // 8: proto.WireGuardNotification.config_notification:type_name -> proto.WireGuard
	2,  // 9: proto.WireGuardPeerNotification.operation:type_name -> proto.WireGuardPeerNotification.Operation
	10, // 10: proto.WireGuardPeerNotification.peer:type_name -> proto.WireGuardPeer
	7,  // 11: proto.ClientConfigurationResponse.configuration:type_name -> proto.Configuration
	4,  // 12: proto.VpnS.GetConfiguration:input_type -> proto.Empty
	6,  // 13: proto.VpnS.SubscribeWG:input_type -> proto.SubscribeWGRequest
	13, // 14: proto.VpnS.SendTelemetry:input_type -> proto.WireGuardTelemetry
	14, // 15: proto.VpnC.GetConfiguration:input_type -> proto.ClientConfigurationRequest
	7,  // 16: proto.VpnS.GetConfiguration:output_type -> proto.Configuration
	11, // 17: proto.VpnS.SubscribeWG:output_type -> proto.WireGuardNotification
	4,  // 18: proto.VpnS.SendTelemetry:output_type -> proto.Empty
	15, // 19: proto.VpnC.GetConfiguration:output_type -> proto.ClientConfigurationResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_v1_vpncfg_proto_init() }
func file_proto_v1_vpncfg_proto_init() {
	if File_proto_v1_vpncfg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_vpncfg_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RPCStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Subscribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeWGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Configuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardPeerNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*WireGuardTelemetry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ClientConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_vpncfg_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ClientConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_v1_vpncfg_proto_msgTypes[3].OneofWrappers = []any{
		(*SubscribeWGRequest_Subscribe)(nil),
		(*SubscribeWGRequest_Response)(nil),
	}
	file_proto_v1_vpncfg_proto_msgTypes[4].OneofWrappers = []any{
		(*Configuration_Wg)(nil),
	}
	file_proto_v1_vpncfg_proto_msgTypes[8].OneofWrappers = []any{
		(*WireGuardNotification_PeerNotification)(nil),
		(*WireGuardNotification_ConfigNotification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_vpncfg_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_v1_vpncfg_proto_goTypes,
		DependencyIndexes: file_proto_v1_vpncfg_proto_depIdxs,
		EnumInfos:         file_proto_v1_vpncfg_proto_enumTypes,
		MessageInfos:      file_proto_v1_vpncfg_proto_msgTypes,
	}.Build()
	File_proto_v1_vpncfg_proto = out.File
	file_proto_v1_vpncfg_proto_rawDesc = nil
	file_proto_v1_vpncfg_proto_goTypes = nil
	file_proto_v1_vpncfg_proto_depIdxs = nil
}
