// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/v1/vpncfg.proto

package pbapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VpnS_GetConfiguration_FullMethodName = "/proto.VpnS/GetConfiguration"
	VpnS_SubscribeWG_FullMethodName      = "/proto.VpnS/SubscribeWG"
	VpnS_SendTelemetry_FullMethodName    = "/proto.VpnS/SendTelemetry"
)

// VpnSClient is the client API for VpnS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnSClient interface {
	GetConfiguration(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Configuration, error)
	SubscribeWG(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeWGRequest, WireGuardNotification], error)
	SendTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WireGuardTelemetry, Empty], error)
}

type vpnSClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnSClient(cc grpc.ClientConnInterface) VpnSClient {
	return &vpnSClient{cc}
}

func (c *vpnSClient) GetConfiguration(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Configuration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Configuration)
	err := c.cc.Invoke(ctx, VpnS_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnSClient) SubscribeWG(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeWGRequest, WireGuardNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VpnS_ServiceDesc.Streams[0], VpnS_SubscribeWG_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeWGRequest, WireGuardNotification]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnS_SubscribeWGClient = grpc.BidiStreamingClient[SubscribeWGRequest, WireGuardNotification]

func (c *vpnSClient) SendTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WireGuardTelemetry, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VpnS_ServiceDesc.Streams[1], VpnS_SendTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WireGuardTelemetry, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnS_SendTelemetryClient = grpc.ClientStreamingClient[WireGuardTelemetry, Empty]

// VpnSServer is the server API for VpnS service.
// All implementations must embed UnimplementedVpnSServer
// for forward compatibility.
type VpnSServer interface {
	GetConfiguration(context.Context, *Empty) (*Configuration, error)
	SubscribeWG(grpc.BidiStreamingServer[SubscribeWGRequest, WireGuardNotification]) error
	SendTelemetry(grpc.ClientStreamingServer[WireGuardTelemetry, Empty]) error
	mustEmbedUnimplementedVpnSServer()
}

// UnimplementedVpnSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnSServer struct{}

func (UnimplementedVpnSServer) GetConfiguration(context.Context, *Empty) (*Configuration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedVpnSServer) SubscribeWG(grpc.BidiStreamingServer[SubscribeWGRequest, WireGuardNotification]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeWG not implemented")
}
func (UnimplementedVpnSServer) SendTelemetry(grpc.ClientStreamingServer[WireGuardTelemetry, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method SendTelemetry not implemented")
}
func (UnimplementedVpnSServer) mustEmbedUnimplementedVpnSServer() {}
func (UnimplementedVpnSServer) testEmbeddedByValue()              {}

// UnsafeVpnSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnSServer will
// result in compilation errors.
type UnsafeVpnSServer interface {
	mustEmbedUnimplementedVpnSServer()
}

func RegisterVpnSServer(s grpc.ServiceRegistrar, srv VpnSServer) {
	// If the following call pancis, it indicates UnimplementedVpnSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VpnS_ServiceDesc, srv)
}

func _VpnS_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnSServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnS_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnSServer).GetConfiguration(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnS_SubscribeWG_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VpnSServer).SubscribeWG(&grpc.GenericServerStream[SubscribeWGRequest, WireGuardNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnS_SubscribeWGServer = grpc.BidiStreamingServer[SubscribeWGRequest, WireGuardNotification]

func _VpnS_SendTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VpnSServer).SendTelemetry(&grpc.GenericServerStream[WireGuardTelemetry, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnS_SendTelemetryServer = grpc.ClientStreamingServer[WireGuardTelemetry, Empty]

// VpnS_ServiceDesc is the grpc.ServiceDesc for VpnS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VpnS",
	HandlerType: (*VpnSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _VpnS_GetConfiguration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeWG",
			Handler:       _VpnS_SubscribeWG_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendTelemetry",
			Handler:       _VpnS_SendTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v1/vpncfg.proto",
}

const (
	VpnC_GetConfiguration_FullMethodName = "/proto.VpnC/GetConfiguration"
)

// VpnCClient is the client API for VpnC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnCClient interface {
	GetConfiguration(ctx context.Context, in *ClientConfigurationRequest, opts ...grpc.CallOption) (*ClientConfigurationResponse, error)
}

type vpnCClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnCClient(cc grpc.ClientConnInterface) VpnCClient {
	return &vpnCClient{cc}
}

func (c *vpnCClient) GetConfiguration(ctx context.Context, in *ClientConfigurationRequest, opts ...grpc.CallOption) (*ClientConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientConfigurationResponse)
	err := c.cc.Invoke(ctx, VpnC_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnCServer is the server API for VpnC service.
// All implementations must embed UnimplementedVpnCServer
// for forward compatibility.
type VpnCServer interface {
	GetConfiguration(context.Context, *ClientConfigurationRequest) (*ClientConfigurationResponse, error)
	mustEmbedUnimplementedVpnCServer()
}

// UnimplementedVpnCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnCServer struct{}

func (UnimplementedVpnCServer) GetConfiguration(context.Context, *ClientConfigurationRequest) (*ClientConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedVpnCServer) mustEmbedUnimplementedVpnCServer() {}
func (UnimplementedVpnCServer) testEmbeddedByValue()              {}

// UnsafeVpnCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnCServer will
// result in compilation errors.
type UnsafeVpnCServer interface {
	mustEmbedUnimplementedVpnCServer()
}

func RegisterVpnCServer(s grpc.ServiceRegistrar, srv VpnCServer) {
	// If the following call pancis, it indicates UnimplementedVpnCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VpnC_ServiceDesc, srv)
}

func _VpnC_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnCServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnC_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnCServer).GetConfiguration(ctx, req.(*ClientConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VpnC_ServiceDesc is the grpc.ServiceDesc for VpnC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VpnC",
	HandlerType: (*VpnCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _VpnC_GetConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/vpncfg.proto",
}
